// Generated by Melange

import * as Caml_obj from "melange.js/caml_obj.js";
import * as Caml_option from "melange.js/caml_option.js";
import * as Curry from "melange.js/curry.js";
import * as Js__Js_dict from "melange.js/js_dict.js";
import * as Js__Js_json from "melange.js/js_json.js";
import * as Melange__Context_gen from "./context_gen.js";
import * as Melange__Domain from "./domain.js";
import * as Melange__Envelope from "./envelope.js";
import * as Melange__Hono from "./hono.js";
import * as Melange__Html from "./html.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Load_tree from "./load_tree.js";
import * as Melange__Markdown from "./markdown.js";
import * as Melange__Memory_ml from "./memory_ml.js";
import * as Melange__Overlay from "./overlay.js";
import * as Melange__Paths from "./paths.js";
import * as Melange__Rebuild from "./rebuild.js";
import * as Melange__Speckit from "./speckit.js";
import * as Melange__Views from "./views.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Stdlib__String from "melange/string.js";
import * as Bunsqlite from "bun:sqlite";
import * as Hono from "hono";
import * as Nodefs from "node:fs";

function hit_json_list(hits) {
  return Stdlib__List.map((function (h) {
    return Melange__Views.Json.obj({
      hd: [
        "path",
        Melange__Views.Json.str(h.hit_path)
      ],
      tl: {
        hd: [
          "title",
          Melange__Views.Json.str(h.hit_title)
        ],
        tl: {
          hd: [
            "as_of",
            Melange__Views.Json.opt_str(h.hit_as_of)
          ],
          tl: {
            hd: [
              "status",
              Melange__Views.Json.str(h.hit_status)
            ],
            tl: {
              hd: [
                "excerpt",
                Melange__Views.Json.str(h.hit_excerpt)
              ],
              tl: {
                hd: [
                  "kind",
                  Melange__Views.Json.str(h.hit_kind)
                ],
                tl: /* [] */ 0
              }
            }
          }
        }
      }
    });
  }), hits);
}

function string_of_hits(hits) {
  return Melange__Views.Json.arr(hit_json_list(hits));
}

function horizon_label(f) {
  return Melange__Domain.horizon_to_string(f.inferred_horizon);
}

function parse_errors_json(errs) {
  return Melange__Views.Json.arr(Stdlib__List.map((function (e) {
    return Melange__Views.Json.obj({
      hd: [
        "path",
        Melange__Views.Json.str(e.err_path)
      ],
      tl: {
        hd: [
          "message",
          Melange__Views.Json.str(e.err_message)
        ],
        tl: /* [] */ 0
      }
    });
  }), errs));
}

function health_json(spec_count, overlay_ok, context_age_s, parse_errors) {
  const empty = spec_count === 0;
  return Melange__Views.Json.obj({
    hd: [
      "ok",
      Melange__Views.Json.bool(overlay_ok)
    ],
    tl: {
      hd: [
        "specs",
        Melange__Views.Json.obj({
          hd: [
            "count",
            Melange__Views.Json.$$int(spec_count)
          ],
          tl: {
            hd: [
              "empty",
              Melange__Views.Json.bool(empty)
            ],
            tl: /* [] */ 0
          }
        })
      ],
      tl: {
        hd: [
          "overlay",
          Melange__Views.Json.obj({
            hd: [
              "ok",
              Melange__Views.Json.bool(overlay_ok)
            ],
            tl: /* [] */ 0
          })
        ],
        tl: {
          hd: [
            "context_age_s",
            Melange__Views.Json.opt_int(context_age_s)
          ],
          tl: {
            hd: [
              "parse_errors",
              parse_errors_json(parse_errors)
            ],
            tl: {
              hd: [
                "empty_specs",
                empty ? Melange__Views.Json.bool(true) : null
              ],
              tl: /* [] */ 0
            }
          }
        }
      }
    }
  });
}

const body_dict = Js__Js_json.decodeObject;

function body_string(json, k) {
  const d = Js__Js_json.decodeObject(json);
  if (d === undefined) {
    return;
  }
  const v = Js__Js_dict.get(Caml_option.valFromOption(d), k);
  if (v !== undefined) {
    return Js__Js_json.decodeString(Caml_option.valFromOption(v));
  }
  
}

function body_bool(json, k) {
  const d = Js__Js_json.decodeObject(json);
  if (d === undefined) {
    return;
  }
  const v = Js__Js_dict.get(Caml_option.valFromOption(d), k);
  if (v !== undefined) {
    return Js__Js_json.decodeBoolean(Caml_option.valFromOption(v));
  }
  
}

function catch_null(c, f) {
  return Melange__Hono.json_body(c.req).then(function (body) {
    return Promise.resolve(Curry._1(f, Caml_option.some(body)));
  }).catch(function (param) {
    return Promise.resolve(Curry._1(f, undefined));
  });
}

function ref_has_task(ref_) {
  const i = Stdlib__String.index_opt(ref_, /* '#' */35);
  if (i !== undefined) {
    return (i + 1 | 0) < ref_.length;
  } else {
    return false;
  }
}

const graph_of = Melange__Views.graph_typed;

function create_app(root) {
  const paths = Melange__Paths.paths_for(root);
  Melange__Js_shims.Fs.mkdir_p(paths.dash);
  const db = new Bunsqlite.Database(paths.db);
  Melange__Overlay.apply_migrations(db);
  if (!Nodefs.existsSync(Melange__Js_shims.Path.join2(paths.context, "summary.md"))) {
    Melange__Rebuild.rebuild_all(root);
  }
  const state = {
    contents: {
      st_tree: Melange__Load_tree.load_tree(paths),
      st_db: db
    }
  };
  const reload = function (param) {
    state.contents = {
      st_tree: Melange__Load_tree.load_tree(paths),
      st_db: db
    };
  };
  const app = new Hono.Hono();
  const banners = function (param) {
    const t = state.contents.st_tree;
    let out = /* [] */ 0;
    if (Caml_obj.caml_equal(t.features, /* [] */ 0)) {
      out = {
        hd: "No specs yet. A mid-day design conversation becomes <code>specs/NNN-slug/spec.md</code>.",
        tl: out
      };
    }
    if (Caml_obj.caml_notequal(t.parse_errors, /* [] */ 0)) {
      out = {
        hd: "Parse errors: " + Stdlib__String.concat(", ", Stdlib__List.map((function (e) {
          return Melange__Markdown.esc(e.err_path);
        }), t.parse_errors)),
        tl: out
      };
    }
    if (Melange__Rebuild.context_is_stale(paths, t.spec_mtime_ms)) {
      out = {
        hd: "Generated context is stale. <form class=\"inline\" method=\"post\" action=\"/api/sync\"><button>Rebuild</button></form>",
        tl: out
      };
    }
    if (!t.tree_constitution.present) {
      out = {
        hd: "Constitution missing. Bootstrap writes a stub; replace via /speckit.constitution.",
        tl: out
      };
    }
    return Stdlib__List.rev(out);
  };
  const page_html = function (title, path, body) {
    return Melange__Html.page(title, path, banners(), body);
  };
  const sync_json = function (param) {
    const result = Melange__Rebuild.rebuild_all(root);
    reload();
    return Melange__Views.Json.obj({
      hd: [
        "ok",
        Melange__Views.Json.bool(true)
      ],
      tl: {
        hd: [
          "features",
          Melange__Views.Json.$$int(result.rb_features)
        ],
        tl: {
          hd: [
            "memory_notes",
            Melange__Views.Json.$$int(result.rb_memory_notes)
          ],
          tl: {
            hd: [
              "parse_errors",
              parse_errors_json(result.rb_parse_errors)
            ],
            tl: {
              hd: [
                "generated_at",
                Melange__Views.Json.str(result.rb_generated_at)
              ],
              tl: /* [] */ 0
            }
          }
        }
      }
    });
  };
  const chat_route = function (param) {
    const t = state.contents.st_tree;
    const features = t.features;
    const constitution = t.tree_constitution;
    return function (message) {
      const ls = Melange__Speckit.lines_of(constitution.const_body);
      const take = function (_n, _acc, _param) {
        while (true) {
          const param = _param;
          const acc = _acc;
          const n = _n;
          if (!param) {
            return Stdlib__List.rev(acc);
          }
          if (n <= 0) {
            return Stdlib__List.rev(acc);
          }
          _param = param.tl;
          _acc = {
            hd: param.hd,
            tl: acc
          };
          _n = n - 1 | 0;
          continue;
        };
      };
      const excerpt_lines = take(12, /* [] */ 0, ls);
      const excerpt = Stdlib__String.concat("\n", excerpt_lines);
      const slugs = Stdlib__List.map((function (f) {
        return f.slug;
      }), features);
      const intent = Melange__Envelope.classify(slugs, message);
      let memory_hits;
      memory_hits = /* tag */ typeof intent !== "object" && typeof intent !== "function" || intent.TAG !== /* Memory */ 2 ? /* [] */ 0 : Melange__Overlay.search_memory(undefined, db, intent._0);
      const constitution_info_c_title = constitution.const_title;
      const constitution_info_c_body = constitution.const_body;
      const constitution_info = {
        c_title: constitution_info_c_title,
        c_excerpt: excerpt,
        c_body: constitution_info_c_body
      };
      const catalog = Melange__Views.catalog_of(features, constitution_info, hit_json_list(memory_hits));
      return Melange__Envelope.encode_envelope(Melange__Envelope.envelope_for(intent, catalog));
    };
  };
  app.get("/health", (function (c) {
    const t = state.contents.st_tree;
    return Melange__Hono.json_resp(c, health_json(Stdlib__List.length(t.features), Melange__Overlay.ping(db), Melange__Rebuild.context_age_s(paths), t.parse_errors));
  }));
  app.get("/", (function (c) {
    const t = state.contents.st_tree;
    const features = t.features;
    const blocked = Melange__Context_gen.blocked_tasks(features);
    const metrics = Melange__Context_gen.metrics_of(features);
    const in_flight = Melange__Context_gen.in_flight(features);
    const now_specs = Stdlib__List.filter((function (f) {
      return f.inferred_horizon === /* Now */ 0;
    }), features);
    const summary_path = Melange__Js_shims.Path.join2(paths.context, "summary.md");
    const summary_md = Nodefs.existsSync(summary_path) ? Melange__Js_shims.Fs.read_file_sync(summary_path) : "";
    const pins = Melange__Overlay.list_pins(db);
    const blocked_items_html = Caml_obj.caml_equal(blocked, /* [] */ 0) ? "<p class=\"empty\">Nothing blocked.</p>" : "<ul>" + (Stdlib__String.concat("", Stdlib__List.map((function (item) {
        const sc = item.card;
        let id;
        id = sc.TAG === /* Spec_card */ 0 ? sc._0.slug : sc._0.card_ref;
        return "<li><code>" + (Melange__Markdown.esc(id) + ("</code> \xe2\x80\x94 " + (Melange__Markdown.esc(item.why) + "</li>")));
      }), blocked)) + "</ul>");
    const pins_html = Caml_obj.caml_equal(pins, /* [] */ 0) ? "<p class=\"empty\">No pins.</p>" : "<ul>" + (Stdlib__String.concat("", Stdlib__List.map((function (p) {
        return "<li><code>" + (Melange__Markdown.esc(p.pin_ref) + ("</code> \xe2\x80\x94 " + (Melange__Markdown.esc(p.pin_reason) + "</li>")));
      }), pins)) + "</ul>");
    const s = Melange__Rebuild.context_age_s(paths);
    const body = "<h1>Overview</h1>\n" + (Melange__Html.dl({
      hd: [
        "In flight",
        String(Stdlib__List.length(in_flight))
      ],
      tl: {
        hd: [
          "Open tasks",
          Curry._2(Stdlib__Printf.sprintf({
            TAG: /* Format */ 0,
            _0: {
              TAG: /* Int */ 4,
              _0: /* Int_d */ 0,
              _1: /* No_padding */ 0,
              _2: /* No_precision */ 0,
              _3: {
                TAG: /* Char_literal */ 12,
                _0: /* '/' */47,
                _1: {
                  TAG: /* Int */ 4,
                  _0: /* Int_d */ 0,
                  _1: /* No_padding */ 0,
                  _2: /* No_precision */ 0,
                  _3: /* End_of_format */ 0
                }
              }
            },
            _1: "%d/%d"
          }), metrics.m_open_tasks, metrics.m_total_tasks)
        ],
        tl: {
          hd: [
            "Blocked",
            String(Stdlib__List.length(blocked))
          ],
          tl: {
            hd: [
              "Now horizon",
              String(Stdlib__List.length(now_specs))
            ],
            tl: {
              hd: [
                "Context age",
                s !== undefined ? String(s) + "s" : "never built"
              ],
              tl: {
                hd: [
                  "Pins",
                  String(Stdlib__List.length(pins))
                ],
                tl: /* [] */ 0
              }
            }
          }
        }
      }
    }) + ("\n<h2>In flight</h2>\n" + (Melange__Html.feature_table(Stdlib__List.map(Melange__Domain.spec_card, in_flight), "Nothing in flight.") + ("\n<h2>Now</h2>\n" + (Melange__Html.feature_table(Stdlib__List.map(Melange__Domain.spec_card, now_specs), "No now-horizon specs.") + ("\n<h2>Blocked</h2>\n" + (blocked_items_html + ("\n<h2>Pins</h2>\n" + (pins_html + ("\n<h2>Generated summary</h2>\n" + (
      summary_md === "" ? "<p class=\"empty\"><em>Run</em> <code>bun run index</code> or POST /api/sync.</p>" : Melange__Html.md_article(summary_md)
    )))))))))));
    return Melange__Hono.html_resp(c, page_html("Overview", "/", body));
  }));
  app.get("/roadmap", (function (c) {
    const features = state.contents.st_tree.features;
    const sections = Stdlib__String.concat("", Stdlib__List.map((function (param) {
      const name = param[1];
      const h = param[0];
      const cards = Stdlib__List.map(Melange__Domain.spec_card, Stdlib__List.filter((function (f) {
        return f.inferred_horizon === h;
      }), features));
      return "<h2>" + (name + ("</h2>" + Melange__Html.feature_table(cards, "No specs on " + (name + "."))));
    }), {
      hd: [
        /* Now */ 0,
        "now"
      ],
      tl: {
        hd: [
          /* Next */ 1,
          "next"
        ],
        tl: {
          hd: [
            /* Later */ 2,
            "later"
          ],
          tl: /* [] */ 0
        }
      }
    }));
    return Melange__Hono.html_resp(c, page_html("Roadmap", "/roadmap", "<h1>Roadmap</h1>" + sections));
  }));
  app.get("/backlog", (function (c) {
    const features = state.contents.st_tree.features;
    const items = Stdlib__List.map((function (t) {
      return {
        tr_ref: t.card_ref,
        tr_title: t.card_title,
        tr_done: t.card_done,
        tr_spec: t.card_spec_slug
      };
    }), Melange__Views.backlog_items(features));
    const body = "<h1>Backlog</h1>\n<p>Open tasks across specs, in the order <code>tasks.md</code> states.</p>\n" + Melange__Html.task_table(true, items);
    return Melange__Hono.html_resp(c, page_html("Backlog", "/backlog", body));
  }));
  app.get("/specs", (function (c) {
    const cards = Stdlib__List.map(Melange__Domain.spec_card, state.contents.st_tree.features);
    const body = "<h1>Specs</h1>\n<p>Router: <a href=\"/specs/INDEX.md\"><code>specs/INDEX.md</code></a> (generated).</p>\n" + Melange__Html.feature_table(cards, "No specs yet.");
    return Melange__Hono.html_resp(c, page_html("Specs", "/specs", body));
  }));
  app.get("/specs/INDEX.md", (function (c) {
    if (Nodefs.existsSync(paths.index_md)) {
      return Melange__Hono.markdown_resp(c, Melange__Js_shims.Fs.read_file_sync(paths.index_md));
    } else {
      return Melange__Hono.text_status(c, "INDEX.md not generated", 404);
    }
  }));
  app.get("/specs/:slug", (function (c) {
    const slug = Melange__Hono.param(c, "slug");
    const feature = Melange__Views.find_feature(state.contents.st_tree.features, slug);
    if (feature === undefined) {
      return Melange__Hono.html_status(c, page_html("Missing", "/specs", "<h1>No spec " + (Melange__Markdown.esc(slug) + "</h1>")), 404);
    }
    const detail = Melange__Views.spec_detail_of_feature(feature);
    const tasks = Stdlib__List.map((function (t) {
      return {
        tr_ref: Melange__Domain.make_ref(feature.slug, t.id),
        tr_title: t.title,
        tr_done: t.is_done,
        tr_spec: feature.slug
      };
    }), feature.tasks);
    const p = feature.plan_md;
    const plan_section = p !== undefined ? "\n<h2>plan.md</h2>" + Melange__Html.md_article(p) : "\n<p class=\"empty\">No plan.md \xe2\x80\x94 status is specified.</p>";
    const t = feature.tasks_md;
    const raw_tasks = t !== undefined ? "\n<details><summary>Raw tasks.md</summary>" + (Melange__Html.md_article(t) + "</details>") : "\n<p class=\"empty\">No tasks.md.</p>";
    const p$1 = feature.priority;
    const body = "<h1>" + (Melange__Markdown.esc(feature.slug) + ("</h1>\n" + (Melange__Html.dl({
      hd: [
        "Status",
        Melange__Html.status_pill(Melange__Domain.status_to_string(feature.status))
      ],
      tl: {
        hd: [
          "Horizon",
          Melange__Markdown.esc(Melange__Domain.horizon_to_string(feature.inferred_horizon))
        ],
        tl: {
          hd: [
            "Priority",
            p$1 !== undefined ? Melange__Markdown.esc(Melange__Domain.priority_to_string(p$1)) : "\xe2\x80\x94"
          ],
          tl: {
            hd: [
              "Tasks",
              Curry._2(Stdlib__Printf.sprintf({
                TAG: /* Format */ 0,
                _0: {
                  TAG: /* Int */ 4,
                  _0: /* Int_d */ 0,
                  _1: /* No_padding */ 0,
                  _2: /* No_precision */ 0,
                  _3: {
                    TAG: /* Char_literal */ 12,
                    _0: /* '/' */47,
                    _1: {
                      TAG: /* Int */ 4,
                      _0: /* Int_d */ 0,
                      _1: /* No_padding */ 0,
                      _2: /* No_precision */ 0,
                      _3: {
                        TAG: /* String_literal */ 11,
                        _0: " open",
                        _1: /* End_of_format */ 0
                      }
                    }
                  }
                },
                _1: "%d/%d open"
              }), detail.sd_open, detail.sd_total)
            ],
            tl: {
              hd: [
                "Plan",
                detail.sd_plan_present ? "present" : "none"
              ],
              tl: /* [] */ 0
            }
          }
        }
      }
    }) + ("\n<h2>spec.md</h2>\n" + (Melange__Html.md_article(feature.spec_md) + (plan_section + ("\n<h2>tasks.md</h2>\n" + (Melange__Html.task_table(true, tasks) + raw_tasks))))))));
    return Melange__Hono.html_resp(c, page_html(feature.slug, "/specs", body));
  }));
  app.get("/constitution", (function (c) {
    const con = state.contents.st_tree.tree_constitution;
    const body = con.present ? "<h1>" + (Melange__Markdown.esc(con.const_title) + ("</h1>\n<p class=\"empty\">Read-only. Amend the file, not this page. Not copied into <code>memory/</code>.</p>\n" + Melange__Html.md_article(con.const_body))) : "<h1>Constitution</h1><p>Missing. Bootstrap writes a stub.</p>";
    return Melange__Hono.html_resp(c, page_html("Constitution", "/constitution", body));
  }));
  app.get("/graph", (function (c) {
    const graph = Melange__Views.graph_typed(state.contents.st_tree.features);
    const nodes = Stdlib__List.map((function (n) {
      return "<li><span class=\"pill\">" + (Melange__Markdown.esc(n.node_kind) + ("</span> <code>" + (Melange__Markdown.esc(n.node_id) + ("</code> " + (Melange__Markdown.esc(n.node_title) + (" " + (Melange__Html.status_pill(n.node_status) + "</li>")))))));
    }), graph.nodes);
    const edges = Stdlib__List.map((function (e) {
      return "<li><code>" + (Melange__Markdown.esc(e.g_edge_from) + ("</code> \xe2\x86\x92 <code>" + (Melange__Markdown.esc(e.g_edge_to) + ("</code> <span class=\"muted\">" + (Melange__Markdown.esc(e.g_edge_kind) + "</span></li>")))));
    }), graph.edges);
    const body = "<h1>Graph</h1>\n<p>Edges from <code>tasks.md</code> order, phase boundaries, and <code>[[wiki]]</code> links. No side-car relations table.</p>\n<h2>Nodes</h2><ul class=\"graph\">" + ((
      nodes ? Stdlib__String.concat("", nodes) : "<li>none</li>"
    ) + ("</ul>\n<h2>Edges</h2><ul class=\"graph\">" + ((
      edges ? Stdlib__String.concat("", edges) : "<li>none</li>"
    ) + "</ul>")));
    return Melange__Hono.html_resp(c, page_html("Graph", "/graph", body));
  }));
  app.get("/memory", (function (c) {
    const notes = Melange__Load_tree.load_memory_notes(undefined, paths.memory);
    const items = Caml_obj.caml_equal(notes, /* [] */ 0) ? "<p class=\"empty\">No reviewed notes. Action agents append <code>memory/sessions/</code> only. Curator proposes the rest.</p>" : "<ul>" + (Stdlib__String.concat("", Stdlib__List.map((function (n) {
        const s = n.note_as_of;
        const b = n.note_body;
        return "<li><strong>" + (Melange__Markdown.esc(n.note_title) + ("</strong> <code>" + (Melange__Markdown.esc(n.note_path) + ("</code>\n<span class=\"muted\">" + (Melange__Markdown.esc(Melange__Memory_ml.kind_to_string(n.note_kind)) + (" \xc2\xb7 " + (Melange__Markdown.esc(s !== undefined ? s : "") + ("</span>\n<p>" + (Melange__Markdown.esc(b.length > 200 ? Stdlib__String.sub(b, 0, 200) : b) + "</p></li>")))))))));
      }), notes)) + "</ul>");
    const body = "<h1>Memory</h1>\n<p>Read-only. Constitution is not copied here; point at it.</p>\n" + items;
    return Melange__Hono.html_resp(c, page_html("Memory", "/memory", body));
  }));
  app.get("/static/:file", (function (c) {
    const file = Melange__Hono.param(c, "file");
    if (Melange__Speckit.contains(file, "/") || Melange__Speckit.contains(file, "..")) {
      return Melange__Hono.text_status(c, "not found", 404);
    }
    const p = Melange__Js_shims.Path.join2(Melange__Paths.public_dir(), file);
    if (!Nodefs.existsSync(p)) {
      return Melange__Hono.text_status(c, "not found", 404);
    }
    const mime = file.endsWith(".css") ? "text/css; charset=utf-8" : (
        file.endsWith(".js") ? "text/javascript; charset=utf-8" : (
            file.endsWith(".svg") ? "image/svg+xml" : "application/octet-stream"
          )
      );
    return Melange__Hono.bytes_resp(c, mime, Melange__Js_shims.Fs.read_file_sync(p));
  }));
  app.get("/api/summary", (function (c) {
    const features = state.contents.st_tree.features;
    return Melange__Hono.json_resp(c, Melange__Views.summary_visual_json(features, Melange__Context_gen.blocked_tasks(features)));
  }));
  app.get("/api/roadmap", (function (c) {
    return Melange__Hono.json_resp(c, Melange__Views.roadmap_json(state.contents.st_tree.features));
  }));
  app.get("/api/backlog", (function (c) {
    return Melange__Hono.json_resp(c, Melange__Views.backlog_json(state.contents.st_tree.features));
  }));
  app.get("/api/specs", (function (c) {
    return Melange__Hono.json_resp(c, Melange__Views.Json.arr(Stdlib__List.map((function (f) {
      return Melange__Views.spec_card_json(Melange__Domain.spec_card(f));
    }), state.contents.st_tree.features)));
  }));
  app.get("/api/specs/:slug", (function (c) {
    const f = Melange__Views.find_feature(state.contents.st_tree.features, Melange__Hono.param(c, "slug"));
    if (f !== undefined) {
      return Melange__Hono.json_resp(c, Melange__Views.spec_detail_json(Melange__Views.spec_detail_of_feature(f)));
    } else {
      return Melange__Hono.json_status(c, Melange__Views.Json.obj({
        hd: [
          "error",
          Melange__Views.Json.str("not found")
        ],
        tl: /* [] */ 0
      }), 404);
    }
  }));
  app.get("/api/item/:ref", (function (c) {
    const ref_ = Melange__Hono.param(c, "ref");
    const r = Melange__Domain.parse_ref(ref_);
    const match = r.task_id;
    if (match !== undefined) {
      const match$1 = Melange__Views.find_task(state.contents.st_tree.features, ref_);
      if (match$1 !== undefined) {
        return Melange__Hono.json_resp(c, Melange__Views.Json.obj({
          hd: [
            "kind",
            Melange__Views.Json.str("task")
          ],
          tl: {
            hd: [
              "spec",
              Melange__Views.spec_card_json(Melange__Domain.spec_card(match$1[0]))
            ],
            tl: {
              hd: [
                "task",
                Melange__Views.task_json(match$1[1])
              ],
              tl: /* [] */ 0
            }
          }
        }));
      } else {
        return Melange__Hono.json_status(c, Melange__Views.Json.obj({
          hd: [
            "error",
            Melange__Views.Json.str("not found")
          ],
          tl: /* [] */ 0
        }), 404);
      }
    }
    const slug = r.slug;
    if (slug === undefined) {
      return Melange__Hono.json_status(c, Melange__Views.Json.obj({
        hd: [
          "error",
          Melange__Views.Json.str("not found")
        ],
        tl: /* [] */ 0
      }), 404);
    }
    const f = Melange__Views.find_feature(state.contents.st_tree.features, slug);
    if (f !== undefined) {
      return Melange__Hono.json_resp(c, Melange__Views.Json.obj({
        hd: [
          "kind",
          Melange__Views.Json.str("spec")
        ],
        tl: {
          hd: [
            "spec",
            Melange__Views.spec_detail_json(Melange__Views.spec_detail_of_feature(f))
          ],
          tl: /* [] */ 0
        }
      }));
    } else {
      return Melange__Hono.json_status(c, Melange__Views.Json.obj({
        hd: [
          "error",
          Melange__Views.Json.str("not found")
        ],
        tl: /* [] */ 0
      }), 404);
    }
  }));
  app.get("/api/search", (function (c) {
    const q = Stdlib__String.lowercase_ascii(Melange__Hono.query_default(c, "q", ""));
    const hits = Stdlib__List.concat_map((function (f) {
      const spec_hits = Melange__Speckit.contains(f.slug, q) || Melange__Speckit.contains(Stdlib__String.lowercase_ascii(f.title), q) ? ({
          hd: Melange__Views.Json.obj({
            hd: [
              "kind",
              Melange__Views.Json.str("spec")
            ],
            tl: {
              hd: [
                "ref",
                Melange__Views.Json.str(f.slug)
              ],
              tl: {
                hd: [
                  "title",
                  Melange__Views.Json.str(f.title)
                ],
                tl: /* [] */ 0
              }
            }
          }),
          tl: /* [] */ 0
        }) : /* [] */ 0;
      const task_hits = Stdlib__List.filter_map((function (t) {
        if (Melange__Speckit.contains(Stdlib__String.lowercase_ascii(t.id), q) || Melange__Speckit.contains(Stdlib__String.lowercase_ascii(t.title), q)) {
          return Caml_option.some(Melange__Views.Json.obj({
            hd: [
              "kind",
              Melange__Views.Json.str("task")
            ],
            tl: {
              hd: [
                "ref",
                Melange__Views.Json.str(Melange__Domain.make_ref(f.slug, t.id))
              ],
              tl: {
                hd: [
                  "title",
                  Melange__Views.Json.str(t.title)
                ],
                tl: /* [] */ 0
              }
            }
          }));
        }
        
      }), f.tasks);
      return Stdlib.$at(spec_hits, task_hits);
    }), state.contents.st_tree.features);
    return Melange__Hono.json_resp(c, Melange__Views.Json.obj({
      hd: [
        "hits",
        Melange__Views.Json.arr(hits)
      ],
      tl: /* [] */ 0
    }));
  }));
  app.get("/api/memory", (function (c) {
    const q = Melange__Hono.query_default(c, "q", "");
    const hits = Melange__Overlay.search_memory(undefined, db, q);
    return Melange__Hono.json_resp(c, Melange__Views.Json.obj({
      hd: [
        "hits",
        Melange__Views.Json.arr(hit_json_list(hits))
      ],
      tl: /* [] */ 0
    }));
  }));
  app.get("/api/pins", (function (c) {
    return Melange__Hono.json_resp(c, Melange__Views.Json.obj({
      hd: [
        "pins",
        Melange__Views.Json.arr(Stdlib__List.map((function (p) {
          return Melange__Views.Json.obj({
            hd: [
              "ref",
              Melange__Views.Json.str(p.pin_ref)
            ],
            tl: {
              hd: [
                "reason",
                Melange__Views.Json.str(p.pin_reason)
              ],
              tl: {
                hd: [
                  "pinned_at",
                  Melange__Views.Json.str(p.pin_pinned_at)
                ],
                tl: /* [] */ 0
              }
            }
          });
        }), Melange__Overlay.list_pins(db)))
      ],
      tl: /* [] */ 0
    }));
  }));
  app.get("/api/metrics", (function (c) {
    return Melange__Hono.json_resp(c, Melange__Views.metrics_json(state.contents.st_tree.features));
  }));
  app.post("/api/sync", (function (c) {
    return Promise.resolve(Melange__Hono.json_resp(c, sync_json()));
  }));
  app.post("/api/index", (function (c) {
    return Promise.resolve(Melange__Hono.json_resp(c, sync_json()));
  }));
  app.post("/api/task", (function (c) {
    return catch_null(c, (function (body) {
      if (body === undefined) {
        return Melange__Hono.json_status(c, Melange__Views.Json.obj({
          hd: [
            "error",
            Melange__Views.Json.str("ref required")
          ],
          tl: /* [] */ 0
        }), 400);
      }
      const body$1 = Caml_option.valFromOption(body);
      const ref_ = body_string(body$1, "ref");
      if (ref_ === undefined) {
        return Melange__Hono.json_status(c, Melange__Views.Json.obj({
          hd: [
            "error",
            Melange__Views.Json.str("ref required")
          ],
          tl: /* [] */ 0
        }), 400);
      }
      const b = body_bool(body$1, "done");
      const done_ = b !== undefined ? b : true;
      const r = Melange__Domain.parse_ref(ref_);
      const match = r.slug;
      const match$1 = r.task_id;
      if (match !== undefined && match$1 !== undefined) {
        const tasks_path = Melange__Js_shims.Path.join3(paths.specs, match, "tasks.md");
        if (!Nodefs.existsSync(tasks_path)) {
          return Melange__Hono.json_status(c, Melange__Views.Json.obj({
            hd: [
              "error",
              Melange__Views.Json.str("tasks.md missing")
            ],
            tl: /* [] */ 0
          }), 404);
        }
        const current = Melange__Js_shims.Fs.read_file_sync(tasks_path);
        const e = Melange__Speckit.set_task_checkbox(current, match$1, done_);
        if (e.TAG !== /* Ok */ 0) {
          return Melange__Hono.json_status(c, Melange__Views.Json.obj({
            hd: [
              "error",
              Melange__Views.Json.str(e._0)
            ],
            tl: /* [] */ 0
          }), 404);
        }
        Melange__Js_shims.Fs.write_file_sync(tasks_path, e._0);
        Melange__Rebuild.rebuild_all(root);
        reload();
        const features = state.contents.st_tree.features;
        return Melange__Hono.json_resp(c, Melange__Views.Json.obj({
          hd: [
            "ok",
            Melange__Views.Json.bool(true)
          ],
          tl: {
            hd: [
              "changed",
              Melange__Views.Json.bool(true)
            ],
            tl: {
              hd: [
                "ref",
                Melange__Views.Json.str(ref_)
              ],
              tl: {
                hd: [
                  "done",
                  Melange__Views.Json.bool(done_)
                ],
                tl: {
                  hd: [
                    "backlog",
                    Melange__Views.backlog_json(features)
                  ],
                  tl: /* [] */ 0
                }
              }
            }
          }
        }));
      }
      return Melange__Hono.json_status(c, Melange__Views.Json.obj({
        hd: [
          "error",
          Melange__Views.Json.str("ref must be slug#T0xx")
        ],
        tl: /* [] */ 0
      }), 400);
    }));
  }));
  app.post("/api/pins", (function (c) {
    return catch_null(c, (function (body) {
      if (body === undefined) {
        return Melange__Hono.json_status(c, Melange__Views.Json.obj({
          hd: [
            "error",
            Melange__Views.Json.str("ref and reason required")
          ],
          tl: /* [] */ 0
        }), 400);
      }
      const body$1 = Caml_option.valFromOption(body);
      const match = body_string(body$1, "ref");
      const match$1 = body_string(body$1, "reason");
      if (match !== undefined && match$1 !== undefined) {
        const pin = Melange__Overlay.upsert_pin(db, match, match$1);
        return Melange__Hono.json_resp(c, Melange__Views.Json.obj({
          hd: [
            "ok",
            Melange__Views.Json.bool(true)
          ],
          tl: {
            hd: [
              "pin",
              Melange__Views.Json.obj({
                hd: [
                  "ref",
                  Melange__Views.Json.str(pin.pin_ref)
                ],
                tl: {
                  hd: [
                    "reason",
                    Melange__Views.Json.str(pin.pin_reason)
                  ],
                  tl: {
                    hd: [
                      "pinned_at",
                      Melange__Views.Json.str(pin.pin_pinned_at)
                    ],
                    tl: /* [] */ 0
                  }
                }
              })
            ],
            tl: /* [] */ 0
          }
        }));
      }
      return Melange__Hono.json_status(c, Melange__Views.Json.obj({
        hd: [
          "error",
          Melange__Views.Json.str("ref and reason required")
        ],
        tl: /* [] */ 0
      }), 400);
    }));
  }));
  app.post("/api/chat", (function (c) {
    return catch_null(c, (function (body) {
      if (body === undefined) {
        return Melange__Hono.json_status(c, Melange__Views.Json.obj({
          hd: [
            "error",
            Melange__Views.Json.str("message required")
          ],
          tl: /* [] */ 0
        }), 400);
      }
      const body$1 = Caml_option.valFromOption(body);
      const message = body_string(body$1, "message");
      if (message === undefined) {
        return Melange__Hono.json_status(c, Melange__Views.Json.obj({
          hd: [
            "error",
            Melange__Views.Json.str("message required")
          ],
          tl: /* [] */ 0
        }), 400);
      }
      const envelope = chat_route()(message);
      const t = body_string(body$1, "thread_id");
      const thread_id = t !== undefined ? t : crypto.randomUUID();
      Melange__Overlay.insert_thread(db, thread_id, message.length > 80 ? Stdlib__String.sub(message, 0, 80) : message);
      const d = Js__Js_json.decodeObject(body$1);
      let tmp;
      if (d !== undefined) {
        const ctx = Js__Js_dict.get(Caml_option.valFromOption(d), "context");
        tmp = ctx !== undefined ? Caml_option.valFromOption(ctx) : null;
      } else {
        tmp = null;
      }
      Melange__Overlay.insert_message(db, thread_id, "user", JSON.stringify(Melange__Views.Json.obj({
        hd: [
          "message",
          Melange__Views.Json.str(message)
        ],
        tl: {
          hd: [
            "context",
            tmp
          ],
          tl: /* [] */ 0
        }
      })));
      Melange__Overlay.insert_message(db, thread_id, "assistant", JSON.stringify(envelope));
      const d$1 = Js__Js_json.decodeObject(envelope);
      const d$2 = d$1 !== undefined ? Caml_option.valFromOption(d$1) : ({});
      d$2["thread_id"] = Melange__Views.Json.str(thread_id);
      return Melange__Hono.json_resp(c, d$2);
    }));
  }));
  return app;
}

export {
  hit_json_list,
  string_of_hits,
  horizon_label,
  parse_errors_json,
  health_json,
  body_dict,
  body_string,
  body_bool,
  catch_null,
  ref_has_task,
  graph_of,
  create_app,
}
/* Melange__Envelope Not a pure module */
