// Generated by Melange

import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Caml_option from "melange.js/caml_option.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Overlay from "./overlay.js";
import * as Melange__Paths from "./paths.js";
import * as Melange__Rebuild from "./rebuild.js";
import * as Stdlib__Printexc from "melange/printexc.js";
import * as Stdlib__String from "melange/string.js";
import * as Bunsqlite from "bun:sqlite";
import * as Nodechild_process from "node:child_process";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";

process.cwd();

process.chdir(Melange__Paths.tool_root());

try {
  Nodechild_process.execSync("bun install");
}
catch (raw_e){
  const e = Caml_js_exceptions.internalToOCamlException(raw_e);
  Melange__Js_shims.Console.error("bun install failed: " + Stdlib__Printexc.to_string(e));
  process.exit(1);
}

const root = Melange__Paths.resolve_project_root();

const paths = Melange__Paths.paths_for(root);

Melange__Js_shims.Fs.mkdir_p(paths.dash);

try {
  const db = new Bunsqlite.Database(paths.db);
  Melange__Overlay.apply_migrations(db);
  Caml_option.some(db);
}
catch (raw_e$1){
  const e$1 = Caml_js_exceptions.internalToOCamlException(raw_e$1);
  Melange__Js_shims.Console.error("sqlite migration failed: " + Stdlib__Printexc.to_string(e$1));
  process.exit(1);
}

if (!Nodefs.existsSync(paths.specs)) {
  Melange__Js_shims.Fs.mkdir_p(paths.specs);
}

Melange__Js_shims.Fs.mkdir_p(Nodepath.dirname(paths.constitution));

if (!Nodefs.existsSync(paths.constitution)) {
  Melange__Js_shims.Fs.write_file_sync(paths.constitution, Melange__Paths.constitution_stub());
}

if (!Nodefs.existsSync(paths.memory)) {
  Melange__Js_shims.Fs.mkdir_p(paths.memory);
}

const indexed = Melange__Rebuild.rebuild_all(root);

const boot = Stdlib__String.concat("\n", {
  hd: "# Bootstrap",
  tl: {
    hd: "",
    tl: {
      hd: "project_root: " + root,
      tl: {
        hd: "specs: " + String(indexed.rb_features),
        tl: {
          hd: "constitution: " + (
            Nodefs.existsSync(paths.constitution) ? "present" : "missing"
          ),
          tl: {
            hd: "overlay: ok",
            tl: {
              hd: "memory_notes: " + String(indexed.rb_memory_notes),
              tl: {
                hd: "generated_js: committed _generated/ (Melange optional)",
                tl: {
                  hd: "generated_at: " + indexed.rb_generated_at,
                  tl: {
                    hd: "",
                    tl: {
                      hd: "No interactive prompts. Files are the writings.",
                      tl: {
                        hd: "",
                        tl: /* [] */ 0
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
});

Melange__Js_shims.Fs.write_file_sync(paths.bootstrap_md, boot);

Melange__Js_shims.Console.log("bootstrapped " + root);

process.exit(0);
/*  Not a pure module */
