// Generated by Melange

import * as Caml from "melange.js/caml.js";
import * as Caml_array from "melange.js/caml_array.js";
import * as Caml_obj from "melange.js/caml_obj.js";
import * as Caml_option from "melange.js/caml_option.js";
import * as Js__Js_dict from "melange.js/js_dict.js";
import * as Js__Js_json from "melange.js/js_json.js";
import * as Melange__App from "./app.js";
import * as Melange__Context_gen from "./context_gen.js";
import * as Melange__Domain from "./domain.js";
import * as Melange__Envelope from "./envelope.js";
import * as Melange__Hono from "./hono.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Memory_ml from "./memory_ml.js";
import * as Melange__Paths from "./paths.js";
import * as Melange__Rebuild from "./rebuild.js";
import * as Melange__Speckit from "./speckit.js";
import * as Melange__Views from "./views.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Option from "melange/option.js";
import * as Stdlib__String from "melange/string.js";
import * as Nodeos from "node:os";

const failures = {
  contents: /* [] */ 0
};

function assert_(cond, msg) {
  if (!cond) {
    failures.contents = Stdlib.$at(failures.contents, {
      hd: msg,
      tl: /* [] */ 0
    });
    return;
  }
  
}

function eq_string(a, b, msg) {
  if (a !== b) {
    failures.contents = Stdlib.$at(failures.contents, {
      hd: msg + (": " + (a + (" !== " + b))),
      tl: /* [] */ 0
    });
    return;
  }
  
}

function field(json, k) {
  const d = Js__Js_json.decodeObject(json);
  if (d !== undefined) {
    return Js__Js_dict.get(Caml_option.valFromOption(d), k);
  }
  
}

function str_field(json, k) {
  const v = field(json, k);
  if (v !== undefined) {
    return Js__Js_json.decodeString(Caml_option.valFromOption(v));
  }
  
}

function get_json(json, k) {
  const v = field(json, k);
  if (v !== undefined) {
    return Caml_option.valFromOption(v);
  } else {
    return null;
  }
}

function get_str(json, k) {
  const s = str_field(json, k);
  if (s !== undefined) {
    return s;
  } else {
    return "";
  }
}

function get_bool(json, k) {
  const v = field(json, k);
  if (v !== undefined) {
    return Stdlib__Option.value(Js__Js_json.decodeBoolean(Caml_option.valFromOption(v)), false);
  } else {
    return false;
  }
}

function first_visual_kind(env) {
  const v = field(env, "visuals");
  if (v === undefined) {
    return;
  }
  const vs = Js__Js_json.decodeArray(Caml_option.valFromOption(v));
  if (vs !== undefined && vs.length !== 0) {
    return str_field(Caml_array.get(vs, 0), "kind");
  }
  
}

function json_array_to_list(a, _acc, _i) {
  while (true) {
    const i = _i;
    const acc = _acc;
    if (i >= a.length) {
      return Stdlib__List.rev(acc);
    }
    _i = i + 1 | 0;
    _acc = {
      hd: Caml_array.get(a, i),
      tl: acc
    };
    continue;
  };
}

function json_list(json) {
  const a = Js__Js_json.decodeArray(json);
  if (a !== undefined) {
    return json_array_to_list(a, /* [] */ 0, 0);
  } else {
    return /* [] */ 0;
  }
}

function sync_checks(param) {
  const fixtures = Melange__Paths.fixtures_dir();
  const constitution_text = Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join2(fixtures, "constitution.md"));
  const spec_text = Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join4(fixtures, "specs", "000-check-fixture", "spec.md"));
  const tasks_text = Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join4(fixtures, "specs", "000-check-fixture", "tasks.md"));
  const plan_text = Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join4(fixtures, "specs", "000-check-fixture", "plan.md"));
  const constitution = Melange__Speckit.parse_constitution(constitution_text);
  assert_(constitution.title !== "", "constitution has a title");
  assert_(!Melange__Speckit.contains(constitution.body, "memory/decisions"), "constitution is not a memory dump");
  const feature = Melange__Speckit.assemble_feature({
    fi_slug: "000-check-fixture",
    fi_spec_md: spec_text,
    fi_plan_md: plan_text,
    fi_tasks_md: tasks_text,
    fi_siblings: /* [] */ 0,
    fi_gate_failing: false
  });
  eq_string(Melange__Domain.status_to_string(feature.status), "in-progress", "fixture feature is in-progress");
  const h = feature.horizon;
  eq_string(h !== undefined ? Melange__Domain.horizon_to_string(h) : "null", "now", "fixture horizon from frontmatter");
  assert_(Stdlib__List.length(feature.tasks) >= 3, "parsed tasks");
  assert_(Stdlib__List.length(feature.tasks) > 0 && Stdlib__List.nth(feature.tasks, 0).is_done, "T001 checked");
  assert_(Stdlib__List.exists((function (t) {
    if (t.id === "T003") {
      return t.parallel;
    } else {
      return false;
    }
  }), feature.tasks), "[P] task");
  const specified = Melange__Speckit.assemble_feature({
    fi_slug: "002-x",
    fi_spec_md: "# X\n\nwhy\n",
    fi_plan_md: undefined,
    fi_tasks_md: undefined,
    fi_siblings: /* [] */ 0,
    fi_gate_failing: false
  });
  eq_string(Melange__Domain.status_to_string(specified.status), "specified", "no plan \xe2\x86\x92 specified");
  eq_string(Melange__Domain.horizon_to_string(specified.inferred_horizon), "next", "specified infers next");
  const done_now = Melange__Speckit.assemble_feature({
    fi_slug: "009-done",
    fi_spec_md: "---\nhorizon: now\n---\n\n# Done\n",
    fi_plan_md: "# Plan\n\n## Constitution Check\n\n- [x] ok\n",
    fi_tasks_md: "- [x] T001 finished\n",
    fi_siblings: /* [] */ 0,
    fi_gate_failing: false
  });
  eq_string(Melange__Domain.status_to_string(done_now.status), "done", "all tasks \xe2\x86\x92 done");
  eq_string(Melange__Domain.horizon_to_string(done_now.inferred_horizon), "later", "Done + horizon: now \xe2\x86\x92 Later");
  const specified_summary = Melange__Context_gen.build_summary({
    hd: specified,
    tl: /* [] */ 0
  }, /* [] */ 0, "now");
  assert_(Melange__Speckit.contains(specified_summary, "## Needs a plan"), "summary has a Needs a plan section");
  assert_(Melange__Speckit.contains(specified_summary, "002-x"), "summary names the unplanned feature");
  assert_(!Melange__Speckit.contains(specified_summary, "## Ready queue\n- none\n"), "empty ready queue falls through to Needs a plan");
  const planned_summary = Melange__Context_gen.build_summary({
    hd: feature,
    tl: /* [] */ 0
  }, /* [] */ 0, "now");
  assert_(Melange__Speckit.contains(planned_summary, "## Needs a plan\n- none"), "nothing unplanned says none");
  assert_(true, "OCaml literals are byte strings");
  const parsed = Melange__Speckit.parse_tasks_markdown(tasks_text, "000-check-fixture");
  assert_(Caml_obj.caml_notequal(parsed.edges, /* [] */ 0), "task order produces edges");
  const flipped = Melange__Speckit.set_task_checkbox(tasks_text, "T002", true);
  if (flipped.TAG === /* Ok */ 0) {
    const md = flipped._0;
    assert_(Melange__Speckit.contains(md, "- [x] T002"), "T002 now checked");
    assert_(Melange__Speckit.contains(md, "- [ ] T003"), "T003 untouched");
  } else {
    failures.contents = Stdlib.$at(failures.contents, {
      hd: "checkbox edit ok: " + flipped._0,
      tl: /* [] */ 0
    });
  }
  let back;
  back = flipped.TAG === /* Ok */ 0 ? Melange__Speckit.set_task_checkbox(flipped._0, "T002", false) : flipped;
  if (back.TAG === /* Ok */ 0) {
    assert_(Melange__Speckit.contains(back._0, "- [ ] T002"), "checkbox restore");
  } else {
    failures.contents = Stdlib.$at(failures.contents, {
      hd: "checkbox restore: " + back._0,
      tl: /* [] */ 0
    });
  }
  const kind_of = function (m) {
    const match = Melange__Envelope.classify({
      hd: "000-check-fixture",
      tl: /* [] */ 0
    }, m);
    if (/* tag */ typeof match !== "object" && typeof match !== "function") {
      switch (match) {
        case /* Summary */ 0 :
          return "summary";
        case /* Roadmap */ 1 :
          return "roadmap";
        case /* Backlog */ 2 :
          return "backlog";
        case /* Blocked */ 3 :
          return "blocked";
        case /* Constitution */ 4 :
          return "constitution";
        case /* Graph */ 5 :
          return "graph";
      }
    } else {
      switch (match.TAG) {
        case /* Spec */ 0 :
          return "spec";
        case /* Task_ref */ 1 :
          return "task";
        case /* Memory */ 2 :
          return "memory";
      }
    }
  };
  eq_string(kind_of("what should we work on?"), "summary", "morning \xe2\x86\x92 summary");
  eq_string(kind_of("what's blocked"), "blocked", "blocked");
  eq_string(kind_of("show the roadmap"), "roadmap", "roadmap");
  eq_string(kind_of("backlog please"), "backlog", "backlog");
  eq_string(kind_of("constitution"), "constitution", "constitution");
  eq_string(kind_of("000-check-fixture"), "spec", "slug \xe2\x86\x92 spec");
  eq_string(kind_of("look at T012 in 000-check-fixture"), "task", "task ref");
  eq_string(kind_of("why did we decide that"), "memory", "memory");
  const catalog = Melange__Views.catalog_of({
    hd: feature,
    tl: /* [] */ 0
  }, {
    c_title: constitution.title,
    c_excerpt: Stdlib__String.sub(constitution.body, 0, Caml.caml_int_min(200, constitution.body.length)),
    c_body: constitution.body
  }, /* [] */ 0);
  const envelope_json = function (m) {
    return Melange__Envelope.encode_envelope(Melange__Envelope.envelope_for(Melange__Envelope.classify({
      hd: "000-check-fixture",
      tl: /* [] */ 0
    }, m), catalog));
  };
  const morning = envelope_json("what should we work on?");
  const k = first_visual_kind(morning);
  if (k !== undefined) {
    eq_string(k, "summary", "named surface summary");
  } else {
    failures.contents = Stdlib.$at(failures.contents, {
      hd: "named surface summary: no visuals",
      tl: /* [] */ 0
    });
  }
  const blocked_env = envelope_json("what's blocked");
  const k$1 = first_visual_kind(blocked_env);
  if (k$1 !== undefined) {
    eq_string(k$1, "blocked", "named surface blocked");
  } else {
    failures.contents = Stdlib.$at(failures.contents, {
      hd: "named surface blocked: no visuals",
      tl: /* [] */ 0
    });
  }
  const round = Melange__Envelope.decode_envelope(morning);
  if (round.TAG === /* Decode_ok */ 0) {
    const match = round._0.e_visuals;
    if (match) {
      eq_string(match.hd.v_kind, "summary", "roundtrip kind");
    } else {
      failures.contents = Stdlib.$at(failures.contents, {
        hd: "roundtrip kind: no visuals",
        tl: /* [] */ 0
      });
    }
  } else {
    failures.contents = Stdlib.$at(failures.contents, {
      hd: "envelope roundtrip ok: " + round._0,
      tl: /* [] */ 0
    });
  }
  assert_(Melange__Memory_ml.is_reviewed(Melange__Memory_ml.parse_memory_note("memory/conventions/ok.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: active\n---\n\n# Title\n\nbody\n")), "active convention is reviewed");
  assert_(!Melange__Memory_ml.is_reviewed(Melange__Memory_ml.parse_memory_note("memory/conventions/ok.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\n---\n\n# Title\n\nbody\n")), "missing status is not reviewed");
  assert_(!Melange__Memory_ml.is_reviewed(Melange__Memory_ml.parse_memory_note("memory/decisions/p.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: proposal\n---\n\n# Title\n\nbody\n")), "proposal is not reviewed");
  assert_(!Melange__Memory_ml.is_reviewed(Melange__Memory_ml.parse_memory_note("memory/regressions/r.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: rejected\n---\n\n# Title\n\nbody\n")), "rejected is not reviewed");
  assert_(!Melange__Memory_ml.is_reviewed(Melange__Memory_ml.parse_memory_note("memory/conventions/s.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: superseded\n---\n\n# Title\n\nbody\n")), "superseded is not reviewed");
  assert_(!Melange__Memory_ml.is_reviewed(Melange__Memory_ml.parse_memory_note("memory/sessions/x.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: proposal\n---\n\n# Title\n\nbody\n")), "session is not reviewed");
  assert_(!Melange__Memory_ml.is_reviewed(Melange__Memory_ml.parse_memory_note("memory/orphan.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: active\n---\n\n# Title\n\nbody\n")), "outside trees is not reviewed");
  assert_(Melange__Memory_ml.parse_memory_note("memory/conventions/x.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\n---\n\n# Title\n\nbody\n").status === undefined, "missing status is None");
  assert_(Melange__Memory_ml.parse_memory_note("memory/conventions/x.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: potato\n---\n\n# Title\n\nbody\n").status === undefined, "unknown status is None");
  eq_string(Melange__Memory_ml.status_label(undefined), "unknown", "status_label none");
}

function write_note(root, tree, name, body) {
  const dir = Melange__Js_shims.Path.join3(root, "memory", tree);
  Melange__Js_shims.Fs.mkdir_p(dir);
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join2(dir, name), body);
}

function make_tmp_project(param) {
  const tmp = Melange__Js_shims.Path.join2(Nodeos.tmpdir(), "dash-check-" + crypto.randomUUID());
  Melange__Js_shims.Fs.mkdir_p(Melange__Js_shims.Path.join3(tmp, ".specify", "memory"));
  Melange__Js_shims.Fs.mkdir_p(Melange__Js_shims.Path.join3(tmp, "specs", "000-check-fixture"));
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join4(tmp, ".specify", "memory", "constitution.md"), Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join2(Melange__Paths.fixtures_dir(), "constitution.md")));
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join4(tmp, "specs", "000-check-fixture", "spec.md"), Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join4(Melange__Paths.fixtures_dir(), "specs", "000-check-fixture", "spec.md")));
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join4(tmp, "specs", "000-check-fixture", "plan.md"), Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join4(Melange__Paths.fixtures_dir(), "specs", "000-check-fixture", "plan.md")));
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join4(tmp, "specs", "000-check-fixture", "tasks.md"), Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join4(Melange__Paths.fixtures_dir(), "specs", "000-check-fixture", "tasks.md")));
  write_note(tmp, "conventions", "testing.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: active\n---\n\n# Testing the overlay\n\nFTS should find this convention. Point at the constitution; do not copy it.\n");
  write_note(tmp, "sessions", "proposal.md", "---\nas_of: 2026-08-28\nsource: session/check\nconfidence: low\nstatus: proposal\n---\n\n# Session proposal\n\nSESSIONONLYTOKEN must not be a fact.\n");
  write_note(tmp, "decisions", "pending.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: medium\nstatus: proposal\n---\n\n# Pending decision\n\nPROPOSALONLYTOKEN must not be a fact.\n");
  write_note(tmp, "regressions", "dead.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: rejected\n---\n\n# Rejected regression\n\nREJECTEDONLYTOKEN must not be a fact.\n");
  write_note(tmp, "conventions", "old.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\nstatus: superseded\n---\n\n# Old convention\n\nSUPERSEDEDONLYTOKEN must not be a fact.\n");
  write_note(tmp, "conventions", "bare.md", "---\nas_of: 2026-08-28\nsource: human\nconfidence: high\n---\n\n# Bare convention\n\nNOSTATUSTOKEN must not be a fact.\n");
  Melange__Rebuild.rebuild_all(tmp);
  return tmp;
}

function finish(param) {
  if (Caml_obj.caml_notequal(failures.contents, /* [] */ 0)) {
    Melange__Js_shims.Console.error("check failed:");
    Stdlib__List.iter((function (f) {
      Melange__Js_shims.Console.error(" - " + f);
    }), Stdlib__List.rev(failures.contents));
    process.exit(1);
  }
  Melange__Js_shims.Console.log("check ok");
  return process.exit(0);
}

sync_checks();

const tmp = make_tmp_project();

const app = Melange__App.create_app(tmp);

Melange__Hono.request_get_p(app, "/health").then(function (prim) {
  return prim.json();
}).then(function (health) {
  assert_(get_bool(health, "ok"), "health ok");
  const specs = field(health, "specs");
  let count;
  if (specs !== undefined) {
    const v = field(Caml_option.valFromOption(specs), "count");
    count = v !== undefined ? Stdlib__Option.value(Js__Js_json.decodeNumber(Caml_option.valFromOption(v)), 0.0) | 0 : 0;
  } else {
    count = 0;
  }
  assert_(count >= 1, "health specs count");
  const specs$1 = field(health, "specs");
  const empty = specs$1 !== undefined ? get_bool(Caml_option.valFromOption(specs$1), "empty") : true;
  assert_(!empty, "not empty-specs");
  return Melange__Hono.request_get_p(app, "/").then(function (prim) {
    return prim.text();
  });
}).then(function (home) {
  assert_(Melange__Speckit.contains(home, "000-check-fixture"), "overview lists fixture spec");
  assert_(Melange__Speckit.contains(home, "What should we work on?"), "overview shows generated summary");
  return Melange__Hono.request_get_p(app, "/specs/INDEX.md").then(Melange__Hono.res_bytes);
}).then(function (index_wire) {
  assert_(!Melange__Speckit.contains(index_wire, "\xc3\xa2\xc2\x80"), "no double-encoded UTF-8 on the wire");
  assert_(Melange__Speckit.contains(index_wire, "Router only \xe2\x80\x94 load one spec folder"), "em dash reaches the wire as UTF-8");
  return Melange__Hono.request_get_p(app, "/specs").then(function (prim) {
    return prim.text();
  });
}).then(function (specs_page) {
  assert_(Melange__Speckit.contains(specs_page, "000-check-fixture"), "GET /specs lists directories");
  return Melange__Hono.request_get_p(app, "/specs/000-check-fixture").then(function (prim) {
    return prim.text();
  });
}).then(function (detail) {
  assert_(Melange__Speckit.contains(detail, "spec.md") || Melange__Speckit.contains(detail, "Example"), "spec body");
  assert_(Melange__Speckit.contains(detail, "T001"), "tasks render");
  return Melange__Hono.request_post_p(app, "/api/chat", "{\"message\":\"what should we work on?\"}").then(function (prim) {
    return prim.json();
  });
}).then(function (chat_summary) {
  const k = first_visual_kind(chat_summary);
  eq_string(k !== undefined ? k : "", "summary", "POST chat morning");
  return Melange__Hono.request_post_p(app, "/api/chat", "{\"message\":\"what's blocked\"}").then(function (prim) {
    return prim.json();
  });
}).then(function (chat_blocked) {
  const k = first_visual_kind(chat_blocked);
  eq_string(k !== undefined ? k : "", "blocked", "POST chat blocked");
  return Melange__Hono.request_get_p(app, "/api/backlog").then(function (prim) {
    return prim.json();
  });
}).then(function (before) {
  const has_t002 = Stdlib__List.exists((function (item) {
    return get_str(item, "ref") === "000-check-fixture#T002";
  }), json_list(get_json(before, "items")));
  assert_(has_t002, "T002 starts open");
  return Melange__Hono.request_post_p(app, "/api/task", "{\"ref\":\"000-check-fixture#T002\",\"done\":true}").then(function (prim) {
    return prim.json();
  });
}).then(function (toggled) {
  assert_(get_bool(toggled, "ok"), "task toggle ok");
  return Melange__Hono.request_get_p(app, "/api/backlog").then(function (prim) {
    return prim.json();
  });
}).then(function (after) {
  const still_t002 = Stdlib__List.exists((function (item) {
    return get_str(item, "ref") === "000-check-fixture#T002";
  }), json_list(get_json(after, "items")));
  assert_(!still_t002, "T002 left the backlog after toggle + sync");
  const tasks_after = Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join4(tmp, "specs", "000-check-fixture", "tasks.md"));
  assert_(Melange__Speckit.contains(tasks_after, "- [x] T002"), "checkbox written to tasks.md");
  const index_md = Melange__Js_shims.Fs.read_file_bytes(Melange__Js_shims.Path.join3(tmp, "specs", "INDEX.md"));
  assert_(!Melange__Speckit.contains(index_md, "\xc3\xa2\xc2\x80"), "no double-encoded UTF-8 on disk in INDEX.md");
  assert_(Melange__Speckit.contains(index_md, "Router only \xe2\x80\x94 load one spec folder"), "INDEX.md em dash survives the write");
  return Melange__Hono.request_post_p(app, "/api/chat", "{\"message\":\"any decision or convention?\"}").then(function (prim) {
    return prim.json();
  });
}).then(function (mem) {
  const k = first_visual_kind(mem);
  eq_string(k !== undefined ? k : "", "memory", "memory visual");
  return Melange__Hono.request_get_p(app, "/memory").then(function (prim) {
    return prim.text();
  });
}).then(function (memory_page) {
  assert_(Melange__Speckit.contains(memory_page, "Testing the overlay"), "reviewed convention on /memory");
  assert_(Melange__Speckit.contains(memory_page, "active"), "/memory shows status");
  assert_(!Melange__Speckit.contains(memory_page, "SESSIONONLYTOKEN"), "session token absent from /memory");
  assert_(!Melange__Speckit.contains(memory_page, "PROPOSALONLYTOKEN"), "proposal token absent from /memory");
  assert_(!Melange__Speckit.contains(memory_page, "REJECTEDONLYTOKEN"), "rejected token absent from /memory");
  assert_(!Melange__Speckit.contains(memory_page, "SUPERSEDEDONLYTOKEN"), "superseded token absent from /memory");
  assert_(!Melange__Speckit.contains(memory_page, "NOSTATUSTOKEN"), "missing-status token absent from /memory");
  return Melange__Hono.request_get_p(app, "/api/memory?q=overlay").then(function (prim) {
    return prim.json();
  });
}).then(function (overlay_hits) {
  const hits = json_list(get_json(overlay_hits, "hits"));
  assert_(Caml_obj.caml_notequal(hits, /* [] */ 0), "FTS finds the active convention");
  return Melange__Hono.request_get_p(app, "/api/memory?q=SESSIONONLYTOKEN").then(function (prim) {
    return prim.json();
  });
}).then(function (session_hits) {
  const hits = json_list(get_json(session_hits, "hits"));
  assert_(Caml_obj.caml_equal(hits, /* [] */ 0), "FTS misses the session token");
  return Melange__Hono.request_get_p(app, "/api/memory?q=PROPOSALONLYTOKEN").then(function (prim) {
    return prim.json();
  });
}).then(function (proposal_hits) {
  const hits = json_list(get_json(proposal_hits, "hits"));
  assert_(Caml_obj.caml_equal(hits, /* [] */ 0), "FTS misses the proposal token");
  return Melange__Hono.request_get_p(app, "/api/memory?q=REJECTEDONLYTOKEN").then(function (prim) {
    return prim.json();
  });
}).then(function (rejected_hits) {
  const hits = json_list(get_json(rejected_hits, "hits"));
  assert_(Caml_obj.caml_equal(hits, /* [] */ 0), "FTS misses the rejected token");
  return Melange__Hono.request_get_p(app, "/api/memory?q=SUPERSEDEDONLYTOKEN").then(function (prim) {
    return prim.json();
  });
}).then(function (superseded_hits) {
  const hits = json_list(get_json(superseded_hits, "hits"));
  assert_(Caml_obj.caml_equal(hits, /* [] */ 0), "FTS misses the superseded token");
  return Melange__Hono.request_get_p(app, "/api/memory?q=NOSTATUSTOKEN").then(function (prim) {
    return prim.json();
  });
}).then(function (bare_hits) {
  const hits = json_list(get_json(bare_hits, "hits"));
  assert_(Caml_obj.caml_equal(hits, /* [] */ 0), "FTS misses the missing-status token");
  return Promise.resolve(finish());
}).catch(function (e) {
  const msg = Stdlib__Option.value(e.message, "unknown JS error");
  Melange__Js_shims.Console.error("check crashed: " + msg);
  return process.exit(1);
});

export {
  failures,
  assert_,
  eq_string,
  field,
  str_field,
  get_json,
  get_str,
  get_bool,
  first_visual_kind,
  json_array_to_list,
  json_list,
  sync_checks,
  write_note,
  make_tmp_project,
  finish,
}
/*  Not a pure module */
