// Generated by Melange

import * as Caml from "melange.js/caml.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Caml_obj from "melange.js/caml_obj.js";
import * as Caml_string from "melange.js/caml_string.js";
import * as Curry from "melange.js/curry.js";
import * as Melange__Domain from "./domain.js";
import * as Melange__Speckit from "./speckit.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Buffer from "melange/buffer.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Stdlib__String from "melange/string.js";

function estimate_tokens(text) {
  return ((text.length + 4 | 0) - 1 | 0) / 4 | 0;
}

function cap_tokens(text, max_tokens) {
  const max_chars = (max_tokens << 2);
  if (text.length <= max_chars) {
    return text;
  }
  const sliced = Stdlib__String.sub(text, 0, max_chars);
  const back = function (_i) {
    while (true) {
      const i = _i;
      if (!(i >= 0 && Caml_string.get(sliced, i) !== /* '\n' */10)) {
        return i;
      }
      _i = i - 1 | 0;
      continue;
    };
  };
  const last_nl = back(max_chars - 1 | 0);
  const cut = last_nl > (Math.imul(max_chars, 6) / 10 | 0) ? Stdlib__String.sub(sliced, 0, last_nl) : sliced;
  return Melange__Speckit.trim(cut) + "\n\n<!-- truncated -->\n";
}

function horizon_of_feature(f) {
  return f.inferred_horizon;
}

function open_tasks(features) {
  return Stdlib__List.concat_map((function (f) {
    return Stdlib__List.filter((function (t) {
      return !t.is_done;
    }), f.tasks);
  }), features);
}

function index_tasks(features) {
  return Stdlib__List.concat_map((function (f) {
    return Stdlib__List.map((function (t) {
      return [
        Melange__Domain.make_ref(f.slug, t.id),
        t
      ];
    }), f.tasks);
  }), features);
}

function ready_tasks(features) {
  const by_ref = index_tasks(features);
  const lookup = function (ref_) {
    try {
      return Stdlib__List.assoc(ref_, by_ref);
    }
    catch (raw_exn){
      const exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn.MEL_EXN_ID === Stdlib.Not_found) {
        return;
      }
      throw exn;
    }
  };
  return Stdlib__List.filter((function (task) {
    return Stdlib__List.for_all((function (id) {
      const dep = lookup(Melange__Domain.make_ref(task.spec_slug, id));
      if (dep !== undefined) {
        return dep.is_done;
      } else {
        return false;
      }
    }), task.depends_on);
  }), open_tasks(features));
}

function blocked_tasks(features) {
  const by_ref = index_tasks(features);
  const dep_done = function (ref_) {
    try {
      return Stdlib__List.assoc(ref_, by_ref).is_done;
    }
    catch (raw_exn){
      const exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn.MEL_EXN_ID === Stdlib.Not_found) {
        return false;
      }
      throw exn;
    }
  };
  return Stdlib__List.concat_map((function (feature) {
    const gate = feature.constitution_gate_failing ? ({
        hd: {
          card: {
            TAG: /* Spec_card */ 0,
            _0: Melange__Domain.spec_card(feature)
          },
          why: "constitution check failing",
          kind: "feature"
        },
        tl: /* [] */ 0
      }) : /* [] */ 0;
    const unmet = Stdlib__List.filter_map((function (task) {
      if (task.is_done) {
        return;
      }
      const waiting = Stdlib__List.filter((function (id) {
        return !dep_done(Melange__Domain.make_ref(task.spec_slug, id));
      }), task.depends_on);
      if (Caml_obj.caml_equal(waiting, /* [] */ 0)) {
        return;
      }
      const ids = Stdlib__List.map((function (id) {
        return Melange__Domain.make_ref(task.spec_slug, id);
      }), waiting);
      return {
        card: {
          TAG: /* Task_card */ 1,
          _0: Melange__Domain.task_card(task)
        },
        why: "waiting on " + Stdlib__String.concat(", ", ids),
        kind: "task"
      };
    }), feature.tasks);
    return Stdlib.$at(gate, unmet);
  }), features);
}

function in_flight(features) {
  return Stdlib__List.filter((function (f) {
    if (f.status === /* In_progress */ 2) {
      return true;
    } else {
      return f.status === /* Blocked */ 4;
    }
  }), features);
}

function needs_plan(features) {
  return Stdlib__List.filter((function (f) {
    return f.status === /* Specified */ 0;
  }), features);
}

function metrics_of(features) {
  const by_status = Stdlib__List.fold_left((function (acc, f) {
    const k = Melange__Domain.status_to_string(f.status);
    const match = Stdlib__List.assoc_opt(k, acc);
    if (match !== undefined) {
      return Stdlib__List.map((function (param) {
        const b = param[1];
        const a = param[0];
        if (a === k) {
          return [
            a,
            b + 1 | 0
          ];
        } else {
          return [
            a,
            b
          ];
        }
      }), acc);
    } else {
      return Stdlib.$at(acc, {
        hd: [
          k,
          1
        ],
        tl: /* [] */ 0
      });
    }
  }), /* [] */ 0, features);
  const by_horizon = Stdlib__List.fold_left((function (param, f) {
    const later = param[2];
    const next = param[1];
    const now = param[0];
    const match = f.inferred_horizon;
    switch (match) {
      case /* Now */ 0 :
        return [
          now + 1 | 0,
          next,
          later
        ];
      case /* Next */ 1 :
        return [
          now,
          next + 1 | 0,
          later
        ];
      case /* Later */ 2 :
        return [
          now,
          next,
          later + 1 | 0
        ];
    }
  }), [
    0,
    0,
    0
  ], features);
  const tasks = Stdlib__List.concat_map((function (f) {
    return f.tasks;
  }), features);
  return {
    m_features: Stdlib__List.length(features),
    m_by_status: by_status,
    m_by_horizon: by_horizon,
    m_open_tasks: Stdlib__List.length(Stdlib__List.filter((function (t) {
      return !t.is_done;
    }), tasks)),
    m_total_tasks: Stdlib__List.length(tasks)
  };
}

function build_summary(features, blocked, generated_at) {
  const flight = in_flight(features);
  const ready = ready_tasks(features);
  const unplanned = needs_plan(features);
  const metrics = metrics_of(features);
  const b = Stdlib__Buffer.create(1024);
  Stdlib__Buffer.add_string(b, "<!-- generated: do not edit -->\n");
  Stdlib__Buffer.add_string(b, "# What should we work on?");
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "Updated: " + generated_at);
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "## In flight");
  Stdlib__Buffer.add_string(b, "\n");
  if (Caml_obj.caml_equal(flight, /* [] */ 0)) {
    Stdlib__Buffer.add_string(b, "- none");
    Stdlib__Buffer.add_string(b, "\n");
  } else {
    Stdlib__List.iter((function (f) {
      const open_ = Stdlib__List.length(Stdlib__List.filter((function (t) {
        return !t.is_done;
      }), f.tasks));
      const next = Stdlib__List.find_opt((function (t) {
        return t.spec_slug === f.slug;
      }), ready);
      const next_bit = next !== undefined ? " Next ready: " + (next.id + (" " + next.title)) : "";
      Stdlib__Buffer.add_string(b, Curry._6(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "- **",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: "** (",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: ", ",
                  _1: {
                    TAG: /* String */ 2,
                    _0: /* No_padding */ 0,
                    _1: {
                      TAG: /* String_literal */ 11,
                      _0: ") \xe2\x80\x94 ",
                      _1: {
                        TAG: /* Int */ 4,
                        _0: /* Int_d */ 0,
                        _1: /* No_padding */ 0,
                        _2: /* No_precision */ 0,
                        _3: {
                          TAG: /* Char_literal */ 12,
                          _0: /* '/' */47,
                          _1: {
                            TAG: /* Int */ 4,
                            _0: /* Int_d */ 0,
                            _1: /* No_padding */ 0,
                            _2: /* No_precision */ 0,
                            _3: {
                              TAG: /* String_literal */ 11,
                              _0: " open.",
                              _1: {
                                TAG: /* String */ 2,
                                _0: /* No_padding */ 0,
                                _1: {
                                  TAG: /* Char_literal */ 12,
                                  _0: /* '\n' */10,
                                  _1: /* End_of_format */ 0
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        _1: "- **%s** (%s, %s) \xe2\x80\x94 %d/%d open.%s\n"
      }), f.slug, Melange__Domain.status_to_string(f.status), Melange__Domain.horizon_to_string(f.inferred_horizon), open_, Stdlib__List.length(f.tasks), next_bit));
    }), flight);
  }
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "## Blocked");
  Stdlib__Buffer.add_string(b, "\n");
  if (Caml_obj.caml_equal(blocked, /* [] */ 0)) {
    Stdlib__Buffer.add_string(b, "- none");
    Stdlib__Buffer.add_string(b, "\n");
  } else {
    const take = function (n, param) {
      if (param && n > 0) {
        return {
          hd: param.hd,
          tl: take(n - 1 | 0, param.tl)
        };
      } else {
        return /* [] */ 0;
      }
    };
    Stdlib__List.iter((function (item) {
      const c = item.card;
      let id;
      id = c.TAG === /* Spec_card */ 0 ? c._0.slug : c._0.card_ref;
      Stdlib__Buffer.add_string(b, "- " + (id + (" \xe2\x80\x94 " + item.why)));
      Stdlib__Buffer.add_string(b, "\n");
    }), take(12, blocked));
  }
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "## Ready queue");
  Stdlib__Buffer.add_string(b, "\n");
  if (Caml_obj.caml_equal(ready, /* [] */ 0)) {
    const s = Caml_obj.caml_equal(unplanned, /* [] */ 0) ? "- none" : "- none \xe2\x80\x94 write a plan first, see Needs a plan below";
    Stdlib__Buffer.add_string(b, s);
    Stdlib__Buffer.add_string(b, "\n");
  } else {
    const take$1 = function (n, param) {
      if (param && n > 0) {
        return {
          hd: param.hd,
          tl: take$1(n - 1 | 0, param.tl)
        };
      } else {
        return /* [] */ 0;
      }
    };
    Stdlib__List.iteri((function (i, t) {
      const s = Curry._3(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* Int */ 4,
          _0: /* Int_d */ 0,
          _1: /* No_padding */ 0,
          _2: /* No_precision */ 0,
          _3: {
            TAG: /* String_literal */ 11,
            _0: ". ",
            _1: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: {
                TAG: /* String_literal */ 11,
                _0: " \xe2\x80\x94 ",
                _1: {
                  TAG: /* String */ 2,
                  _0: /* No_padding */ 0,
                  _1: /* End_of_format */ 0
                }
              }
            }
          }
        },
        _1: "%d. %s \xe2\x80\x94 %s"
      }), i + 1 | 0, Melange__Domain.make_ref(t.spec_slug, t.id), t.title);
      Stdlib__Buffer.add_string(b, s);
      Stdlib__Buffer.add_string(b, "\n");
    }), take$1(8, ready));
  }
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "## Needs a plan");
  Stdlib__Buffer.add_string(b, "\n");
  if (Caml_obj.caml_equal(unplanned, /* [] */ 0)) {
    Stdlib__Buffer.add_string(b, "- none");
    Stdlib__Buffer.add_string(b, "\n");
  } else {
    Stdlib__List.iter((function (f) {
      Stdlib__Buffer.add_string(b, Curry._4(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "- **",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: "** (",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: ") \xe2\x80\x94 ",
                  _1: {
                    TAG: /* String */ 2,
                    _0: /* No_padding */ 0,
                    _1: {
                      TAG: /* String_literal */ 11,
                      _0: ". Write `specs/",
                      _1: {
                        TAG: /* String */ 2,
                        _0: /* No_padding */ 0,
                        _1: {
                          TAG: /* String_literal */ 11,
                          _0: "/plan.md`.\n",
                          _1: /* End_of_format */ 0
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        _1: "- **%s** (%s) \xe2\x80\x94 %s. Write `specs/%s/plan.md`.\n"
      }), f.slug, Melange__Domain.horizon_to_string(f.inferred_horizon), f.title, f.slug));
    }), unplanned);
  }
  Stdlib__Buffer.add_string(b, "\n");
  const now_specs = Stdlib__List.filter((function (f) {
    return f.inferred_horizon === /* Now */ 0;
  }), features);
  Stdlib__Buffer.add_string(b, "## Now horizon");
  Stdlib__Buffer.add_string(b, "\n");
  if (Caml_obj.caml_equal(now_specs, /* [] */ 0)) {
    Stdlib__Buffer.add_string(b, "- none");
    Stdlib__Buffer.add_string(b, "\n");
  } else {
    Stdlib__List.iter((function (f) {
      Stdlib__Buffer.add_string(b, "- " + (f.slug + (" \xe2\x80\x94 " + f.title)));
      Stdlib__Buffer.add_string(b, "\n");
    }), now_specs);
  }
  Stdlib__Buffer.add_string(b, "\n");
  const match = metrics.m_by_horizon;
  Stdlib__Buffer.add_string(b, "## Metrics");
  Stdlib__Buffer.add_string(b, "\n");
  const s$1 = Curry._1(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "- features: ",
      _1: {
        TAG: /* Int */ 4,
        _0: /* Int_d */ 0,
        _1: /* No_padding */ 0,
        _2: /* No_precision */ 0,
        _3: /* End_of_format */ 0
      }
    },
    _1: "- features: %d"
  }), metrics.m_features);
  Stdlib__Buffer.add_string(b, s$1);
  Stdlib__Buffer.add_string(b, "\n");
  const s$2 = Curry._2(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "- open tasks: ",
      _1: {
        TAG: /* Int */ 4,
        _0: /* Int_d */ 0,
        _1: /* No_padding */ 0,
        _2: /* No_precision */ 0,
        _3: {
          TAG: /* Char_literal */ 12,
          _0: /* '/' */47,
          _1: {
            TAG: /* Int */ 4,
            _0: /* Int_d */ 0,
            _1: /* No_padding */ 0,
            _2: /* No_precision */ 0,
            _3: /* End_of_format */ 0
          }
        }
      }
    },
    _1: "- open tasks: %d/%d"
  }), metrics.m_open_tasks, metrics.m_total_tasks);
  Stdlib__Buffer.add_string(b, s$2);
  Stdlib__Buffer.add_string(b, "\n");
  const s$3 = Curry._3(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "- horizon now/next/later: ",
      _1: {
        TAG: /* Int */ 4,
        _0: /* Int_d */ 0,
        _1: /* No_padding */ 0,
        _2: /* No_precision */ 0,
        _3: {
          TAG: /* Char_literal */ 12,
          _0: /* '/' */47,
          _1: {
            TAG: /* Int */ 4,
            _0: /* Int_d */ 0,
            _1: /* No_padding */ 0,
            _2: /* No_precision */ 0,
            _3: {
              TAG: /* Char_literal */ 12,
              _0: /* '/' */47,
              _1: {
                TAG: /* Int */ 4,
                _0: /* Int_d */ 0,
                _1: /* No_padding */ 0,
                _2: /* No_precision */ 0,
                _3: /* End_of_format */ 0
              }
            }
          }
        }
      }
    },
    _1: "- horizon now/next/later: %d/%d/%d"
  }), match[0], match[1], match[2]);
  Stdlib__Buffer.add_string(b, s$3);
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "\n");
  return cap_tokens(Stdlib__Buffer.contents(b), 1000);
}

function build_active(features) {
  const flight = in_flight(features);
  const b = Stdlib__Buffer.create(512);
  Stdlib__Buffer.add_string(b, "<!-- generated: do not edit -->\n");
  Stdlib__Buffer.add_string(b, "# Active\n\n");
  if (Caml_obj.caml_equal(flight, /* [] */ 0)) {
    Stdlib__Buffer.add_string(b, "No specs in flight.\n");
  } else {
    Stdlib__List.iter((function (f) {
      Stdlib__Buffer.add_string(b, Curry._2(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "## ",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: " \xe2\x80\x94 ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: "\n\n",
                  _1: /* End_of_format */ 0
                }
              }
            }
          }
        },
        _1: "## %s \xe2\x80\x94 %s\n\n"
      }), f.slug, f.title));
      Stdlib__Buffer.add_string(b, Curry._2(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "Status: ",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: ". Horizon: ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: ".\n\n",
                  _1: /* End_of_format */ 0
                }
              }
            }
          }
        },
        _1: "Status: %s. Horizon: %s.\n\n"
      }), Melange__Domain.status_to_string(f.status), Melange__Domain.horizon_to_string(f.inferred_horizon)));
      Stdlib__Buffer.add_string(b, "\n");
      Stdlib__List.iter((function (t) {
        Stdlib__Buffer.add_string(b, "- [ ] " + (t.id + (" " + (t.title + "\n"))));
      }), Stdlib__List.filter((function (t) {
        return !t.is_done;
      }), f.tasks));
      Stdlib__Buffer.add_string(b, "\n");
    }), flight);
  }
  return cap_tokens(Stdlib__Buffer.contents(b), 4000);
}

function build_blocked_md(blocked) {
  const b = Stdlib__Buffer.create(256);
  Stdlib__Buffer.add_string(b, "<!-- generated: do not edit -->\n");
  Stdlib__Buffer.add_string(b, "# Blocked\n\n");
  if (Caml_obj.caml_equal(blocked, /* [] */ 0)) {
    Stdlib__Buffer.add_string(b, "Nothing blocked.\n");
  } else {
    Stdlib__List.iter((function (item) {
      const c = item.card;
      let id;
      id = c.TAG === /* Spec_card */ 0 ? c._0.slug : c._0.card_ref;
      Stdlib__Buffer.add_string(b, "- **" + (id + ("**: " + (item.why + "\n"))));
    }), blocked);
    Stdlib__Buffer.add_string(b, "\n");
  }
  return Stdlib__Buffer.contents(b);
}

function build_metrics_md(features) {
  const m = metrics_of(features);
  const match = m.m_by_horizon;
  const entries = m.m_by_status;
  const status_lines = entries ? Stdlib__String.concat("\n", Stdlib__List.map((function (param) {
      return Curry._2(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "- ",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: ": ",
              _1: {
                TAG: /* Int */ 4,
                _0: /* Int_d */ 0,
                _1: /* No_padding */ 0,
                _2: /* No_precision */ 0,
                _3: /* End_of_format */ 0
              }
            }
          }
        },
        _1: "- %s: %d"
      }), param[0], param[1]);
    }), entries)) : "- none";
  return Stdlib__String.concat("\n", {
    hd: "<!-- generated: do not edit -->",
    tl: {
      hd: "# Metrics",
      tl: {
        hd: "",
        tl: {
          hd: Curry._1(Stdlib__Printf.sprintf({
            TAG: /* Format */ 0,
            _0: {
              TAG: /* String_literal */ 11,
              _0: "features: ",
              _1: {
                TAG: /* Int */ 4,
                _0: /* Int_d */ 0,
                _1: /* No_padding */ 0,
                _2: /* No_precision */ 0,
                _3: /* End_of_format */ 0
              }
            },
            _1: "features: %d"
          }), m.m_features),
          tl: {
            hd: Curry._2(Stdlib__Printf.sprintf({
              TAG: /* Format */ 0,
              _0: {
                TAG: /* String_literal */ 11,
                _0: "open tasks: ",
                _1: {
                  TAG: /* Int */ 4,
                  _0: /* Int_d */ 0,
                  _1: /* No_padding */ 0,
                  _2: /* No_precision */ 0,
                  _3: {
                    TAG: /* Char_literal */ 12,
                    _0: /* '/' */47,
                    _1: {
                      TAG: /* Int */ 4,
                      _0: /* Int_d */ 0,
                      _1: /* No_padding */ 0,
                      _2: /* No_precision */ 0,
                      _3: /* End_of_format */ 0
                    }
                  }
                }
              },
              _1: "open tasks: %d/%d"
            }), m.m_open_tasks, m.m_total_tasks),
            tl: {
              hd: "",
              tl: {
                hd: "## By status",
                tl: {
                  hd: status_lines,
                  tl: {
                    hd: "",
                    tl: {
                      hd: "## By horizon",
                      tl: {
                        hd: Curry._1(Stdlib__Printf.sprintf({
                          TAG: /* Format */ 0,
                          _0: {
                            TAG: /* String_literal */ 11,
                            _0: "- now: ",
                            _1: {
                              TAG: /* Int */ 4,
                              _0: /* Int_d */ 0,
                              _1: /* No_padding */ 0,
                              _2: /* No_precision */ 0,
                              _3: /* End_of_format */ 0
                            }
                          },
                          _1: "- now: %d"
                        }), match[0]),
                        tl: {
                          hd: Curry._1(Stdlib__Printf.sprintf({
                            TAG: /* Format */ 0,
                            _0: {
                              TAG: /* String_literal */ 11,
                              _0: "- next: ",
                              _1: {
                                TAG: /* Int */ 4,
                                _0: /* Int_d */ 0,
                                _1: /* No_padding */ 0,
                                _2: /* No_precision */ 0,
                                _3: /* End_of_format */ 0
                              }
                            },
                            _1: "- next: %d"
                          }), match[1]),
                          tl: {
                            hd: Curry._1(Stdlib__Printf.sprintf({
                              TAG: /* Format */ 0,
                              _0: {
                                TAG: /* String_literal */ 11,
                                _0: "- later: ",
                                _1: {
                                  TAG: /* Int */ 4,
                                  _0: /* Int_d */ 0,
                                  _1: /* No_padding */ 0,
                                  _2: /* No_precision */ 0,
                                  _3: /* End_of_format */ 0
                                }
                              },
                              _1: "- later: %d"
                            }), match[2]),
                            tl: {
                              hd: "",
                              tl: /* [] */ 0
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  });
}

function build_index(features) {
  const sorted = Stdlib__List.sort((function (a, b) {
    return Caml.caml_string_compare(a.slug, b.slug);
  }), features);
  const b = Stdlib__Buffer.create(512);
  Stdlib__Buffer.add_string(b, "<!-- generated: do not edit. Router only \xe2\x80\x94 load one spec folder. -->\n");
  Stdlib__Buffer.add_string(b, "# Specs\n\n");
  Stdlib__Buffer.add_string(b, "| ID | Title | Status | Horizon | Tasks | Path |\n");
  Stdlib__Buffer.add_string(b, "|---|---|---|---|---|---|\n");
  if (Caml_obj.caml_equal(sorted, /* [] */ 0)) {
    Stdlib__Buffer.add_string(b, "| \xe2\x80\x94 | no specs yet | \xe2\x80\x94 | \xe2\x80\x94 | \xe2\x80\x94 | \xe2\x80\x94 |\n");
  } else {
    Stdlib__List.iter((function (f) {
      const open_ = Stdlib__List.length(Stdlib__List.filter((function (t) {
        return !t.is_done;
      }), f.tasks));
      const title = Stdlib__String.concat("\\|", Stdlib__String.split_on_char(/* '|' */124, f.title));
      Stdlib__Buffer.add_string(b, Curry._8(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "| ",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: " | ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: " | ",
                  _1: {
                    TAG: /* String */ 2,
                    _0: /* No_padding */ 0,
                    _1: {
                      TAG: /* String_literal */ 11,
                      _0: " | ",
                      _1: {
                        TAG: /* String */ 2,
                        _0: /* No_padding */ 0,
                        _1: {
                          TAG: /* String_literal */ 11,
                          _0: " | ",
                          _1: {
                            TAG: /* Int */ 4,
                            _0: /* Int_d */ 0,
                            _1: /* No_padding */ 0,
                            _2: /* No_precision */ 0,
                            _3: {
                              TAG: /* Char_literal */ 12,
                              _0: /* '/' */47,
                              _1: {
                                TAG: /* Int */ 4,
                                _0: /* Int_d */ 0,
                                _1: /* No_padding */ 0,
                                _2: /* No_precision */ 0,
                                _3: {
                                  TAG: /* String_literal */ 11,
                                  _0: " | [",
                                  _1: {
                                    TAG: /* String */ 2,
                                    _0: /* No_padding */ 0,
                                    _1: {
                                      TAG: /* String_literal */ 11,
                                      _0: "](./",
                                      _1: {
                                        TAG: /* String */ 2,
                                        _0: /* No_padding */ 0,
                                        _1: {
                                          TAG: /* String_literal */ 11,
                                          _0: "/) |\n",
                                          _1: /* End_of_format */ 0
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        _1: "| %s | %s | %s | %s | %d/%d | [%s](./%s/) |\n"
      }), f.slug, title, Melange__Domain.status_to_string(f.status), Melange__Domain.horizon_to_string(f.inferred_horizon), open_, Stdlib__List.length(f.tasks), f.slug, f.slug));
    }), sorted);
  }
  Stdlib__Buffer.add_string(b, "\n");
  Stdlib__Buffer.add_string(b, "Read `spec.md` (what/why), `plan.md` (how), `tasks.md` (the backlog for that feature).\n\n");
  return Stdlib__Buffer.contents(b);
}

const chars_per_token = 4;

const summary_token_cap = 1000;

const board_token_cap = 4000;

export {
  chars_per_token,
  summary_token_cap,
  board_token_cap,
  estimate_tokens,
  cap_tokens,
  horizon_of_feature,
  open_tasks,
  index_tasks,
  ready_tasks,
  blocked_tasks,
  in_flight,
  needs_plan,
  metrics_of,
  build_summary,
  build_active,
  build_blocked_md,
  build_metrics_md,
  build_index,
}
/* No side effect */
