// Generated by Melange

import * as Caml_string from "melange.js/caml_string.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__String from "melange/string.js";

function horizon_to_string(param) {
  switch (param) {
    case /* Now */ 0 :
      return "now";
    case /* Next */ 1 :
      return "next";
    case /* Later */ 2 :
      return "later";
  }
}

function horizon_of_string(param) {
  switch (param) {
    case "later" :
      return /* Later */ 2;
    case "next" :
      return /* Next */ 1;
    case "now" :
      return /* Now */ 0;
    default:
      return;
  }
}

function priority_to_string(param) {
  switch (param) {
    case /* Critical */ 0 :
      return "critical";
    case /* High */ 1 :
      return "high";
    case /* Medium */ 2 :
      return "medium";
    case /* Low */ 3 :
      return "low";
  }
}

function priority_of_string(param) {
  switch (param) {
    case "critical" :
      return /* Critical */ 0;
    case "high" :
      return /* High */ 1;
    case "low" :
      return /* Low */ 3;
    case "medium" :
      return /* Medium */ 2;
    default:
      return;
  }
}

function status_to_string(param) {
  switch (param) {
    case /* Specified */ 0 :
      return "specified";
    case /* Planned */ 1 :
      return "planned";
    case /* In_progress */ 2 :
      return "in-progress";
    case /* Done */ 3 :
      return "done";
    case /* Blocked */ 4 :
      return "blocked";
  }
}

function make_ref(slug, task_id) {
  if (task_id !== undefined) {
    return slug + ("#" + task_id);
  } else {
    return slug;
  }
}

function parse_ref(ref_) {
  const n = ref_.length;
  const start = function (_i) {
    while (true) {
      const i = _i;
      if (!(i < n && Caml_string.get(ref_, i) === /* '/' */47)) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  const stop = function (_i) {
    while (true) {
      const i = _i;
      if (!(i >= 0 && Caml_string.get(ref_, i) === /* '/' */47)) {
        return i;
      }
      _i = i - 1 | 0;
      continue;
    };
  };
  const a = start(0);
  const b = stop(n - 1 | 0);
  if (a > b) {
    return {
      slug: undefined,
      task_id: undefined
    };
  }
  const trimmed = Stdlib__String.sub(ref_, a, (b - a | 0) + 1 | 0);
  const i = Stdlib__String.index_opt(trimmed, /* '#' */35);
  if (i === undefined) {
    return {
      slug: trimmed,
      task_id: undefined
    };
  }
  const slug = Stdlib__String.sub(trimmed, 0, i);
  const rest = Stdlib__String.sub(trimmed, i + 1 | 0, (trimmed.length - i | 0) - 1 | 0);
  if (rest === "") {
    return {
      slug: slug,
      task_id: undefined
    };
  } else {
    return {
      slug: slug,
      task_id: rest
    };
  }
}

function is_digit(c) {
  if (c >= /* '0' */48) {
    return c <= /* '9' */57;
  } else {
    return false;
  }
}

function is_word_char(c) {
  if (is_digit(c) || c >= /* 'a' */97 && c <= /* 'z' */122 || c >= /* 'A' */65 && c <= /* 'Z' */90) {
    return true;
  } else {
    return c === /* '_' */95;
  }
}

function is_slug_char(c) {
  if (is_word_char(c)) {
    return true;
  } else {
    return c === /* '-' */45;
  }
}

function is_feature_slug(name) {
  const n = name.length;
  if (n < 5) {
    return false;
  }
  if (!is_digit(Caml_string.get(name, 0))) {
    return false;
  }
  if (!is_digit(Caml_string.get(name, 1))) {
    return false;
  }
  if (!is_digit(Caml_string.get(name, 2))) {
    return false;
  }
  if (Caml_string.get(name, 3) !== /* '-' */45) {
    return false;
  }
  const c = Caml_string.get(name, 4);
  if (!(is_digit(c) || c >= /* 'a' */97 && c <= /* 'z' */122)) {
    return false;
  }
  let _i = 5;
  while (true) {
    const i = _i;
    if (i >= n) {
      return true;
    }
    if (!is_slug_char(Caml_string.get(name, i))) {
      return false;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function spec_card(f) {
  const open_ = Stdlib__List.fold_left((function (n, t) {
    if (t.is_done) {
      return n;
    } else {
      return n + 1 | 0;
    }
  }), 0, f.tasks);
  return {
    slug: f.slug,
    title: f.title,
    horizon: f.inferred_horizon,
    priority: f.priority,
    status: f.status,
    open_tasks: open_,
    total_tasks: Stdlib__List.length(f.tasks)
  };
}

function task_card(t) {
  return {
    card_ref: make_ref(t.spec_slug, t.id),
    card_title: t.title,
    card_done: t.is_done,
    card_spec_slug: t.spec_slug,
    card_priority: t.priority
  };
}

export {
  horizon_to_string,
  horizon_of_string,
  priority_to_string,
  priority_of_string,
  status_to_string,
  make_ref,
  parse_ref,
  is_digit,
  is_word_char,
  is_slug_char,
  is_feature_slug,
  spec_card,
  task_card,
}
/* No side effect */
