// Generated by Melange

import * as Caml_array from "melange.js/caml_array.js";
import * as Caml_obj from "melange.js/caml_obj.js";
import * as Caml_option from "melange.js/caml_option.js";
import * as Caml_string from "melange.js/caml_string.js";
import * as Js__Js_dict from "melange.js/js_dict.js";
import * as Js__Js_json from "melange.js/js_json.js";
import * as Melange__Domain from "./domain.js";
import * as Melange__Speckit from "./speckit.js";
import * as Melange__Views from "./views.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Option from "melange/option.js";
import * as Stdlib__String from "melange/string.js";

function get_field(d, k) {
  const v = Js__Js_dict.get(d, k);
  if (v !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(v));
  }
  
}

function contains_ci(hay, needle) {
  return Melange__Speckit.contains(Stdlib__String.lowercase_ascii(hay), needle);
}

function word_at(s, i, n) {
  const n_total = s.length;
  const before_ok = i === 0 || !Melange__Domain.is_word_char(Caml_string.get(s, i - 1 | 0));
  const after_i = i + n | 0;
  const after_ok = after_i >= n_total || !Melange__Domain.is_word_char(Caml_string.get(s, after_i));
  if (before_ok) {
    return after_ok;
  } else {
    return false;
  }
}

function contains_word_ci(hay, needle) {
  const low = Stdlib__String.lowercase_ascii(hay);
  const n = low.length;
  const m = needle.length;
  let _i = 0;
  while (true) {
    const i = _i;
    if ((i + m | 0) > n) {
      return false;
    }
    if (Stdlib__String.sub(low, i, m) === needle && word_at(low, i, m)) {
      return true;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function is_punct(c) {
  if (c >= 46) {
    if (c < 60) {
      return c > 57 || c < 47;
    } else {
      return c === 63;
    }
  } else if (c !== 33) {
    return c === 44;
  } else {
    return true;
  }
}

function standalone_word(q, w) {
  const n = q.length;
  const m = w.length;
  let _i = 0;
  while (true) {
    const i = _i;
    if ((i + m | 0) > n) {
      return false;
    }
    if (Stdlib__String.sub(q, i, m) === w) {
      const before_ok = i === 0 || Caml_string.get(q, i - 1 | 0) === /* ' ' */32;
      const j = i + m | 0;
      const after_ok = j >= n || Caml_string.get(q, j) === /* ' ' */32 || is_punct(Caml_string.get(q, j));
      if (before_ok && after_ok) {
        return true;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function find_slug_in_text(message, slugs) {
  const known = Stdlib__List.find_opt((function (s) {
    return contains_word_ci(message, s);
  }), slugs);
  if (known !== undefined) {
    return known;
  }
  const n = message.length;
  const low = Stdlib__String.lowercase_ascii(message);
  let _i = 0;
  while (true) {
    const i = _i;
    if ((i + 4 | 0) > n) {
      return;
    }
    if (Melange__Domain.is_digit(Caml_string.get(low, i)) && Melange__Domain.is_digit(Caml_string.get(low, i + 1 | 0)) && Melange__Domain.is_digit(Caml_string.get(low, i + 2 | 0)) && Caml_string.get(low, i + 3 | 0) === /* '-' */45 && (i === 0 || !Melange__Domain.is_word_char(Caml_string.get(low, i - 1 | 0)))) {
      const c = Caml_string.get(low, i + 4 | 0);
      if (Melange__Domain.is_digit(c) || c >= /* 'a' */97 && c <= /* 'z' */122) {
        const take = function (_j) {
          while (true) {
            const j = _j;
            if (!(j < n && Melange__Domain.is_word_char(Caml_string.get(low, j)))) {
              return j;
            }
            _j = j + 1 | 0;
            continue;
          };
        };
        const j = take(i + 4 | 0);
        const slug = Stdlib__String.sub(low, i, j - i | 0);
        if (word_at(low, i, j - i | 0)) {
          return slug;
        }
        _i = j;
        continue;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function find_task_in_text(message) {
  const n = message.length;
  const low = Stdlib__String.lowercase_ascii(message);
  let _i = 0;
  while (true) {
    const i = _i;
    if ((i + 4 | 0) > n) {
      return;
    }
    if (Caml_string.get(low, i) === /* 't' */116 && Melange__Domain.is_digit(Caml_string.get(low, i + 1 | 0)) && Melange__Domain.is_digit(Caml_string.get(low, i + 2 | 0)) && Melange__Domain.is_digit(Caml_string.get(low, i + 3 | 0)) && (i === 0 || !Melange__Domain.is_word_char(Caml_string.get(low, i - 1 | 0)))) {
      const take = function (_j) {
        while (true) {
          const j = _j;
          if (!(j < n && Melange__Domain.is_digit(Caml_string.get(low, j)))) {
            return j;
          }
          _j = j + 1 | 0;
          continue;
        };
      };
      const j = take(i + 1 | 0);
      if (j >= n || !Melange__Domain.is_word_char(Caml_string.get(low, j))) {
        return Stdlib__String.uppercase_ascii(Stdlib__String.sub(low, i, j - i | 0));
      }
      _i = j;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function classify(slugs, message) {
  if (contains_word_ci(message, "blocked")) {
    return /* Blocked */ 3;
  }
  if (contains_word_ci(message, "constitution")) {
    return /* Constitution */ 4;
  }
  if (Melange__Speckit.contains(Stdlib__String.lowercase_ascii(message), "why did we") || contains_word_ci(message, "decision") || contains_word_ci(message, "regression") || contains_word_ci(message, "memory")) {
    return {
      TAG: /* Memory */ 2,
      _0: message
    };
  }
  const slug = find_slug_in_text(message, slugs);
  const task_id = find_task_in_text(message);
  if (task_id !== undefined) {
    return {
      TAG: /* Task_ref */ 1,
      _0: slug !== undefined ? slug + ("#" + task_id) : task_id
    };
  } else if (slug !== undefined) {
    return {
      TAG: /* Spec */ 0,
      _0: slug
    };
  } else if (Melange__Speckit.contains(Stdlib__String.lowercase_ascii(message), "what should we") || Melange__Speckit.contains(Stdlib__String.lowercase_ascii(message), "what should i")) {
    return /* Summary */ 0;
  } else if (contains_word_ci(message, "roadmap") || contains_word_ci(message, "horizon") || standalone_word(Stdlib__String.lowercase_ascii(message), "now") || standalone_word(Stdlib__String.lowercase_ascii(message), "next") && contains_word_ci(message, "horizon")) {
    return /* Roadmap */ 1;
  } else if (contains_word_ci(message, "backlog") || contains_word_ci(message, "tasks")) {
    return /* Backlog */ 2;
  } else if (contains_word_ci(message, "graph")) {
    return /* Graph */ 5;
  } else {
    return /* Summary */ 0;
  }
}

function visual(kind, title, data) {
  return {
    v_kind: kind,
    v_title: title,
    v_data: data
  };
}

function make_envelope(text, visuals, citations) {
  const unique = function (_acc, _param) {
    while (true) {
      const param = _param;
      const acc = _acc;
      if (!param) {
        return Stdlib__List.rev(acc);
      }
      const rest = param.tl;
      const x = param.hd;
      if (Stdlib__List.mem(x, acc)) {
        _param = rest;
        continue;
      }
      _param = rest;
      _acc = {
        hd: x,
        tl: acc
      };
      continue;
    };
  };
  return {
    e_text: text,
    e_visuals: visuals,
    e_citations: unique(/* [] */ 0, citations)
  };
}

function resolve_task(ref_, cat) {
  const exact = function (ref_) {
    const match = Stdlib__List.assoc_opt(ref_, cat.cat_tasks);
    if (match !== undefined && !match[1]) {
      return match[0];
    }
    
  };
  const d = exact(ref_);
  if (d !== undefined) {
    return d;
  }
  const upper = Stdlib__String.uppercase_ascii(ref_);
  const d$1 = exact(upper);
  if (d$1 !== undefined) {
    return d$1;
  }
  const i = Stdlib__String.index_opt(ref_, /* '#' */35);
  if (i === undefined) {
    return;
  }
  const slug = Stdlib__String.sub(ref_, 0, i);
  const id = Stdlib__String.uppercase_ascii(Stdlib__String.sub(ref_, i + 1 | 0, (ref_.length - i | 0) - 1 | 0));
  return exact(slug + ("#" + id));
}

function morning_text(cat) {
  const flight = cat.cat_in_flight;
  const ready = cat.cat_ready;
  const blocked = cat.cat_blocked;
  if (Caml_obj.caml_equal(flight, /* [] */ 0) && Caml_obj.caml_equal(ready, /* [] */ 0)) {
    return "No specs in flight. Specify something, or pick a next-horizon writing to plan.";
  }
  const next = ready ? ready.hd : undefined;
  const next_bit = next !== undefined ? " Next ready task: " + (next.card_ref + (" \xe2\x80\x94 " + (next.card_title + "."))) : "";
  const block_bit = Caml_obj.caml_equal(blocked, /* [] */ 0) ? "" : " " + (String(Stdlib__List.length(blocked)) + " blocked.");
  const slugs = Stdlib__List.map((function (c) {
    return c.slug;
  }), flight);
  const flight_str = slugs ? Stdlib__String.concat(", ", slugs) : "none";
  return "In flight: " + (flight_str + ("." + (next_bit + block_bit)));
}

function blocked_citations(cat) {
  return Stdlib__List.filter_map((function (item) {
    const c = item.card;
    if (c.TAG === /* Spec_card */ 0) {
      return c._0.slug;
    } else {
      return c._0.card_ref;
    }
  }), cat.cat_blocked);
}

function memory_hit_paths(hits) {
  return Stdlib__List.filter_map((function (h) {
    const d = Js__Js_json.decodeObject(h);
    if (d !== undefined) {
      let v = get_field(Caml_option.valFromOption(d), "path");
      if (v !== undefined) {
        return Js__Js_json.decodeString(Caml_option.valFromOption(v));
      } else {
        return;
      }
    }
    
  }), hits);
}

function envelope_for(intent, cat) {
  if (/* tag */ typeof intent !== "object" && typeof intent !== "function") {
    switch (intent) {
      case /* Summary */ 0 :
        return make_envelope(morning_text(cat), {
          hd: {
            v_kind: "summary",
            v_title: "What should we work on?",
            v_data: cat.cat_summary_json
          },
          tl: /* [] */ 0
        }, Stdlib__List.map((function (c) {
          return c.slug;
        }), cat.cat_in_flight));
      case /* Roadmap */ 1 :
        return make_envelope("Specs grouped by horizon (now / next / later).", {
          hd: {
            v_kind: "roadmap",
            v_title: "Roadmap",
            v_data: cat.cat_roadmap_json
          },
          tl: /* [] */ 0
        }, cat.cat_roadmap_specs);
      case /* Backlog */ 2 :
        return make_envelope("Open tasks across specs, in file order.", {
          hd: {
            v_kind: "backlog",
            v_title: "Backlog",
            v_data: cat.cat_backlog_json
          },
          tl: /* [] */ 0
        }, Stdlib__List.map((function (t) {
          return t.card_ref;
        }), cat.cat_ready));
      case /* Blocked */ 3 :
        return make_envelope("Blocked items from constitution gates and unmet task order.", {
          hd: {
            v_kind: "blocked",
            v_title: "Blocked",
            v_data: cat.cat_blocked_json
          },
          tl: /* [] */ 0
        }, blocked_citations(cat));
      case /* Constitution */ 4 :
        const c = cat.cat_constitution;
        const constitution = c !== undefined ? c : ({
            c_title: "Constitution",
            c_excerpt: "Constitution is the gate.",
            c_body: ""
          });
        return make_envelope(constitution.c_excerpt !== "" ? constitution.c_excerpt : "Constitution is the gate.", {
          hd: {
            v_kind: "note_md",
            v_title: constitution.c_title !== "" ? constitution.c_title : "Constitution",
            v_data: Melange__Views.Json.obj({
              hd: [
                "markdown",
                Melange__Views.Json.str(constitution.c_body)
              ],
              tl: {
                hd: [
                  "path",
                  Melange__Views.Json.str(".specify/memory/constitution.md")
                ],
                tl: /* [] */ 0
              }
            })
          },
          tl: /* [] */ 0
        }, {
          hd: ".specify/memory/constitution.md",
          tl: /* [] */ 0
        });
      case /* Graph */ 5 :
        return make_envelope("Task order and wiki links from the writings.", {
          hd: {
            v_kind: "graph",
            v_title: "Graph",
            v_data: cat.cat_graph_json
          },
          tl: /* [] */ 0
        }, cat.cat_slugs);
    }
  } else {
    switch (intent.TAG) {
      case /* Spec */ 0 :
        const slug = intent._0;
        const d = Stdlib__List.assoc_opt(slug, cat.cat_specs);
        if (d !== undefined) {
          return make_envelope(d.sd_card.slug + (" \xe2\x80\x94 " + (d.sd_card.title + (" (" + (Melange__Domain.status_to_string(d.sd_card.status) + ")")))), {
            hd: {
              v_kind: "spec",
              v_title: d.sd_card.slug,
              v_data: Melange__Views.spec_detail_json(d)
            },
            tl: /* [] */ 0
          }, {
            hd: d.sd_card.slug,
            tl: /* [] */ 0
          });
        } else {
          return make_envelope("No spec " + (slug + "."), /* [] */ 0, /* [] */ 0);
        }
      case /* Task_ref */ 1 :
        const ref_ = intent._0;
        const d$1 = resolve_task(ref_, cat);
        if (d$1 !== undefined) {
          return make_envelope(d$1.td_card.card_ref + (" \xe2\x80\x94 " + d$1.td_card.card_title), {
            hd: {
              v_kind: "task",
              v_title: d$1.td_card.card_ref,
              v_data: Melange__Views.task_detail_json(d$1)
            },
            tl: /* [] */ 0
          }, {
            hd: d$1.td_slug,
            tl: {
              hd: d$1.td_card.card_ref,
              tl: /* [] */ 0
            }
          });
        } else {
          return make_envelope("No task " + (ref_ + " in the writings."), /* [] */ 0, /* [] */ 0);
        }
      case /* Memory */ 2 :
        const hits = cat.cat_memory_hits;
        return make_envelope(Caml_obj.caml_notequal(hits, /* [] */ 0) ? "Memory hits for \xe2\x80\x9c" + (intent._0 + "\xe2\x80\x9d.") : "No reviewed memory matched. Constitution is still citable; it is not copied into memory/.", {
          hd: {
            v_kind: "memory",
            v_title: "Memory",
            v_data: Melange__Views.Json.obj({
              hd: [
                "hits",
                Melange__Views.Json.arr(hits)
              ],
              tl: /* [] */ 0
            })
          },
          tl: /* [] */ 0
        }, memory_hit_paths(hits));
    }
  }
}

function is_visual_kind(kind) {
  return Stdlib__List.mem(kind, {
    hd: "summary",
    tl: {
      hd: "roadmap",
      tl: {
        hd: "backlog",
        tl: {
          hd: "spec",
          tl: {
            hd: "task",
            tl: {
              hd: "graph",
              tl: {
                hd: "blocked",
                tl: {
                  hd: "memory",
                  tl: {
                    hd: "note_md",
                    tl: /* [] */ 0
                  }
                }
              }
            }
          }
        }
      }
    }
  });
}

function encode_envelope(e) {
  return Melange__Views.Json.obj({
    hd: [
      "text",
      Melange__Views.Json.str(e.e_text)
    ],
    tl: {
      hd: [
        "visuals",
        Melange__Views.Json.arr(Stdlib__List.map((function (v) {
          return Melange__Views.Json.obj({
            hd: [
              "kind",
              Melange__Views.Json.str(v.v_kind)
            ],
            tl: {
              hd: [
                "title",
                Melange__Views.Json.str(v.v_title)
              ],
              tl: {
                hd: [
                  "data",
                  v.v_data
                ],
                tl: /* [] */ 0
              }
            }
          });
        }), e.e_visuals))
      ],
      tl: {
        hd: [
          "citations",
          Melange__Views.Json.arr(Stdlib__List.map(Melange__Views.Json.str, e.e_citations))
        ],
        tl: /* [] */ 0
      }
    }
  });
}

function get_field$1(d, k) {
  const v = Js__Js_dict.get(d, k);
  if (v !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(v));
  }
  
}

function as_string(v) {
  if (v !== undefined) {
    return Js__Js_json.decodeString(Caml_option.valFromOption(v));
  }
  
}

function decode_envelope(json) {
  const d = Js__Js_json.decodeObject(json);
  if (d === undefined) {
    return {
      TAG: /* Decode_err */ 1,
      _0: "not an object"
    };
  }
  const d$1 = Caml_option.valFromOption(d);
  const text = as_string(get_field$1(d$1, "text"));
  if (text === undefined) {
    return {
      TAG: /* Decode_err */ 1,
      _0: "text must be a string"
    };
  }
  const arg = [];
  const visuals_arr = Js__Js_json.decodeArray((function (param) {
    return Stdlib__Option.value(param, arg);
  })(get_field$1(d$1, "visuals")));
  if (visuals_arr === undefined) {
    return {
      TAG: /* Decode_err */ 1,
      _0: "visuals must be an array"
    };
  }
  const decode_visual = function (v) {
    const vd = Js__Js_json.decodeObject(v);
    if (vd === undefined) {
      return {
        TAG: /* Error */ 1,
        _0: "visual must be an object"
      };
    }
    const vd$1 = Caml_option.valFromOption(vd);
    const kind = as_string(get_field$1(vd$1, "kind"));
    if (kind === undefined) {
      return {
        TAG: /* Error */ 1,
        _0: "visual kind must be a string"
      };
    }
    if (!is_visual_kind(kind)) {
      return {
        TAG: /* Error */ 1,
        _0: "unknown visual kind: " + kind
      };
    }
    const title = as_string(get_field$1(vd$1, "title"));
    if (title === undefined) {
      return {
        TAG: /* Error */ 1,
        _0: "visual title must be a string"
      };
    }
    const data = get_field$1(vd$1, "data");
    const data$1 = data !== undefined ? Caml_option.valFromOption(data) : ({});
    return {
      TAG: /* Ok */ 0,
      _0: {
        v_kind: kind,
        v_title: title,
        v_data: data$1
      }
    };
  };
  const result = Stdlib__Array.fold_left((function (acc, v) {
    const match = decode_visual(v);
    if (acc.TAG === /* Ok */ 0) {
      if (match.TAG === /* Ok */ 0) {
        return {
          TAG: /* Ok */ 0,
          _0: {
            hd: match._0,
            tl: acc._0
          }
        };
      } else {
        return {
          TAG: /* Error */ 1,
          _0: match._0
        };
      }
    } else {
      return {
        TAG: /* Error */ 1,
        _0: acc._0
      };
    }
  }), {
    TAG: /* Ok */ 0,
    _0: /* [] */ 0
  }, visuals_arr);
  if (result.TAG !== /* Ok */ 0) {
    return {
      TAG: /* Decode_err */ 1,
      _0: result._0
    };
  }
  const visuals = Stdlib__List.rev(result._0);
  const c = get_field$1(d$1, "citations");
  let citations_opt;
  if (c !== undefined) {
    const arr = Js__Js_json.decodeArray(Caml_option.valFromOption(c));
    if (arr !== undefined) {
      const to_strs = function (_i, _acc) {
        while (true) {
          const acc = _acc;
          const i = _i;
          if (i >= arr.length) {
            return Stdlib__List.rev(acc);
          }
          const s = Js__Js_json.decodeString(Caml_array.get(arr, i));
          if (s === undefined) {
            return;
          }
          _acc = {
            hd: s,
            tl: acc
          };
          _i = i + 1 | 0;
          continue;
        };
      };
      citations_opt = to_strs(0, /* [] */ 0);
    } else {
      citations_opt = undefined;
    }
  } else {
    citations_opt = /* [] */ 0;
  }
  if (citations_opt !== undefined) {
    return {
      TAG: /* Decode_ok */ 0,
      _0: {
        e_text: text,
        e_visuals: visuals,
        e_citations: citations_opt
      }
    };
  } else {
    return {
      TAG: /* Decode_err */ 1,
      _0: "citations must be an array"
    };
  }
}

export {
  contains_ci,
  word_at,
  contains_word_ci,
  is_punct,
  standalone_word,
  find_slug_in_text,
  find_task_in_text,
  classify,
  visual,
  make_envelope,
  resolve_task,
  morning_text,
  blocked_citations,
  memory_hit_paths,
  envelope_for,
  is_visual_kind,
  encode_envelope,
  get_field$1 as get_field,
  as_string,
  decode_envelope,
}
/* Melange__Views Not a pure module */
