// Generated by Melange

import * as Melange__Js_shims from "./js_shims.js";

function param(ctx, name) {
  return ctx.req.param(name);
}

function query_default(ctx, name, $$default) {
  const v = ctx.req.query(name);
  if (v !== undefined) {
    return v;
  } else {
    return $$default;
  }
}

function markdown_resp(ctx, body) {
  const headers = Melange__Js_shims.str_obj({
    hd: [
      "content-type",
      "text/markdown; charset=utf-8"
    ],
    tl: /* [] */ 0
  });
  return ctx.text(body, 200, Melange__Js_shims.unsafe_obj({
    hd: [
      "headers",
      headers
    ],
    tl: /* [] */ 0
  }));
}

function request_get_p(app, path) {
  const init = {};
  return Promise.resolve(app.request(path, init));
}

function request_post_p(app, path, body) {
  const headers = Melange__Js_shims.str_obj({
    hd: [
      "content-type",
      "application/json"
    ],
    tl: /* [] */ 0
  });
  const init = {};
  init["method"] = "POST";
  init["headers"] = headers;
  init["body"] = body;
  return Promise.resolve(app.request(path, init));
}

export {
  param,
  query_default,
  markdown_resp,
  request_get_p,
  request_post_p,
}
/* Melange__Js_shims Not a pure module */
