// Generated by Melange

import * as Caml_obj from "melange.js/caml_obj.js";
import * as Curry from "melange.js/curry.js";
import * as Melange__Domain from "./domain.js";
import * as Melange__Markdown from "./markdown.js";
import * as Melange__Speckit from "./speckit.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Stdlib__String from "melange/string.js";

const nav_items = {
  hd: [
    "/",
    "Overview"
  ],
  tl: {
    hd: [
      "/roadmap",
      "Roadmap"
    ],
    tl: {
      hd: [
        "/backlog",
        "Backlog"
      ],
      tl: {
        hd: [
          "/specs",
          "Specs"
        ],
        tl: {
          hd: [
            "/constitution",
            "Constitution"
          ],
          tl: {
            hd: [
              "/graph",
              "Graph"
            ],
            tl: {
              hd: [
                "/memory",
                "Memory"
              ],
              tl: /* [] */ 0
            }
          }
        }
      }
    }
  }
};

function page(title, path, banners, body) {
  const banners$1 = Stdlib__String.concat("", Stdlib__List.map((function (b) {
    return "<div class=\"banner\">" + (b + "</div>");
  }), banners));
  const nav = Stdlib__String.concat("", Stdlib__List.map((function (param) {
    const href = param[0];
    const on = path === href || href !== "/" && Melange__Speckit.starts_with(href, path);
    return Curry._3(Stdlib__Printf.sprintf({
      TAG: /* Format */ 0,
      _0: {
        TAG: /* String_literal */ 11,
        _0: "<a href=\"",
        _1: {
          TAG: /* String */ 2,
          _0: /* No_padding */ 0,
          _1: {
            TAG: /* Char_literal */ 12,
            _0: /* '"' */34,
            _1: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: {
                TAG: /* Char_literal */ 12,
                _0: /* '>' */62,
                _1: {
                  TAG: /* String */ 2,
                  _0: /* No_padding */ 0,
                  _1: {
                    TAG: /* String_literal */ 11,
                    _0: "</a>",
                    _1: /* End_of_format */ 0
                  }
                }
              }
            }
          }
        }
      },
      _1: "<a href=\"%s\"%s>%s</a>"
    }), href, on ? " aria-current=\"page\"" : "", param[1]);
  }), nav_items));
  return Curry._4(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "<!doctype html>\n<html lang=\"en\">\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>",
      _1: {
        TAG: /* String */ 2,
        _0: /* No_padding */ 0,
        _1: {
          TAG: /* String_literal */ 11,
          _0: " \xc2\xb7 Berea</title>\n<link rel=\"stylesheet\" href=\"/static/app.css\">\n<body>\n  <a class=\"skip\" href=\"#main\">Skip to writings</a>\n  <header class=\"mast\">\n    <p class=\"mark\">Berea</p>\n    <p class=\"verse\">They received the word with all readiness of mind, and searched the scriptures daily, whether those things were so.</p>\n  </header>\n  <div class=\"shell\">\n    <nav class=\"rail\">",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: "</nav>\n    <main id=\"main\">\n      ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: "\n      ",
                  _1: {
                    TAG: /* String */ 2,
                    _0: /* No_padding */ 0,
                    _1: {
                      TAG: /* String_literal */ 11,
                      _0: "\n    </main>\n    <aside class=\"ask\" aria-label=\"Ask the writings\">\n      <h2>Ask</h2>\n      <form id=\"chat-form\">\n        <label class=\"sr\" for=\"chat-q\">Question</label>\n        <textarea id=\"chat-q\" name=\"message\" rows=\"3\" placeholder=\"what should we work on?\"></textarea>\n        <button type=\"submit\">Ask</button>\n      </form>\n      <div id=\"chat-out\" class=\"chat-out\" hidden></div>\n    </aside>\n  </div>\n  <script src=\"/static/app.js\" type=\"module\"></script>\n</body>\n</html>",
                      _1: /* End_of_format */ 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    _1: "<!doctype html>\n<html lang=\"en\">\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>%s \xc2\xb7 Berea</title>\n<link rel=\"stylesheet\" href=\"/static/app.css\">\n<body>\n  <a class=\"skip\" href=\"#main\">Skip to writings</a>\n  <header class=\"mast\">\n    <p class=\"mark\">Berea</p>\n    <p class=\"verse\">They received the word with all readiness of mind, and searched the scriptures daily, whether those things were so.</p>\n  </header>\n  <div class=\"shell\">\n    <nav class=\"rail\">%s</nav>\n    <main id=\"main\">\n      %s\n      %s\n    </main>\n    <aside class=\"ask\" aria-label=\"Ask the writings\">\n      <h2>Ask</h2>\n      <form id=\"chat-form\">\n        <label class=\"sr\" for=\"chat-q\">Question</label>\n        <textarea id=\"chat-q\" name=\"message\" rows=\"3\" placeholder=\"what should we work on?\"></textarea>\n        <button type=\"submit\">Ask</button>\n      </form>\n      <div id=\"chat-out\" class=\"chat-out\" hidden></div>\n    </aside>\n  </div>\n  <script src=\"/static/app.js\" type=\"module\"></script>\n</body>\n</html>"
  }), Melange__Markdown.esc(title), nav, banners$1, body);
}

function status_pill(status) {
  return Curry._2(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "<span class=\"pill ",
      _1: {
        TAG: /* String */ 2,
        _0: /* No_padding */ 0,
        _1: {
          TAG: /* String_literal */ 11,
          _0: "\">",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: "</span>",
              _1: /* End_of_format */ 0
            }
          }
        }
      }
    },
    _1: "<span class=\"pill %s\">%s</span>"
  }), Melange__Markdown.esc(status), Melange__Markdown.esc(status));
}

function feature_table(cards, empty) {
  if (Caml_obj.caml_equal(cards, /* [] */ 0)) {
    return "<p class=\"empty\">" + (Melange__Markdown.esc(empty) + "</p>");
  }
  const rows = Stdlib__String.concat("", Stdlib__List.map((function (c) {
    return Curry._7(Stdlib__Printf.sprintf({
      TAG: /* Format */ 0,
      _0: {
        TAG: /* String_literal */ 11,
        _0: "<tr>\n<td><a href=\"/specs/",
        _1: {
          TAG: /* String */ 2,
          _0: /* No_padding */ 0,
          _1: {
            TAG: /* String_literal */ 11,
            _0: "\">",
            _1: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: {
                TAG: /* String_literal */ 11,
                _0: "</a></td>\n<td>",
                _1: {
                  TAG: /* String */ 2,
                  _0: /* No_padding */ 0,
                  _1: {
                    TAG: /* String_literal */ 11,
                    _0: "</td>\n<td>",
                    _1: {
                      TAG: /* String */ 2,
                      _0: /* No_padding */ 0,
                      _1: {
                        TAG: /* String_literal */ 11,
                        _0: "</td>\n<td>",
                        _1: {
                          TAG: /* String */ 2,
                          _0: /* No_padding */ 0,
                          _1: {
                            TAG: /* String_literal */ 11,
                            _0: "</td>\n<td>",
                            _1: {
                              TAG: /* Int */ 4,
                              _0: /* Int_d */ 0,
                              _1: /* No_padding */ 0,
                              _2: /* No_precision */ 0,
                              _3: {
                                TAG: /* Char_literal */ 12,
                                _0: /* '/' */47,
                                _1: {
                                  TAG: /* Int */ 4,
                                  _0: /* Int_d */ 0,
                                  _1: /* No_padding */ 0,
                                  _2: /* No_precision */ 0,
                                  _3: {
                                    TAG: /* String_literal */ 11,
                                    _0: "</td>\n</tr>",
                                    _1: /* End_of_format */ 0
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      _1: "<tr>\n<td><a href=\"/specs/%s\">%s</a></td>\n<td>%s</td>\n<td>%s</td>\n<td>%s</td>\n<td>%d/%d</td>\n</tr>"
    }), Melange__Markdown.esc(c.slug), Melange__Markdown.esc(c.slug), Melange__Markdown.esc(c.title), status_pill(Melange__Domain.status_to_string(c.status)), Melange__Markdown.esc(Melange__Domain.horizon_to_string(c.horizon)), c.open_tasks, c.total_tasks);
  }), cards));
  return "<table>\n<thead><tr><th>ID</th><th>Title</th><th>Status</th><th>Horizon</th><th>Tasks</th></tr></thead>\n<tbody>" + (rows + "</tbody>\n</table>");
}

function task_table(interactiveOpt, items) {
  const interactive = interactiveOpt !== undefined ? interactiveOpt : false;
  if (Caml_obj.caml_equal(items, /* [] */ 0)) {
    return "<p class=\"empty\">No open tasks.</p>";
  }
  const rows = Stdlib__String.concat("", Stdlib__List.map((function (t) {
    const box = interactive ? Curry._2(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "<input type=\"checkbox\" class=\"task-toggle\" data-ref=\"",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* Char_literal */ 12,
              _0: /* '"' */34,
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* Char_literal */ 12,
                  _0: /* '>' */62,
                  _1: /* End_of_format */ 0
                }
              }
            }
          }
        },
        _1: "<input type=\"checkbox\" class=\"task-toggle\" data-ref=\"%s\"%s>"
      }), Melange__Markdown.esc(t.tr_ref), t.tr_done ? " checked" : "") : (
        t.tr_done ? "\xe2\x98\x91" : "\xe2\x98\x90"
      );
    const i = Stdlib__String.index_opt(t.tr_ref, /* '#' */35);
    const anchor = i !== undefined ? Stdlib__String.sub(t.tr_ref, i + 1 | 0, (t.tr_ref.length - i | 0) - 1 | 0) : t.tr_ref;
    return Curry._6(Stdlib__Printf.sprintf({
      TAG: /* Format */ 0,
      _0: {
        TAG: /* String_literal */ 11,
        _0: "<tr id=\"",
        _1: {
          TAG: /* String */ 2,
          _0: /* No_padding */ 0,
          _1: {
            TAG: /* String_literal */ 11,
            _0: "\">\n<td>",
            _1: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: {
                TAG: /* String_literal */ 11,
                _0: "</td>\n<td><code>",
                _1: {
                  TAG: /* String */ 2,
                  _0: /* No_padding */ 0,
                  _1: {
                    TAG: /* String_literal */ 11,
                    _0: "</code></td>\n<td>",
                    _1: {
                      TAG: /* String */ 2,
                      _0: /* No_padding */ 0,
                      _1: {
                        TAG: /* String_literal */ 11,
                        _0: "</td>\n<td><a href=\"/specs/",
                        _1: {
                          TAG: /* String */ 2,
                          _0: /* No_padding */ 0,
                          _1: {
                            TAG: /* String_literal */ 11,
                            _0: "\">",
                            _1: {
                              TAG: /* String */ 2,
                              _0: /* No_padding */ 0,
                              _1: {
                                TAG: /* String_literal */ 11,
                                _0: "</a></td>\n</tr>",
                                _1: /* End_of_format */ 0
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      _1: "<tr id=\"%s\">\n<td>%s</td>\n<td><code>%s</code></td>\n<td>%s</td>\n<td><a href=\"/specs/%s\">%s</a></td>\n</tr>"
    }), Melange__Markdown.esc(anchor), box, Melange__Markdown.esc(t.tr_ref), Melange__Markdown.esc(t.tr_title), Melange__Markdown.esc(t.tr_spec), Melange__Markdown.esc(t.tr_spec));
  }), items));
  return "<table>\n<thead><tr><th></th><th>Ref</th><th>Title</th><th>Spec</th></tr></thead>\n<tbody>" + (rows + "</tbody>\n</table>");
}

function md_article(md) {
  return "<article class=\"prose\">" + (Melange__Markdown.render_markdown(md) + "</article>");
}

function dl(rows) {
  const items = Stdlib__String.concat("", Stdlib__List.map((function (param) {
    return "<div><dt>" + (param[0] + ("</dt><dd>" + (param[1] + "</dd></div>")));
  }), rows));
  return "<dl class=\"facts\">" + (items + "</dl>");
}

const esc = Melange__Markdown.esc;

export {
  esc,
  nav_items,
  page,
  status_pill,
  feature_table,
  task_table,
  md_article,
  dl,
}
/* No side effect */
