// Generated by Melange

import * as Curry from "melange.js/curry.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Paths from "./paths.js";
import * as Melange__Rebuild from "./rebuild.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";

const root = Melange__Paths.resolve_project_root();

const result = Melange__Rebuild.rebuild_all(root);

Melange__Js_shims.Console.log(Curry._2(Stdlib__Printf.sprintf({
  TAG: /* Format */ 0,
  _0: {
    TAG: /* String_literal */ 11,
    _0: "indexed ",
    _1: {
      TAG: /* Int */ 4,
      _0: /* Int_d */ 0,
      _1: /* No_padding */ 0,
      _2: /* No_precision */ 0,
      _3: {
        TAG: /* String_literal */ 11,
        _0: " features, ",
        _1: {
          TAG: /* Int */ 4,
          _0: /* Int_d */ 0,
          _1: /* No_padding */ 0,
          _2: /* No_precision */ 0,
          _3: {
            TAG: /* String_literal */ 11,
            _0: " memory notes",
            _1: /* End_of_format */ 0
          }
        }
      }
    }
  },
  _1: "indexed %d features, %d memory notes"
}), result.rb_features, result.rb_memory_notes));

Stdlib__List.iter((function (e) {
  Melange__Js_shims.Console.warn("parse: " + (e.err_path + (": " + e.err_message)));
}), result.rb_parse_errors);
/* root Not a pure module */
