// Generated by Melange

import * as Caml_option from "melange.js/caml_option.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Option from "melange/option.js";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";

const Str = {};

const of_list = Stdlib__Array.of_list;

const to_list = Stdlib__Array.to_list;

const A = {
  of_list,
  to_list
};

function str_obj(kvs) {
  const o = {};
  Stdlib__List.iter((function (param) {
    o[param[0]] = param[1];
  }), kvs);
  return o;
}

function unsafe_obj(kvs) {
  const o = {};
  Stdlib__List.iter((function (param) {
    o[param[0]] = param[1];
  }), kvs);
  return o;
}

function now_iso(param) {
  return new Date(Date.now()).toISOString();
}

const $$Date$1 = {
  now_iso
};

function env_port(param) {
  return Stdlib__Option.value(Caml_option.undefined_to_opt(process.env["PORT"]), "");
}

function env_spec_root(param) {
  return Stdlib__Option.value(Caml_option.undefined_to_opt(process.env["SPEC_ROOT"]), "");
}

function argv_1(param) {
  if (process.argv.length > 1) {
    return process.argv[1];
  }
  
}

const Process = {
  env_port,
  env_spec_root,
  argv_1
};

const Console = {};

const $$Crypto = {};

const Child_process = {};

function read_file_sync(path) {
  return Nodefs.readFileSync(path, "utf8");
}

function mkdir_p(dir) {
  const opts = {};
  opts["recursive"] = true;
  Nodefs.mkdirSync(dir, opts);
}

function mtime_ms(path) {
  return Nodefs.statSync(path).mtimeMs;
}

function is_dir(path) {
  return Nodefs.statSync(path).isDirectory();
}

const Fs = {
  read_file_sync,
  recursive: true,
  mkdir_p,
  mtime_ms,
  is_dir
};

function join2(a, b) {
  return Nodepath.join(a, b);
}

function join3(a, b, c) {
  return Nodepath.join(a, b, c);
}

function join4(a, b, c, d) {
  return Nodepath.join(a, b, c, d);
}

const Path = {
  join2,
  join3,
  join4
};

const Os = {};

export {
  Str,
  A,
  str_obj,
  unsafe_obj,
  $$Date$1 as $$Date,
  Process,
  Console,
  $$Crypto,
  Child_process,
  Fs,
  Path,
  Os,
}
/* node:fs Not a pure module */
