// Generated by Melange

import * as Caml from "melange.js/caml.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Melange__Domain from "./domain.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Memory_ml from "./memory_ml.js";
import * as Melange__Speckit from "./speckit.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__Float from "melange/float.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printexc from "melange/printexc.js";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";

function missing_constitution(const_path) {
  return {
    present: false,
    const_path,
    const_title: "Constitution",
    const_body: "",
    const_principles: /* [] */ 0
  };
}

function load_constitution(const_path, errs) {
  if (!Nodefs.existsSync(const_path)) {
    return missing_constitution(const_path);
  }
  try {
    const text = Melange__Js_shims.Fs.read_file_sync(const_path);
    const parsed = Melange__Speckit.parse_constitution(text);
    return {
      present: true,
      const_path,
      const_title: parsed.title,
      const_body: parsed.body,
      const_principles: parsed.principles
    };
  }
  catch (raw_e){
    const e = Caml_js_exceptions.internalToOCamlException(raw_e);
    errs.contents = Stdlib.$at(errs.contents, {
      hd: {
        err_path: const_path,
        err_message: Stdlib__Printexc.to_string(e)
      },
      tl: /* [] */ 0
    });
    return missing_constitution(const_path);
  }
}

function is_dir(path) {
  return Melange__Js_shims.Fs.is_dir(path);
}

function load_tree(paths) {
  const errs = {
    contents: /* [] */ 0
  };
  const constitution = load_constitution(paths.constitution, errs);
  if (!Nodefs.existsSync(paths.specs)) {
    return {
      features: /* [] */ 0,
      tree_constitution: constitution,
      parse_errors: errs.contents,
      spec_mtime_ms: 0.0
    };
  }
  const dirs = Stdlib__List.sort(Caml.caml_string_compare, Stdlib__List.filter(Melange__Domain.is_feature_slug, Stdlib__List.filter((function (name) {
    const p = Melange__Js_shims.Path.join2(paths.specs, name);
    try {
      return Melange__Js_shims.Fs.is_dir(p);
    }
    catch (exn){
      return false;
    }
  }), Melange__Js_shims.A.to_list(Nodefs.readdirSync(paths.specs)))));
  const match = Stdlib__List.fold_left((function (param, slug) {
    const errs = param[2];
    const mtime = param[1];
    const features = param[0];
    const dir = Melange__Js_shims.Path.join2(paths.specs, slug);
    const spec_path = Melange__Js_shims.Path.join2(dir, "spec.md");
    if (!Nodefs.existsSync(spec_path)) {
      return [
        features,
        mtime,
        Stdlib.$at(errs, {
          hd: {
            err_path: spec_path,
            err_message: "missing spec.md"
          },
          tl: /* [] */ 0
        })
      ];
    }
    try {
      const spec_md = Melange__Js_shims.Fs.read_file_sync(spec_path);
      const mtime$1 = Stdlib__Float.max(mtime, Melange__Js_shims.Fs.mtime_ms(spec_path));
      const plan_path = Melange__Js_shims.Path.join2(dir, "plan.md");
      const tasks_path = Melange__Js_shims.Path.join2(dir, "tasks.md");
      const plan_md = Nodefs.existsSync(plan_path) ? Melange__Js_shims.Fs.read_file_sync(plan_path) : undefined;
      const mtime$2 = plan_md !== undefined ? Stdlib__Float.max(mtime$1, Melange__Js_shims.Fs.mtime_ms(plan_path)) : mtime$1;
      const tasks_md = Nodefs.existsSync(tasks_path) ? Melange__Js_shims.Fs.read_file_sync(tasks_path) : undefined;
      const mtime$3 = tasks_md !== undefined ? Stdlib__Float.max(mtime$2, Melange__Js_shims.Fs.mtime_ms(tasks_path)) : mtime$2;
      const entries = Melange__Js_shims.A.to_list(Nodefs.readdirSync(dir));
      const siblings = Stdlib__List.filter((function (n) {
        if (n !== "spec.md" && n !== "plan.md") {
          return n !== "tasks.md";
        } else {
          return false;
        }
      }), entries);
      const feature = Melange__Speckit.assemble_feature({
        fi_slug: slug,
        fi_spec_md: spec_md,
        fi_plan_md: plan_md,
        fi_tasks_md: tasks_md,
        fi_siblings: siblings,
        fi_gate_failing: false
      });
      return [
        {
          hd: feature,
          tl: features
        },
        mtime$3,
        errs
      ];
    }
    catch (raw_e){
      const e = Caml_js_exceptions.internalToOCamlException(raw_e);
      return [
        features,
        mtime,
        Stdlib.$at(errs, {
          hd: {
            err_path: spec_path,
            err_message: Stdlib__Printexc.to_string(e)
          },
          tl: /* [] */ 0
        })
      ];
    }
  }), [
    /* [] */ 0,
    0.0,
    errs.contents
  ], dirs);
  return {
    features: Stdlib__List.rev(match[0]),
    tree_constitution: constitution,
    parse_errors: match[2],
    spec_mtime_ms: match[1]
  };
}

function walk_md(dir) {
  const go = function (acc, dir) {
    const entries = Nodefs.readdirSync(dir);
    return Stdlib__Array.fold_left((function (acc, name) {
      const p = Melange__Js_shims.Path.join2(dir, name);
      let tmp;
      try {
        tmp = Melange__Js_shims.Fs.is_dir(p);
      }
      catch (exn){
        tmp = false;
      }
      if (tmp) {
        return go(acc, p);
      } else if (name.endsWith(".md")) {
        return {
          hd: p,
          tl: acc
        };
      } else {
        return acc;
      }
    }), acc, entries);
  };
  return go(/* [] */ 0, dir);
}

function load_memory_notes(include_sessionsOpt, memory_root) {
  const include_sessions = include_sessionsOpt !== undefined ? include_sessionsOpt : false;
  if (!Nodefs.existsSync(memory_root)) {
    return /* [] */ 0;
  }
  const files = walk_md(memory_root);
  return Stdlib__List.filter_map((function (abs) {
    const rel = Nodepath.relative(memory_root, abs);
    const path = "memory/" + rel;
    if (!Melange__Memory_ml.should_index(include_sessions, path)) {
      return;
    }
    const text = Melange__Js_shims.Fs.read_file_sync(abs);
    const note = Melange__Memory_ml.parse_memory_note(path, text);
    return {
      note_path: note.path,
      note_title: note.title,
      note_as_of: note.as_of,
      note_body: note.body,
      note_kind: note.kind
    };
  }), files);
}

export {
  missing_constitution,
  load_constitution,
  is_dir,
  load_tree,
  walk_md,
  load_memory_notes,
}
/* Melange__Js_shims Not a pure module */
