// Generated by Melange

import * as Caml_string from "melange.js/caml_string.js";
import * as Curry from "melange.js/curry.js";
import * as Melange__Speckit from "./speckit.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Buffer from "melange/buffer.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Stdlib__String from "melange/string.js";

function esc(s) {
  const b = Stdlib__Buffer.create(s.length);
  Stdlib__String.iter((function (c) {
    if (c >= 40) {
      switch (c) {
        case 60 :
          return Stdlib__Buffer.add_string(b, "&lt;");
        case 62 :
          return Stdlib__Buffer.add_string(b, "&gt;");
        default:
          return Stdlib__Buffer.add_char(b, c);
      }
    } else {
      if (c < 34) {
        return Stdlib__Buffer.add_char(b, c);
      }
      switch (c) {
        case 34 :
          return Stdlib__Buffer.add_string(b, "&quot;");
        case 35 :
        case 36 :
        case 37 :
          return Stdlib__Buffer.add_char(b, c);
        case 38 :
          return Stdlib__Buffer.add_string(b, "&amp;");
        case 39 :
          return Stdlib__Buffer.add_string(b, "&#39;");
      }
    }
  }), s);
  return Stdlib__Buffer.contents(b);
}

function wiki(ref_) {
  const i = Stdlib__String.index_opt(ref_, /* '#' */35);
  if (i === undefined) {
    return Curry._2(Stdlib__Printf.sprintf({
      TAG: /* Format */ 0,
      _0: {
        TAG: /* String_literal */ 11,
        _0: "<a class=\"wiki\" href=\"/specs/",
        _1: {
          TAG: /* String */ 2,
          _0: /* No_padding */ 0,
          _1: {
            TAG: /* String_literal */ 11,
            _0: "\">",
            _1: {
              TAG: /* String */ 2,
              _0: /* No_padding */ 0,
              _1: {
                TAG: /* String_literal */ 11,
                _0: "</a>",
                _1: /* End_of_format */ 0
              }
            }
          }
        }
      },
      _1: "<a class=\"wiki\" href=\"/specs/%s\">%s</a>"
    }), esc(ref_), esc(ref_));
  }
  const slug = Stdlib__String.sub(ref_, 0, i);
  const task = Stdlib__String.sub(ref_, i + 1 | 0, (ref_.length - i | 0) - 1 | 0);
  return Curry._3(Stdlib__Printf.sprintf({
    TAG: /* Format */ 0,
    _0: {
      TAG: /* String_literal */ 11,
      _0: "<a class=\"wiki\" href=\"/specs/",
      _1: {
        TAG: /* String */ 2,
        _0: /* No_padding */ 0,
        _1: {
          TAG: /* Char_literal */ 12,
          _0: /* '#' */35,
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: "\">",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: "</a>",
                  _1: /* End_of_format */ 0
                }
              }
            }
          }
        }
      }
    },
    _1: "<a class=\"wiki\" href=\"/specs/%s#%s\">%s</a>"
  }), esc(slug), esc(task), esc(ref_));
}

function replace_wiki(s) {
  const b = Stdlib__Buffer.create(s.length);
  const n = s.length;
  const go = function (_i) {
    while (true) {
      const i = _i;
      if (i >= n) {
        return;
      }
      if ((i + 2 | 0) <= n && Caml_string.get(s, i) === /* '[' */91 && Caml_string.get(s, i + 1 | 0) === /* '[' */91) {
        const j = Melange__Speckit.find_from(s, i + 2 | 0, "]]");
        if (j !== undefined) {
          const inner = Melange__Speckit.trim(Stdlib__String.sub(s, i + 2 | 0, (j - i | 0) - 2 | 0));
          Stdlib__Buffer.add_string(b, wiki(inner));
          _i = j + 2 | 0;
          continue;
        }
        Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
        _i = i + 1 | 0;
        continue;
      }
      Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
      _i = i + 1 | 0;
      continue;
    };
  };
  go(0);
  return Stdlib__Buffer.contents(b);
}

function replace_between(open_, close_, wrap, s) {
  const b = Stdlib__Buffer.create(s.length);
  const n = s.length;
  const m = open_.length;
  const go = function (_i) {
    while (true) {
      const i = _i;
      if (i >= n) {
        return;
      }
      if ((i + m | 0) <= n && Stdlib__String.sub(s, i, m) === open_) {
        let close_at = -1;
        let j = i + m | 0;
        while (j < n && close_at === -1) {
          if ((s.length - j | 0) >= close_.length && Stdlib__String.sub(s, j, close_.length) === close_) {
            close_at = j;
          } else {
            j = j + 1 | 0;
          }
        };
        if (close_at > (i + m | 0)) {
          const inner = Stdlib__String.sub(s, i + m | 0, (close_at - i | 0) - m | 0);
          Stdlib__Buffer.add_string(b, Curry._1(wrap, inner));
          _i = close_at + close_.length | 0;
          continue;
        }
        Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
        _i = i + 1 | 0;
        continue;
      }
      Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
      _i = i + 1 | 0;
      continue;
    };
  };
  go(0);
  return Stdlib__Buffer.contents(b);
}

function replace_md_links(s) {
  const b = Stdlib__Buffer.create(s.length);
  const n = s.length;
  const find_close = function (_j) {
    while (true) {
      const j = _j;
      if (j >= n) {
        return -1;
      }
      if (Caml_string.get(s, j) === /* ']' */93) {
        return j;
      }
      if (Caml_string.get(s, j) === /* '[' */91) {
        return -1;
      }
      _j = j + 1 | 0;
      continue;
    };
  };
  const find_paren_end = function (_j) {
    while (true) {
      const j = _j;
      if (j >= n) {
        return -1;
      }
      if (Caml_string.get(s, j) === /* ')' */41) {
        return j;
      }
      _j = j + 1 | 0;
      continue;
    };
  };
  const go = function (_i) {
    while (true) {
      const i = _i;
      if (i >= n) {
        return;
      }
      if (Caml_string.get(s, i) === /* '[' */91) {
        const c = find_close(i + 1 | 0);
        if (c > (i + 1 | 0) && (c + 1 | 0) < n && Caml_string.get(s, c + 1 | 0) === /* '(' */40) {
          const pe = find_paren_end(c + 2 | 0);
          if (pe > (c + 2 | 0)) {
            const text = Stdlib__String.sub(s, i + 1 | 0, (c - i | 0) - 1 | 0);
            const href = Stdlib__String.sub(s, c + 2 | 0, (pe - c | 0) - 2 | 0);
            Stdlib__Buffer.add_string(b, Curry._2(Stdlib__Printf.sprintf({
              TAG: /* Format */ 0,
              _0: {
                TAG: /* String_literal */ 11,
                _0: "<a href=\"",
                _1: {
                  TAG: /* String */ 2,
                  _0: /* No_padding */ 0,
                  _1: {
                    TAG: /* String_literal */ 11,
                    _0: "\">",
                    _1: {
                      TAG: /* String */ 2,
                      _0: /* No_padding */ 0,
                      _1: {
                        TAG: /* String_literal */ 11,
                        _0: "</a>",
                        _1: /* End_of_format */ 0
                      }
                    }
                  }
                }
              },
              _1: "<a href=\"%s\">%s</a>"
            }), href, text));
            _i = pe + 1 | 0;
            continue;
          }
          Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
          _i = i + 1 | 0;
          continue;
        }
        Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
        _i = i + 1 | 0;
        continue;
      }
      Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
      _i = i + 1 | 0;
      continue;
    };
  };
  go(0);
  return Stdlib__Buffer.contents(b);
}

function inline(s) {
  return replace_md_links(replace_between("**", "**", (function (x) {
    return "<strong>" + (x + "</strong>");
  }), replace_between("`", "`", (function (x) {
    return "<code>" + (x + "</code>");
  }), replace_wiki(esc(s)))));
}

function is_blank(line) {
  return Melange__Speckit.trim(line) === "";
}

function is_hr(line) {
  const t = Melange__Speckit.trim(line);
  const n = t.length;
  if (n < 3) {
    return false;
  }
  let _i = 0;
  while (true) {
    const i = _i;
    if (i >= n) {
      return true;
    }
    if (Caml_string.get(t, i) !== /* '-' */45) {
      return false;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function is_table_line(line) {
  const t = Melange__Speckit.trim(line);
  if (t.length >= 2 && Caml_string.get(t, 0) === /* '|' */124 && Caml_string.get(t, t.length - 1 | 0) === /* '|' */124) {
    return Melange__Speckit.contains(t, "|");
  } else {
    return false;
  }
}

function is_list_line(line) {
  const t = Melange__Speckit.trim(line);
  return Melange__Speckit.starts_with("- ", t);
}

function is_task_list_line(line) {
  const t = Melange__Speckit.trim(line);
  if (Melange__Speckit.starts_with("- [", t) && t.length >= 6 && (Caml_string.get(t, 3) === /* ' ' */32 || Caml_string.get(t, 3) === /* 'x' */120 || Caml_string.get(t, 3) === /* 'X' */88)) {
    return Caml_string.get(t, 4) === /* ']' */93;
  } else {
    return false;
  }
}

function is_break(line) {
  if (Melange__Speckit.starts_with("#", line)) {
    return true;
  }
  if (is_list_line(line)) {
    return true;
  }
  if (is_task_list_line(line)) {
    return true;
  }
  if (is_hr(line)) {
    return true;
  }
  const t = Melange__Speckit.trim(line);
  if (t.length !== 0) {
    return Caml_string.get(t, 0) === /* '|' */124;
  } else {
    return false;
  }
}

function is_comment_start(line) {
  return Melange__Speckit.starts_with("<!--", Melange__Speckit.trim(line));
}

function table(ls, start) {
  const collect = function (_i, _rows) {
    while (true) {
      const rows = _rows;
      const i = _i;
      if (!(i < Stdlib__List.length(ls) && is_table_line(Stdlib__List.nth(ls, i)))) {
        return [
          rows,
          i
        ];
      }
      const raw = Melange__Speckit.trim(Stdlib__List.nth(ls, i));
      const inner = Stdlib__String.sub(raw, 1, raw.length - 2 | 0);
      const cells = Stdlib__List.map(Melange__Speckit.trim, Stdlib__String.split_on_char(/* '|' */124, inner));
      const is_sep = Stdlib__List.for_all((function (c) {
        const n = c.length;
        if (n < 1) {
          return false;
        }
        let _j = 0;
        while (true) {
          const j = _j;
          if (j >= n) {
            return true;
          }
          if (!(Caml_string.get(c, j) === /* '-' */45 || Caml_string.get(c, j) === /* ':' */58)) {
            return false;
          }
          _j = j + 1 | 0;
          continue;
        };
      }), cells);
      _rows = is_sep ? rows : Stdlib.$at(rows, {
          hd: cells,
          tl: /* [] */ 0
        });
      _i = i + 1 | 0;
      continue;
    };
  };
  const match = collect(start, /* [] */ 0);
  const next = match[1];
  const rows = match[0];
  if (!rows) {
    return [
      "",
      next
    ];
  }
  const tr = function (tag, cells) {
    return "<tr>" + (Stdlib__String.concat("", Stdlib__List.map((function (c) {
      return Curry._3(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* Char_literal */ 12,
          _0: /* '<' */60,
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* Char_literal */ 12,
              _0: /* '>' */62,
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: "</",
                  _1: {
                    TAG: /* String */ 2,
                    _0: /* No_padding */ 0,
                    _1: {
                      TAG: /* Char_literal */ 12,
                      _0: /* '>' */62,
                      _1: /* End_of_format */ 0
                    }
                  }
                }
              }
            }
          }
        },
        _1: "<%s>%s</%s>"
      }), tag, inline(c), tag);
    }), cells)) + "</tr>");
  };
  const html = "<table>" + (tr("th", rows.hd) + (Stdlib__String.concat("", Stdlib__List.map((function (param) {
    return tr("td", param);
  }), rows.tl)) + "</table>"));
  return [
    html,
    next
  ];
}

function list(ls, start) {
  const collect = function (_i, _items) {
    while (true) {
      const items = _items;
      const i = _i;
      if (i >= Stdlib__List.length(ls)) {
        return [
          items,
          i
        ];
      }
      const line = Stdlib__List.nth(ls, i);
      if (is_task_list_line(line)) {
        const t = Melange__Speckit.trim(line);
        const mark = Caml_string.get(t, 3);
        const rest = Stdlib__String.sub(t, 6, t.length - 6 | 0);
        _items = Stdlib.$at(items, {
          hd: Curry._2(Stdlib__Printf.sprintf({
            TAG: /* Format */ 0,
            _0: {
              TAG: /* String_literal */ 11,
              _0: "<li class=\"task\"><input type=\"checkbox\" disabled ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: {
                  TAG: /* String_literal */ 11,
                  _0: "> ",
                  _1: {
                    TAG: /* String */ 2,
                    _0: /* No_padding */ 0,
                    _1: {
                      TAG: /* String_literal */ 11,
                      _0: "</li>",
                      _1: /* End_of_format */ 0
                    }
                  }
                }
              }
            },
            _1: "<li class=\"task\"><input type=\"checkbox\" disabled %s> %s</li>"
          }), mark !== /* ' ' */32 ? "checked" : "", inline(rest)),
          tl: /* [] */ 0
        });
        _i = i + 1 | 0;
        continue;
      }
      if (!is_list_line(line)) {
        return [
          items,
          i
        ];
      }
      const t$1 = Melange__Speckit.trim(line);
      const rest$1 = Stdlib__String.sub(t$1, 2, t$1.length - 2 | 0);
      _items = Stdlib.$at(items, {
        hd: "<li>" + (inline(rest$1) + "</li>"),
        tl: /* [] */ 0
      });
      _i = i + 1 | 0;
      continue;
    };
  };
  const match = collect(start, /* [] */ 0);
  return [
    "<ul>" + (Stdlib__String.concat("", match[0]) + "</ul>"),
    match[1]
  ];
}

function block(src) {
  const ls = Melange__Speckit.lines_of(src);
  const len = Stdlib__List.length(ls);
  const b = Stdlib__Buffer.create(1024);
  const out = function (html) {
    Stdlib__Buffer.add_string(b, html + "\n");
  };
  const go = function (_i) {
    while (true) {
      const i = _i;
      if (i >= len) {
        return;
      }
      const line = Stdlib__List.nth(ls, i);
      if (Melange__Speckit.starts_with("### ", line)) {
        out("<h3>" + (inline(Stdlib__String.sub(line, 4, line.length - 4 | 0)) + "</h3>"));
        _i = i + 1 | 0;
        continue;
      }
      if (Melange__Speckit.starts_with("## ", line)) {
        out("<h2>" + (inline(Stdlib__String.sub(line, 3, line.length - 3 | 0)) + "</h2>"));
        _i = i + 1 | 0;
        continue;
      }
      if (Melange__Speckit.starts_with("# ", line)) {
        out("<h1>" + (inline(Stdlib__String.sub(line, 2, line.length - 2 | 0)) + "</h1>"));
        _i = i + 1 | 0;
        continue;
      }
      if (is_hr(line)) {
        out("<hr>");
        _i = i + 1 | 0;
        continue;
      }
      if (is_table_line(line)) {
        const match = table(ls, i);
        out(match[0]);
        _i = match[1];
        continue;
      }
      if (is_task_list_line(line) || is_list_line(line)) {
        const match$1 = list(ls, i);
        out(match$1[0]);
        _i = match$1[1];
        continue;
      }
      if (Melange__Speckit.trim(line) === "") {
        _i = i + 1 | 0;
        continue;
      }
      let para = /* [] */ 0;
      let j = i;
      while ((function () {
          let tmp = false;
          if (j < len) {
            const line = Stdlib__List.nth(ls, j);
            tmp = Melange__Speckit.trim(line) !== "" && !is_break(Stdlib__List.nth(ls, j));
          }
          return tmp;
        })()) {
        para = {
          hd: Stdlib__List.nth(ls, j),
          tl: para
        };
        j = j + 1 | 0;
      };
      out("<p>" + (inline(Stdlib__String.concat(" ", Stdlib__List.rev(para))) + "</p>"));
      _i = j;
      continue;
    };
  };
  go(0);
  return Stdlib__Buffer.contents(b);
}

function strip_comments(s) {
  const b = Stdlib__Buffer.create(s.length);
  const n = s.length;
  const go = function (_i) {
    while (true) {
      const i = _i;
      if (i >= n) {
        return;
      }
      if ((i + 4 | 0) <= n && Stdlib__String.sub(s, i, 4) === "<!--") {
        const j = Melange__Speckit.find_from(s, i + 4 | 0, "-->");
        if (j === undefined) {
          return Stdlib__Buffer.add_string(b, Stdlib__String.sub(s, i, n - i | 0));
        }
        _i = j + 3 | 0;
        continue;
      }
      Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
      _i = i + 1 | 0;
      continue;
    };
  };
  go(0);
  return Stdlib__Buffer.contents(b);
}

function split_fences(s) {
  const n = s.length;
  let _i = 0;
  let _acc = /* [] */ 0;
  while (true) {
    const acc = _acc;
    const i = _i;
    if (i >= n) {
      return Stdlib__List.rev(acc);
    }
    const j = Melange__Speckit.find_from(s, i, "```");
    if (j === undefined) {
      return Stdlib__List.rev({
        hd: Stdlib__String.sub(s, i, n - i | 0),
        tl: acc
      });
    }
    const k = Melange__Speckit.find_from(s, j + 3 | 0, "```");
    if (k === undefined) {
      return Stdlib__List.rev({
        hd: Stdlib__String.sub(s, i, n - i | 0),
        tl: acc
      });
    }
    const before = j > i ? ({
        hd: Stdlib__String.sub(s, i, j - i | 0),
        tl: /* [] */ 0
      }) : /* [] */ 0;
    _acc = Stdlib__List.rev_append(before, {
      hd: Stdlib__String.sub(s, j, (k + 3 | 0) - j | 0),
      tl: acc
    });
    _i = k + 3 | 0;
    continue;
  };
}

function fence(part) {
  const n = part.length;
  if (n < 6 || !Melange__Speckit.starts_with("```", part)) {
    return "<pre><code>" + (esc(part) + "</code></pre>");
  }
  const rest = Stdlib__String.sub(part, 3, n - 3 | 0);
  const i = Stdlib__String.index_opt(rest, /* '\n' */10);
  const content = i !== undefined ? Stdlib__String.sub(rest, i + 1 | 0, (rest.length - i | 0) - 1 | 0) : rest;
  const content$1 = Melange__Speckit.ends_with("```", content) ? Stdlib__String.sub(content, 0, content.length - 3 | 0) : content;
  return "<pre><code>" + (esc(content$1) + "</code></pre>");
}

function render_markdown(src) {
  const text = Melange__Speckit.normalize_crlf(strip_comments(src));
  return Stdlib__String.concat("", Stdlib__List.map((function (part) {
    if (Melange__Speckit.starts_with("```", part)) {
      return fence(part);
    } else {
      return block(part);
    }
  }), split_fences(text)));
}

const esc_attr = esc;

export {
  esc,
  esc_attr,
  wiki,
  replace_wiki,
  replace_between,
  replace_md_links,
  inline,
  is_blank,
  is_hr,
  is_table_line,
  is_list_line,
  is_task_list_line,
  is_break,
  is_comment_start,
  table,
  list,
  block,
  strip_comments,
  split_fences,
  fence,
  render_markdown,
}
/* No side effect */
