// Generated by Melange

import * as Caml_string from "melange.js/caml_string.js";
import * as Melange__Speckit from "./speckit.js";
import * as Stdlib__Buffer from "melange/buffer.js";
import * as Stdlib__Option from "melange/option.js";
import * as Stdlib__String from "melange/string.js";

function kind_to_string(param) {
  switch (param) {
    case /* Decision */ 0 :
      return "decision";
    case /* Regression */ 1 :
      return "regression";
    case /* Convention */ 2 :
      return "convention";
    case /* Session */ 3 :
      return "session";
    case /* Other */ 4 :
      return "other";
  }
}

function status_to_string(param) {
  switch (param) {
    case /* Active */ 0 :
      return "active";
    case /* Superseded */ 1 :
      return "superseded";
    case /* Rejected */ 2 :
      return "rejected";
    case /* Proposal */ 3 :
      return "proposal";
  }
}

function status_of_string(param) {
  switch (param) {
    case "active" :
      return /* Active */ 0;
    case "proposal" :
      return /* Proposal */ 3;
    case "rejected" :
      return /* Rejected */ 2;
    case "superseded" :
      return /* Superseded */ 1;
    default:
      return;
  }
}

function status_label(s) {
  if (s !== undefined) {
    return status_to_string(s);
  } else {
    return "unknown";
  }
}

function is_reviewed(note) {
  const match = note.kind;
  const match$1 = note.status;
  switch (match) {
    case /* Session */ 3 :
    case /* Other */ 4 :
      return false;
    default:
      if (match$1 === /* Active */ 0) {
        return true;
      } else {
        return false;
      }
  }
}

function normalize_confidence(v) {
  if (v === undefined) {
    return;
  }
  switch (v) {
    case "high" :
    case "low" :
    case "medium" :
      return v;
    default:
      return;
  }
}

function basename(path) {
  const i = Stdlib__String.rindex_opt(path, /* '/' */47);
  if (i !== undefined) {
    return Stdlib__String.sub(path, i + 1 | 0, (path.length - i | 0) - 1 | 0);
  } else {
    return path;
  }
}

function kind_from_path(path) {
  const match = Stdlib__String.split_on_char(/* '/' */47, path);
  if (!match) {
    return /* Other */ 4;
  }
  if (match.hd !== "memory") {
    return /* Other */ 4;
  }
  const match$1 = match.tl;
  if (!match$1) {
    return /* Other */ 4;
  }
  switch (match$1.hd) {
    case "conventions" :
      return /* Convention */ 2;
    case "decisions" :
      return /* Decision */ 0;
    case "regressions" :
      return /* Regression */ 1;
    case "sessions" :
      return /* Session */ 3;
    default:
      return /* Other */ 4;
  }
}

function is_session_path(path) {
  return kind_from_path(path) === /* Session */ 3;
}

function keep_loaded(include_sessions, note) {
  if (is_reviewed(note)) {
    return true;
  } else if (include_sessions) {
    return note.kind === /* Session */ 3;
  } else {
    return false;
  }
}

function should_index(include_sessionsOpt, path) {
  const include_sessions = include_sessionsOpt !== undefined ? include_sessionsOpt : false;
  if (Melange__Speckit.ends_with(".gitkeep", path) || Melange__Speckit.ends_with("memory/README.md", path) || !Melange__Speckit.ends_with(".md", path)) {
    return false;
  } else {
    return !(kind_from_path(path) === /* Session */ 3 && !include_sessions);
  }
}

function excerpt(nOpt, body) {
  const n = nOpt !== undefined ? nOpt : 240;
  const flat = Melange__Speckit.trim(Stdlib__String.concat(" ", Melange__Speckit.lines_of(body)));
  const b = Stdlib__Buffer.create(flat.length);
  const n_flat = flat.length;
  for (let i = 0; i < n_flat; ++i) {
    const c = Caml_string.get(flat, i);
    if (c === /* '\n' */10 || c === /* '\t' */9 || c === /* '\r' */13) {
      Stdlib__Buffer.add_char(b, /* ' ' */32);
    } else {
      Stdlib__Buffer.add_char(b, c);
    }
  }
  const flat$1 = Stdlib__Buffer.contents(b);
  if (flat$1.length <= n) {
    return flat$1;
  } else {
    return Melange__Speckit.trim(Stdlib__String.sub(flat$1, 0, n)) + "\xe2\x80\xa6";
  }
}

function parse_memory_note(path, text) {
  const match = Melange__Speckit.parse_frontmatter(text);
  const body = match[1];
  const attrs = match[0];
  const status = Stdlib__Option.bind(Melange__Speckit.attr(attrs, "status"), (function (raw) {
    return status_of_string(Stdlib__String.lowercase_ascii(raw));
  }));
  const confidence = normalize_confidence(Stdlib__Option.map(Stdlib__String.lowercase_ascii, Melange__Speckit.attr(attrs, "confidence")));
  const h = Melange__Speckit.first_heading(body);
  let title;
  if (h !== undefined) {
    title = h;
  } else {
    const t = Melange__Speckit.attr(attrs, "title");
    title = t !== undefined ? t : basename(path);
  }
  const v = Melange__Speckit.attr(attrs, "supersedes");
  let tmp;
  tmp = v === "" ? undefined : v;
  const v$1 = Melange__Speckit.attr(attrs, "source");
  let tmp$1;
  tmp$1 = v$1 === "" ? undefined : v$1;
  return {
    path,
    title,
    as_of: Melange__Speckit.attr(attrs, "as_of"),
    supersedes: tmp,
    source: tmp$1,
    confidence,
    status,
    kind: kind_from_path(path),
    body
  };
}

export {
  kind_to_string,
  status_to_string,
  status_of_string,
  status_label,
  is_reviewed,
  normalize_confidence,
  basename,
  kind_from_path,
  is_session_path,
  keep_loaded,
  should_index,
  excerpt,
  parse_memory_note,
}
/* No side effect */
