// Generated by Melange

import * as Caml from "melange.js/caml.js";
import * as Caml_option from "melange.js/caml_option.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Memory_ml from "./memory_ml.js";
import * as Melange__Paths from "./paths.js";
import * as Melange__Speckit from "./speckit.js";
import * as Stdlib__Char from "melange/char.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Seq from "melange/seq.js";
import * as Stdlib__String from "melange/string.js";
import * as Nodefs from "node:fs";

function ping(db) {
  try {
    db.query("SELECT 1").get();
    return true;
  }
  catch (exn){
    return false;
  }
}

function apply_migrations(db) {
  db.run("CREATE TABLE IF NOT EXISTS schema_migrations (\n      id TEXT PRIMARY KEY,\n      applied_at TEXT NOT NULL\n    )");
  const applied = Stdlib__List.map((function (r) {
    return r.id;
  }), Melange__Js_shims.A.to_list(db.query("SELECT id FROM schema_migrations").all()));
  const dir = Melange__Paths.migrations_dir();
  const files = Stdlib__List.sort(Caml.caml_string_compare, Stdlib__List.filter((function (f) {
    return f.endsWith(".sql");
  }), Melange__Js_shims.A.to_list(Nodefs.readdirSync(dir))));
  Stdlib__List.iter((function (file) {
    if (Stdlib__List.mem(file, applied)) {
      return;
    }
    const sql = Melange__Js_shims.Fs.read_file_sync(Melange__Js_shims.Path.join2(dir, file));
    db.exec(sql);
    db.run("INSERT INTO schema_migrations (id, applied_at) VALUES (?, ?)", file, Melange__Js_shims.$$Date.now_iso());
  }), files);
}

function list_pins(db) {
  return Stdlib__List.map((function (r) {
    return {
      pin_ref: r.ref,
      pin_reason: r.reason,
      pin_pinned_at: r.pinned_at
    };
  }), Melange__Js_shims.A.to_list(db.query("SELECT ref, reason, pinned_at FROM pins ORDER BY pinned_at DESC").all()));
}

function upsert_pin(db, ref_, reason) {
  const pinned_at = Melange__Js_shims.$$Date.now_iso();
  db.run("INSERT INTO pins (ref, reason, pinned_at) VALUES (?, ?, ?)\n      ON CONFLICT(ref) DO UPDATE SET reason = excluded.reason, pinned_at = excluded.pinned_at", ref_, reason, pinned_at);
  return {
    pin_ref: ref_,
    pin_reason: reason,
    pin_pinned_at: pinned_at
  };
}

function replace_memory_fts(db, notes) {
  db.run("DELETE FROM memory_fts");
  Stdlib__List.iter((function (n) {
    const s = n.note_as_of;
    db.run("INSERT INTO memory_fts (path, title, body, kind, as_of) VALUES (?, ?, ?, ?, ?)", n.note_path, n.note_title, n.note_body, Melange__Memory_ml.kind_to_string(n.note_kind), s !== undefined ? s : null);
  }), notes);
}

function fts_query(q) {
  const partial_arg = Stdlib__String.to_seq(q);
  const tokens = Stdlib__List.filter((function (t) {
    return t !== "";
  }), Stdlib__String.split_on_char(/* ' ' */32, Stdlib__String.of_seq(function (param) {
    return Stdlib__Seq.filter_map((function (c) {
      const c$1 = Stdlib__Char.lowercase_ascii(c);
      if (c$1 >= /* 'a' */97 && c$1 <= /* 'z' */122 || c$1 >= /* '0' */48 && c$1 <= /* '9' */57 || c$1 > 127) {
        return c$1;
      } else {
        return /* ' ' */32;
      }
    }), partial_arg, param);
  })));
  if (tokens) {
    return Stdlib__String.concat(" OR ", Stdlib__List.map((function (t) {
      return "\"" + (Stdlib__String.concat("", Stdlib__String.split_on_char(/* '"' */34, t)) + "\"");
    }), tokens));
  } else {
    return "\"\"";
  }
}

function search_memory(limitOpt, db, q) {
  const limit = limitOpt !== undefined ? limitOpt : 12;
  const query_str = Melange__Speckit.trim(q);
  if (query_str === "") {
    return /* [] */ 0;
  }
  try {
    return Stdlib__List.map((function (r) {
      return {
        hit_path: r.path,
        hit_title: r.title,
        hit_as_of: Caml_option.undefined_to_opt(r.as_of),
        hit_status: "active",
        hit_excerpt: r.excerpt,
        hit_kind: r.kind
      };
    }), Melange__Js_shims.A.to_list(db.query("SELECT path, title, kind, as_of,\n                   snippet(memory_fts, 2, '', '', '\xe2\x80\xa6', 24) AS excerpt\n            FROM memory_fts\n            WHERE memory_fts MATCH ?\n            LIMIT ?").all(fts_query(query_str), limit)));
  }
  catch (exn){
    return /* [] */ 0;
  }
}

function insert_snapshot(db, summary_md) {
  db.run("INSERT INTO snapshots (id, taken_at, summary_md) VALUES (?, ?, ?)", crypto.randomUUID(), Melange__Js_shims.$$Date.now_iso(), summary_md);
}

function insert_thread(db, id, title) {
  db.run("INSERT OR IGNORE INTO chat_threads (id, title, created_at) VALUES (?, ?, ?)", id, title, Melange__Js_shims.$$Date.now_iso());
}

function insert_message(db, thread_id, role, content_json) {
  db.run("INSERT INTO chat_messages (id, thread_id, role, content_json, created_at) VALUES (?, ?, ?, ?, ?)", crypto.randomUUID(), thread_id, role, content_json, Melange__Js_shims.$$Date.now_iso());
}

export {
  ping,
  apply_migrations,
  list_pins,
  upsert_pin,
  replace_memory_fts,
  fts_query,
  search_memory,
  insert_snapshot,
  insert_thread,
  insert_message,
}
/* Melange__Js_shims Not a pure module */
