// Generated by Melange

import * as Melange__Js_shims from "./js_shims.js";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";

function resolve_project_root(param) {
  const r = Melange__Js_shims.Process.env_spec_root();
  if (r !== "") {
    return Nodepath.resolve(r);
  }
  const cwd = process.cwd();
  const up2 = Nodepath.resolve(cwd, "..", "..");
  if (Nodefs.existsSync(up2) && Nodefs.existsSync(Melange__Js_shims.Path.join2(cwd, "package.json"))) {
    return up2;
  } else {
    return Nodepath.resolve(cwd);
  }
}

function tool_root(param) {
  const script = Melange__Js_shims.Process.argv_1();
  if (script === undefined) {
    return Nodepath.resolve(process.cwd());
  }
  let _dir = Nodepath.dirname(script);
  while (true) {
    const dir = _dir;
    if (Nodefs.existsSync(Melange__Js_shims.Path.join2(dir, "package.json"))) {
      return dir;
    }
    const parent = Nodepath.dirname(dir);
    if (parent === dir) {
      return dir;
    }
    _dir = parent;
    continue;
  };
}

function paths_for(root) {
  const dash = Melange__Js_shims.Path.join2(root, ".dash");
  return {
    root,
    specs: Melange__Js_shims.Path.join2(root, "specs"),
    constitution: Melange__Js_shims.Path.join4(root, ".specify", "memory", "constitution.md"),
    memory: Melange__Js_shims.Path.join2(root, "memory"),
    dash,
    db: Melange__Js_shims.Path.join2(dash, "dash.sqlite"),
    context: Melange__Js_shims.Path.join2(dash, "context"),
    index_md: Melange__Js_shims.Path.join3(root, "specs", "INDEX.md"),
    bootstrap_md: Melange__Js_shims.Path.join2(dash, "BOOTSTRAP.md")
  };
}

function migrations_dir(param) {
  return Melange__Js_shims.Path.join2(tool_root(), "overlay/migrations");
}

function public_dir(param) {
  return Melange__Js_shims.Path.join2(tool_root(), "public");
}

function fixtures_dir(param) {
  return Melange__Js_shims.Path.join2(tool_root(), "fixtures");
}

function constitution_stub(param) {
  return "# Constitution\n\nReplace this stub via `/speckit.constitution`.\n\nUntil then: the writings in `specs/` are the work. SQLite is derived.\nThere is no second backlog.\n";
}

export {
  resolve_project_root,
  tool_root,
  paths_for,
  migrations_dir,
  public_dir,
  fixtures_dir,
  constitution_stub,
}
/* Melange__Js_shims Not a pure module */
