// Generated by Melange

import * as Melange__Context_gen from "./context_gen.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Load_tree from "./load_tree.js";
import * as Melange__Overlay from "./overlay.js";
import * as Melange__Paths from "./paths.js";
import * as Stdlib__List from "melange/list.js";
import * as Bunsqlite from "bun:sqlite";
import * as Nodefs from "node:fs";

function ensure_dash_dir(paths) {
  Melange__Js_shims.Fs.mkdir_p(paths.dash);
  Melange__Js_shims.Fs.mkdir_p(paths.context);
}

function rebuild_all(root) {
  const paths = Melange__Paths.paths_for(root);
  ensure_dash_dir(paths);
  const db = new Bunsqlite.Database(paths.db);
  Melange__Overlay.apply_migrations(db);
  const tree = Melange__Load_tree.load_tree(paths);
  const blocked = Melange__Context_gen.blocked_tasks(tree.features);
  const generated_at = Melange__Js_shims.$$Date.now_iso();
  const summary = Melange__Context_gen.build_summary(tree.features, blocked, generated_at);
  Melange__Js_shims.Fs.mkdir_p(paths.context);
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join2(paths.context, "summary.md"), summary);
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join2(paths.context, "active.md"), Melange__Context_gen.build_active(tree.features));
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join2(paths.context, "blocked.md"), Melange__Context_gen.build_blocked_md(blocked));
  Melange__Js_shims.Fs.write_file_sync(Melange__Js_shims.Path.join2(paths.context, "metrics.md"), Melange__Context_gen.build_metrics_md(tree.features));
  Melange__Js_shims.Fs.mkdir_p(paths.specs);
  Melange__Js_shims.Fs.write_file_sync(paths.index_md, Melange__Context_gen.build_index(tree.features));
  const notes = Melange__Load_tree.load_memory_notes(undefined, paths.memory);
  Melange__Overlay.replace_memory_fts(db, notes);
  Melange__Overlay.insert_snapshot(db, summary);
  return {
    rb_features: Stdlib__List.length(tree.features),
    rb_memory_notes: Stdlib__List.length(notes),
    rb_parse_errors: tree.parse_errors,
    rb_summary: summary,
    rb_generated_at: generated_at
  };
}

function context_age_s(paths) {
  const summary = Melange__Js_shims.Path.join2(paths.context, "summary.md");
  if (!Nodefs.existsSync(summary)) {
    return;
  }
  const age = Date.now() - Melange__Js_shims.Fs.mtime_ms(summary);
  return age / 1000 | 0;
}

function context_is_stale(paths, spec_mtime_ms) {
  const summary = Melange__Js_shims.Path.join2(paths.context, "summary.md");
  if (Nodefs.existsSync(summary)) {
    return spec_mtime_ms > Melange__Js_shims.Fs.mtime_ms(summary) + 1.0;
  } else {
    return true;
  }
}

export {
  ensure_dash_dir,
  rebuild_all,
  context_age_s,
  context_is_stale,
}
/* Melange__Js_shims Not a pure module */
