// Generated by Melange

import * as Curry from "melange.js/curry.js";
import * as Melange__App from "./app.js";
import * as Melange__Js_shims from "./js_shims.js";
import * as Melange__Paths from "./paths.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Printf from "melange/printf.js";

const root = Melange__Paths.resolve_project_root();

const app = Melange__App.create_app(root);

const p = Stdlib.int_of_string_opt(Melange__Js_shims.Process.env_port());

const port = p !== undefined && p > 0 ? p : 8787;

Melange__Js_shims.Console.log(Curry._2(Stdlib__Printf.sprintf({
  TAG: /* Format */ 0,
  _0: {
    TAG: /* String_literal */ 11,
    _0: "Reading surface http://127.0.0.1:",
    _1: {
      TAG: /* Int */ 4,
      _0: /* Int_d */ 0,
      _1: /* No_padding */ 0,
      _2: /* No_precision */ 0,
      _3: {
        TAG: /* String_literal */ 11,
        _0: "  (root ",
        _1: {
          TAG: /* String */ 2,
          _0: /* No_padding */ 0,
          _1: {
            TAG: /* Char_literal */ 12,
            _0: /* ')' */41,
            _1: /* End_of_format */ 0
          }
        }
      }
    }
  },
  _1: "Reading surface http://127.0.0.1:%d  (root %s)"
}), port, root));

const opts = {};

opts["port"] = port;

opts["hostname"] = "0.0.0.0";

opts["fetch"] = (function (req) {
  return app.fetch(req);
});

Bun.serve(opts);
/* root Not a pure module */
