// Generated by Melange

import * as Caml_format from "melange.js/caml_format.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Caml_obj from "melange.js/caml_obj.js";
import * as Caml_string from "melange.js/caml_string.js";
import * as Melange__Domain from "./domain.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Buffer from "melange/buffer.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Option from "melange/option.js";
import * as Stdlib__String from "melange/string.js";

function normalize_crlf(s) {
  const b = Stdlib__Buffer.create(s.length);
  const n = s.length;
  let _i = 0;
  while (true) {
    const i = _i;
    if (i >= n) {
      return Stdlib__Buffer.contents(b);
    }
    if (Caml_string.get(s, i) === /* '\r' */13) {
      if ((i + 1 | 0) < n && Caml_string.get(s, i + 1 | 0) === /* '\n' */10) {
        _i = i + 1 | 0;
        continue;
      }
      Stdlib__Buffer.add_char(b, /* '\n' */10);
      _i = i + 1 | 0;
      continue;
    }
    Stdlib__Buffer.add_char(b, Caml_string.get(s, i));
    _i = i + 1 | 0;
    continue;
  };
}

function lines_of(s) {
  if (s === "") {
    return {
      hd: "",
      tl: /* [] */ 0
    };
  } else {
    let _acc = /* [] */ 0;
    let _i = 0;
    while (true) {
      const i = _i;
      const acc = _acc;
      const j = Stdlib__String.index_from_opt(s, i, /* '\n' */10);
      if (j === undefined) {
        return Stdlib__List.rev({
          hd: Stdlib__String.sub(s, i, s.length - i | 0),
          tl: acc
        });
      }
      _i = j + 1 | 0;
      _acc = {
        hd: Stdlib__String.sub(s, i, j - i | 0),
        tl: acc
      };
      continue;
    };
  }
}

function starts_with(prefix, s) {
  const n = prefix.length;
  if (s.length >= n) {
    return Stdlib__String.sub(s, 0, n) === prefix;
  } else {
    return false;
  }
}

function ends_with(suffix, s) {
  const n = suffix.length;
  const m = s.length;
  if (m >= n) {
    return Stdlib__String.sub(s, m - n | 0, n) === suffix;
  } else {
    return false;
  }
}

function contains(hay, needle) {
  const n = needle.length;
  let _i = 0;
  while (true) {
    const i = _i;
    if ((i + n | 0) > hay.length) {
      return false;
    }
    if (Stdlib__String.sub(hay, i, n) === needle) {
      return true;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function find_from(s, from, needle) {
  const n = s.length;
  const m = needle.length;
  let _i = 0 > from ? 0 : from;
  while (true) {
    const i = _i;
    if ((i + m | 0) > n) {
      return;
    }
    if (Stdlib__String.sub(s, i, m) === needle) {
      return i;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function trim(s) {
  const n = s.length;
  const left = function (_i) {
    while (true) {
      const i = _i;
      if (i >= n) {
        return n;
      }
      const match = Caml_string.get(s, i);
      if (match > 13 || match < 9) {
        if (match !== 32) {
          return i;
        }
        _i = i + 1 | 0;
        continue;
      }
      if (match === 12 || match === 11) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  const right = function (_i) {
    while (true) {
      const i = _i;
      if (i < 0) {
        return -1;
      }
      const match = Caml_string.get(s, i);
      if (match > 13 || match < 9) {
        if (match !== 32) {
          return i;
        }
        _i = i - 1 | 0;
        continue;
      }
      if (match === 12 || match === 11) {
        return i;
      }
      _i = i - 1 | 0;
      continue;
    };
  };
  const l = left(0);
  const r = right(n - 1 | 0);
  if (l > r) {
    return "";
  } else {
    return Stdlib__String.sub(s, l, (r - l | 0) + 1 | 0);
  }
}

function is_space(c) {
  if (c === /* ' ' */32) {
    return true;
  } else {
    return c === /* '\t' */9;
  }
}

function strip_bom(s) {
  if (s.length >= 3 && Stdlib__String.sub(s, 0, 3) === "\xef\xbb\xbf") {
    return Stdlib__String.sub(s, 3, s.length - 3 | 0);
  } else {
    return s;
  }
}

function unquote(value) {
  const n = value.length;
  if (n >= 2 && (Caml_string.get(value, 0) === /* '"' */34 && Caml_string.get(value, n - 1 | 0) === /* '"' */34 || Caml_string.get(value, 0) === /* '\'' */39 && Caml_string.get(value, n - 1 | 0) === /* '\'' */39)) {
    return Stdlib__String.sub(value, 1, n - 2 | 0);
  } else {
    return value;
  }
}

function parse_simple_yaml(yaml) {
  return Stdlib__List.filter_map((function (raw) {
    const line = trim(raw);
    if (line === "" || starts_with("#", line)) {
      return;
    }
    const c = Stdlib__String.index_opt(line, /* ':' */58);
    if (c === undefined) {
      return;
    }
    if (c === 0) {
      return;
    }
    const k = trim(Stdlib__String.sub(line, 0, c));
    const v = unquote(trim(Stdlib__String.sub(line, c + 1 | 0, (line.length - c | 0) - 1 | 0)));
    if (k === "") {
      return;
    } else {
      return [
        k,
        v
      ];
    }
  }), lines_of(yaml));
}

function attr(attrs, key) {
  try {
    return Stdlib__List.assoc(key, attrs);
  }
  catch (raw_exn){
    const exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.MEL_EXN_ID === Stdlib.Not_found) {
      return;
    }
    throw exn;
  }
}

function parse_frontmatter(text) {
  const src = normalize_crlf(strip_bom(text));
  if (!starts_with("---", src)) {
    return [
      /* [] */ 0,
      src
    ];
  }
  const after = Stdlib__String.sub(src, 3, src.length - 3 | 0);
  const n = after.length;
  const opens_ok = n === 0 || Caml_string.get(after, 0) === /* '\n' */10;
  const find_end = function (_i) {
    while (true) {
      const i = _i;
      if (i >= n) {
        return;
      }
      if (Caml_string.get(after, i) === /* '\n' */10) {
        const rest_start = i + 1 | 0;
        if ((rest_start + 3 | 0) <= n && Stdlib__String.sub(after, rest_start, 3) === "---") {
          let j = rest_start + 3 | 0;
          while (j < n && (Caml_string.get(after, j) === /* ' ' */32 || Caml_string.get(after, j) === /* '\t' */9)) {
            j = j + 1 | 0;
          };
          if (j >= n || Caml_string.get(after, j) === /* '\n' */10) {
            return i;
          }
          _i = i + 1 | 0;
          continue;
        }
        _i = i + 1 | 0;
        continue;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  if (!opens_ok) {
    return [
      /* [] */ 0,
      src
    ];
  }
  const end_i = find_end(0);
  if (end_i === undefined) {
    return [
      /* [] */ 0,
      src
    ];
  }
  const yaml = Stdlib__String.sub(after, 0, end_i);
  const yaml$1 = yaml !== "" && Caml_string.get(yaml, 0) === /* '\n' */10 ? Stdlib__String.sub(yaml, 1, yaml.length - 1 | 0) : yaml;
  const rest_start = end_i + 1 | 0;
  const rest = Stdlib__String.sub(after, rest_start, n - rest_start | 0);
  const rest$1 = Stdlib__String.sub(rest, 3, rest.length - 3 | 0);
  const rest$2 = rest$1 !== "" && Caml_string.get(rest$1, 0) === /* '\n' */10 ? Stdlib__String.sub(rest$1, 1, rest$1.length - 1 | 0) : rest$1;
  return [
    parse_simple_yaml(yaml$1),
    rest$2
  ];
}

function first_heading(markdown) {
  return Stdlib__List.find_map((function (line) {
    if (!starts_with("# ", line)) {
      return;
    }
    const rest = trim(Stdlib__String.sub(line, 2, line.length - 2 | 0));
    if (rest === "") {
      return;
    } else {
      return rest;
    }
  }), lines_of(markdown));
}

function is_heading_1_3(line) {
  const n = line.length;
  const hashes = function (_i) {
    while (true) {
      const i = _i;
      if (!(i < n && Caml_string.get(line, i) === /* '#' */35)) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  const h = hashes(0);
  if (h >= 1 && h <= 3 && h < n) {
    return Caml_string.get(line, h) === /* ' ' */32;
  } else {
    return false;
  }
}

function contains_word_ci(hay, needle) {
  return contains(Stdlib__String.lowercase_ascii(hay), needle);
}

function parse_constitution(text) {
  const match = parse_frontmatter(text);
  const body = match[1];
  const title = Stdlib__Option.value(first_heading(body), "Constitution");
  const principles = Stdlib__List.filter_map((function (line) {
    if (starts_with("## ", line)) {
      return trim(Stdlib__String.sub(line, 3, line.length - 3 | 0));
    }
    
  }), lines_of(body));
  return {
    title,
    body,
    principles
  };
}

function has_fail_word(s) {
  const n = s.length;
  let _i = 0;
  while (true) {
    const i = _i;
    if ((i + 4 | 0) > n) {
      return false;
    }
    if (Stdlib__String.sub(s, i, 4) === "FAIL") {
      const before_ok = i === 0 || !Melange__Domain.is_word_char(Caml_string.get(s, i - 1 | 0));
      const after_i = i + 4 | 0;
      const after_ok = after_i >= n || !Melange__Domain.is_word_char(Caml_string.get(s, after_i));
      if (before_ok && after_ok) {
        return true;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function constitution_gate_failing(plan_md) {
  if (plan_md === undefined) {
    return false;
  }
  const is_constitution_check = function (line) {
    if (is_heading_1_3(line) && contains(Stdlib__String.lowercase_ascii(line), "constitution")) {
      return contains(Stdlib__String.lowercase_ascii(line), "check");
    } else {
      return false;
    }
  };
  let _in_section = false;
  let _param = lines_of(plan_md);
  while (true) {
    const param = _param;
    const in_section = _in_section;
    if (!param) {
      return false;
    }
    const rest = param.tl;
    const line = param.hd;
    if (is_constitution_check(line)) {
      _param = rest;
      _in_section = true;
      continue;
    }
    if (in_section && is_heading_1_3(line)) {
      _param = rest;
      _in_section = false;
      continue;
    }
    if (in_section) {
      if (has_fail_word(line)) {
        return true;
      }
      if (starts_with("- [ ]", trim(line))) {
        return true;
      }
      _param = rest;
      continue;
    }
    _param = rest;
    _in_section = false;
    continue;
  };
}

function parse_task_id(s, i) {
  const n = s.length;
  if (!(i < n && Caml_string.get(s, i) === /* 'T' */84)) {
    return;
  }
  const digits = function (_j) {
    while (true) {
      const j = _j;
      if (!(j < n && Melange__Domain.is_digit(Caml_string.get(s, j)))) {
        return j;
      }
      _j = j + 1 | 0;
      continue;
    };
  };
  const j = digits(i + 1 | 0);
  if (j > (i + 1 | 0)) {
    return [
      Stdlib__String.sub(s, i, j - i | 0),
      j
    ];
  }
  
}

function parse_task_line(line, _spec_slug, _phase) {
  const n = line.length;
  const skip_ws = function (_i) {
    while (true) {
      const i = _i;
      if (!(i < n && is_space(Caml_string.get(line, i)))) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  const i = skip_ws(0);
  if (!(i < n && Caml_string.get(line, i) === /* '-' */45)) {
    return;
  }
  const after_dash = skip_ws(i + 1 | 0);
  if (!((after_dash + 2 | 0) < n && Caml_string.get(line, after_dash) === /* '[' */91 && (Caml_string.get(line, after_dash + 1 | 0) === /* ' ' */32 || Caml_string.get(line, after_dash + 1 | 0) === /* 'x' */120 || Caml_string.get(line, after_dash + 1 | 0) === /* 'X' */88) && Caml_string.get(line, after_dash + 2 | 0) === /* ']' */93)) {
    return;
  }
  const mark = Caml_string.get(line, after_dash + 1 | 0);
  const after_bracket = skip_ws(after_dash + 3 | 0);
  const match = parse_task_id(line, after_bracket);
  if (match === undefined) {
    return;
  }
  const after_id = match[1];
  if (!(after_id < n && is_space(Caml_string.get(line, after_id)))) {
    return;
  }
  const rest = Stdlib__String.sub(line, after_id, n - after_id | 0);
  return [
    match[0],
    mark !== /* ' ' */32,
    rest
  ];
}

function is_t_tag(s) {
  const n = s.length;
  if (n < 2) {
    return false;
  }
  if (Caml_string.get(s, 0) !== /* 'T' */84) {
    return false;
  }
  let _i = 1;
  while (true) {
    const i = _i;
    if (i >= n) {
      return true;
    }
    if (!Melange__Domain.is_digit(Caml_string.get(s, i))) {
      return false;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function split_tag_value(s) {
  const n = s.length;
  const go = function (_i, _cur, _acc) {
    while (true) {
      const acc = _acc;
      const cur = _cur;
      const i = _i;
      if (i >= n) {
        return Stdlib__List.rev(cur === "" ? acc : ({
            hd: cur,
            tl: acc
          }));
      }
      if (Melange__Domain.is_digit(Caml_string.get(s, i)) || Caml_string.get(s, i) === /* 'T' */84 || Caml_string.get(s, i) === /* ',' */44 || is_space(Caml_string.get(s, i))) {
        _cur = cur + Stdlib__String.make(1, Caml_string.get(s, i));
        _i = i + 1 | 0;
        continue;
      }
      _acc = cur === "" ? acc : ({
          hd: cur,
          tl: acc
        });
      _cur = "";
      _i = i + 1 | 0;
      continue;
    };
  };
  return Stdlib__List.filter(is_t_tag, go(0, "", /* [] */ 0));
}

function find_keyword_ci(s, kw) {
  const low = Stdlib__String.lowercase_ascii(s);
  const n = low.length;
  const m = kw.length;
  let _i = 0;
  while (true) {
    const i = _i;
    if ((i + m | 0) > n) {
      return -1;
    }
    if (Stdlib__String.sub(low, i, m) === kw) {
      const before_ok = i === 0 || !Melange__Domain.is_word_char(Caml_string.get(low, i - 1 | 0));
      const after_i = i + m | 0;
      const after_ok = after_i >= n || !Melange__Domain.is_word_char(Caml_string.get(low, after_i));
      if (before_ok && after_ok) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function take_keyword_tag(s, kw) {
  const i = find_keyword_ci(s, kw);
  if (i === -1) {
    return;
  }
  if (i === 0) {
    return;
  }
  const back = function (_j) {
    while (true) {
      const j = _j;
      if (!(j > 0 && is_space(Caml_string.get(s, j - 1 | 0)))) {
        return j;
      }
      _j = j - 1 | 0;
      continue;
    };
  };
  const ws_start = back(i);
  if (ws_start === i) {
    return;
  } else {
    return [
      ws_start,
      i
    ];
  }
}

function drop_range(s, from, upto) {
  return Stdlib__String.sub(s, 0, from) + Stdlib__String.sub(s, upto, s.length - upto | 0);
}

function parse_task_rest(raw) {
  const s0 = trim(raw);
  const n0 = s0.length;
  const match = starts_with("[P]", s0) ? [
      trim(Stdlib__String.sub(s0, 3, n0 - 3 | 0)),
      true
    ] : [
      s0,
      false
    ];
  const s1 = match[0];
  const n = s1.length;
  let match$1;
  if (n >= 4 && Caml_string.get(s1, 0) === /* '[' */91 && (Caml_string.get(s1, 1) === /* 'U' */85 || Caml_string.get(s1, 1) === /* 'u' */117) && Caml_string.get(s1, 2) === /* 'S' */83) {
    const digits = function (_i) {
      while (true) {
        const i = _i;
        if (!(i < n && Melange__Domain.is_digit(Caml_string.get(s1, i)))) {
          return i;
        }
        _i = i + 1 | 0;
        continue;
      };
    };
    const j = digits(3);
    match$1 = j < n && Caml_string.get(s1, j) === /* ']' */93 ? [
        trim(Stdlib__String.sub(s1, j + 1 | 0, (n - j | 0) - 1 | 0)),
        "US" + Stdlib__String.sub(s1, 3, j - 3 | 0)
      ] : [
        s1,
        undefined
      ];
  } else {
    match$1 = [
      s1,
      undefined
    ];
  }
  const s2 = match$1[0];
  const match$2 = take_keyword_tag(s2, "depends_on:");
  let match$3;
  if (match$2 !== undefined) {
    const after = match$2[1] + 11 | 0;
    const n$1 = s2.length;
    const value_end = function (_j) {
      while (true) {
        const j = _j;
        if (!(j < n$1 && (Melange__Domain.is_digit(Caml_string.get(s2, j)) || Caml_string.get(s2, j) === /* 'T' */84 || Caml_string.get(s2, j) === /* ',' */44 || is_space(Caml_string.get(s2, j))))) {
          return j;
        }
        _j = j + 1 | 0;
        continue;
      };
    };
    const vend = value_end(after);
    const value = Stdlib__String.sub(s2, after, vend - after | 0);
    match$3 = [
      trim(drop_range(s2, match$2[0], vend)),
      split_tag_value(value)
    ];
  } else {
    match$3 = [
      s2,
      /* [] */ 0
    ];
  }
  const take_number_tag = function (s, kw) {
    const match = take_keyword_tag(s, kw);
    if (match === undefined) {
      return [
        s,
        undefined
      ];
    }
    const after = match[1] + kw.length | 0;
    const n = s.length;
    const digits = function (_j) {
      while (true) {
        const j = _j;
        if (!(j < n && Melange__Domain.is_digit(Caml_string.get(s, j)))) {
          return j;
        }
        _j = j + 1 | 0;
        continue;
      };
    };
    const vend = digits(after);
    if (vend > after) {
      return [
        trim(drop_range(s, match[0], vend)),
        Caml_format.caml_int_of_string(Stdlib__String.sub(s, after, vend - after | 0))
      ];
    } else {
      return [
        s,
        undefined
      ];
    }
  };
  const match$4 = take_number_tag(match$3[0], "points:");
  const match$5 = take_number_tag(match$4[0], "rank:");
  const s5 = match$5[0];
  const match$6 = take_keyword_tag(s5, "priority:");
  let match$7;
  if (match$6 !== undefined) {
    const after$1 = match$6[1] + 9 | 0;
    const low = Stdlib__String.lowercase_ascii(Stdlib__String.sub(s5, after$1, s5.length - after$1 | 0));
    const w = Stdlib__List.find_opt((function (w) {
      return starts_with(w, low);
    }), {
      hd: "critical",
      tl: {
        hd: "high",
        tl: {
          hd: "medium",
          tl: {
            hd: "low",
            tl: /* [] */ 0
          }
        }
      }
    });
    if (w !== undefined) {
      const vend$1 = after$1 + w.length | 0;
      match$7 = [
        trim(drop_range(s5, match$6[0], vend$1)),
        Melange__Domain.priority_of_string(w)
      ];
    } else {
      match$7 = [
        s5,
        undefined
      ];
    }
  } else {
    match$7 = [
      s5,
      undefined
    ];
  }
  const s6 = match$7[0];
  const match$8 = take_keyword_tag(s6, "status:");
  let match$9;
  if (match$8 !== undefined) {
    const after$2 = match$8[1] + 7 | 0;
    const n$2 = s6.length;
    const nonspace = function (_j) {
      while (true) {
        const j = _j;
        if (!(j < n$2 && !is_space(Caml_string.get(s6, j)))) {
          return j;
        }
        _j = j + 1 | 0;
        continue;
      };
    };
    const vend$2 = nonspace(after$2);
    match$9 = vend$2 > after$2 ? [
        trim(drop_range(s6, match$8[0], vend$2)),
        Stdlib__String.sub(s6, after$2, vend$2 - after$2 | 0)
      ] : [
        s6,
        undefined
      ];
  } else {
    match$9 = [
      s6,
      undefined
    ];
  }
  const status1 = match$9[1];
  const t = trim(match$9[0]);
  const n$3 = t.length;
  let match$10;
  if (ends_with(")", t) && n$3 >= 3) {
    const open_paren = function (_i) {
      while (true) {
        const i = _i;
        if (!(i >= 0 && Caml_string.get(t, i) !== /* '(' */40)) {
          return i;
        }
        _i = i - 1 | 0;
        continue;
      };
    };
    const op = open_paren(n$3 - 2 | 0);
    if (op > 0 && is_space(Caml_string.get(t, op - 1 | 0))) {
      const inner = Stdlib__String.lowercase_ascii(Stdlib__String.sub(t, op + 1 | 0, (n$3 - op | 0) - 2 | 0));
      match$10 = inner === "blocked" || inner === "waiting" || inner === "done" ? [
          trim(Stdlib__String.sub(t, 0, op - 1 | 0)),
          inner
        ] : [
          t,
          undefined
        ];
    } else {
      match$10 = [
        t,
        undefined
      ];
    }
  } else {
    match$10 = [
      t,
      undefined
    ];
  }
  const paren_status = match$10[1];
  const status_tag = status1 !== undefined ? status1 : (
      paren_status !== undefined ? paren_status : undefined
    );
  return {
    tr_parallel: match[1],
    tr_story: match$1[1],
    tr_title: trim(match$10[0]),
    tr_depends_on: match$3[1],
    tr_points: match$4[1],
    tr_rank: match$5[1],
    tr_priority: match$7[1],
    tr_status_tag: status_tag
  };
}

function dedup_add(x, xs) {
  if (Stdlib__List.mem(x, xs)) {
    return xs;
  } else {
    return Stdlib.$at(xs, {
      hd: x,
      tl: /* [] */ 0
    });
  }
}

function with_inferred_deps(tasks) {
  const go = function (prev_phase_ids, phase, last_sequential, current_phase_ids, first_wave, param) {
    if (!param) {
      return /* [] */ 0;
    }
    const t = param.hd;
    const match = Caml_obj.caml_notequal(t.phase, phase) ? [
        current_phase_ids,
        t.phase,
        undefined,
        /* [] */ 0,
        true
      ] : [
        prev_phase_ids,
        phase,
        last_sequential,
        current_phase_ids,
        first_wave
      ];
    const first_wave$1 = match[4];
    const last_seq = match[2];
    const prev = match[0];
    const deps = Stdlib__List.fold_left((function (acc, d) {
      return dedup_add(d, acc);
    }), t.depends_on, /* [] */ 0);
    const deps$1 = first_wave$1 && Caml_obj.caml_notequal(prev, /* [] */ 0) ? Stdlib__List.fold_left((function (acc, id) {
        return dedup_add(id, acc);
      }), deps, prev) : deps;
    const deps$2 = last_seq !== undefined ? dedup_add(last_seq, deps$1) : deps$1;
    const current_ids = Stdlib.$at(match[3], {
      hd: t.id,
      tl: /* [] */ 0
    });
    const last_seq$1 = t.parallel ? last_seq : t.id;
    const first_wave$2 = t.parallel ? first_wave$1 : false;
    return {
      hd: {
        id: t.id,
        title: t.title,
        is_done: t.is_done,
        parallel: t.parallel,
        story: t.story,
        points: t.points,
        rank: t.rank,
        priority: t.priority,
        status_tag: t.status_tag,
        phase: t.phase,
        spec_slug: t.spec_slug,
        depends_on: deps$2,
        body: t.body,
        line: t.line
      },
      tl: go(prev, match[1], last_seq$1, current_ids, first_wave$2, param.tl)
    };
  };
  return go(/* [] */ 0, undefined, undefined, /* [] */ 0, true, tasks);
}

function parse_tasks_markdown(text, spec_slug) {
  const src = normalize_crlf(text);
  const ls = lines_of(src);
  const parsed = Stdlib__List.mapi((function (idx, line) {
    const phase = starts_with("## ", line) ? trim(Stdlib__String.sub(line, 3, line.length - 3 | 0)) : undefined;
    return [
      phase,
      line,
      idx + 1 | 0
    ];
  }), ls);
  const walk = function (_current_phase, _acc, _param) {
    while (true) {
      const param = _param;
      const acc = _acc;
      const current_phase = _current_phase;
      if (!param) {
        return Stdlib__List.rev(acc);
      }
      const rest = param.tl;
      const match = param.hd;
      const phase_opt = match[0];
      const phase = phase_opt !== undefined ? phase_opt : current_phase;
      const match$1 = parse_task_line(match[1], spec_slug, phase);
      if (match$1 !== undefined) {
        const r = parse_task_rest(match$1[2]);
        const t_id = match$1[0];
        const t_title = r.tr_title;
        const t_is_done = match$1[1];
        const t_parallel = r.tr_parallel;
        const t_story = r.tr_story;
        const t_points = r.tr_points;
        const t_rank = r.tr_rank;
        const t_priority = r.tr_priority;
        const t_status_tag = r.tr_status_tag;
        const t_depends_on = r.tr_depends_on;
        const t_body = r.tr_title;
        const t_line = match[2];
        const t = {
          id: t_id,
          title: t_title,
          is_done: t_is_done,
          parallel: t_parallel,
          story: t_story,
          points: t_points,
          rank: t_rank,
          priority: t_priority,
          status_tag: t_status_tag,
          phase,
          spec_slug,
          depends_on: t_depends_on,
          body: t_body,
          line: t_line
        };
        _param = rest;
        _acc = {
          hd: t,
          tl: acc
        };
        _current_phase = phase;
        continue;
      }
      _param = rest;
      _current_phase = phase;
      continue;
    };
  };
  const tasks = with_inferred_deps(walk(undefined, /* [] */ 0, parsed));
  const edges = Stdlib__List.concat_map((function (t) {
    return Stdlib__List.map((function (dep) {
      return {
        edge_from: Melange__Domain.make_ref(spec_slug, dep),
        edge_to: Melange__Domain.make_ref(spec_slug, t.id),
        edge_kind: "depends"
      };
    }), t.depends_on);
  }), tasks);
  return {
    tasks,
    edges
  };
}

function extract_wiki_links(markdown) {
  const n = markdown.length;
  let _i = 0;
  let _acc = /* [] */ 0;
  while (true) {
    const acc = _acc;
    const i = _i;
    if ((i + 4 | 0) > n) {
      return Stdlib__List.rev(acc);
    }
    if (Caml_string.get(markdown, i) === /* '[' */91 && Caml_string.get(markdown, i + 1 | 0) === /* '[' */91) {
      const j = Stdlib__String.index_from_opt(markdown, i + 2 | 0, /* ']' */93);
      if (j !== undefined) {
        if ((j + 1 | 0) < n && Caml_string.get(markdown, j + 1 | 0) === /* ']' */93) {
          const inner = trim(Stdlib__String.sub(markdown, i + 2 | 0, (j - i | 0) - 2 | 0));
          const r = Melange__Domain.parse_ref(inner);
          const match = r.slug;
          const acc$1 = match !== undefined ? ({
              hd: r,
              tl: acc
            }) : acc;
          _acc = acc$1;
          _i = j + 2 | 0;
          continue;
        }
        _i = i + 1 | 0;
        continue;
      }
      _i = i + 1 | 0;
      continue;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function derive_feature_status(gate, plan_md, tasks) {
  if (gate) {
    return /* Blocked */ 4;
  }
  const has_plan = plan_md !== undefined ? plan_md.length !== 0 : false;
  if (!has_plan) {
    return /* Specified */ 0;
  }
  if (Caml_obj.caml_equal(tasks, /* [] */ 0)) {
    return /* Planned */ 1;
  }
  const done_n = Stdlib__List.fold_left((function (n, t) {
    if (t.is_done) {
      return n + 1 | 0;
    } else {
      return n;
    }
  }), 0, tasks);
  if (done_n === Stdlib__List.length(tasks)) {
    return /* Done */ 3;
  } else if (done_n === 0) {
    return /* Planned */ 1;
  } else {
    return /* In_progress */ 2;
  }
}

function infer_horizon(explicit, status) {
  switch (status) {
    case /* Specified */ 0 :
    case /* Planned */ 1 :
      if (explicit !== undefined) {
        return explicit;
      } else {
        return /* Next */ 1;
      }
    case /* Done */ 3 :
      return /* Later */ 2;
    case /* In_progress */ 2 :
    case /* Blocked */ 4 :
      if (explicit !== undefined) {
        return explicit;
      } else {
        return /* Now */ 0;
      }
  }
}

function assemble_feature(input) {
  const match = parse_frontmatter(input.fi_spec_md);
  const spec_body = match[1];
  const attrs = match[0];
  const title = Stdlib__Option.value(first_heading(spec_body), input.fi_slug);
  const horizon = Stdlib__Option.bind(Stdlib__Option.map(Stdlib__String.lowercase_ascii, attr(attrs, "horizon")), Melange__Domain.horizon_of_string);
  const priority = Stdlib__Option.bind(Stdlib__Option.map(Stdlib__String.lowercase_ascii, attr(attrs, "priority")), Melange__Domain.priority_of_string);
  const wiki_links = extract_wiki_links(input.fi_spec_md);
  const md = input.fi_tasks_md;
  const parsed_tasks = md !== undefined ? parse_tasks_markdown(md, input.fi_slug).tasks : /* [] */ 0;
  const gate = input.fi_gate_failing || constitution_gate_failing(input.fi_plan_md);
  const status = derive_feature_status(gate, input.fi_plan_md, parsed_tasks);
  const inferred_horizon = infer_horizon(horizon, status);
  return {
    slug: input.fi_slug,
    title,
    horizon,
    priority,
    spec_md: spec_body,
    spec_raw: input.fi_spec_md,
    plan_md: input.fi_plan_md,
    tasks_md: input.fi_tasks_md,
    tasks: parsed_tasks,
    constitution_gate_failing: gate,
    siblings: input.fi_siblings,
    wiki_links,
    status,
    inferred_horizon
  };
}

function set_task_checkbox(markdown, task_id, done_) {
  const src = normalize_crlf(markdown);
  const ls = lines_of(src);
  const try_line = function (line) {
    const n = line.length;
    const skip_ws = function (_i) {
      while (true) {
        const i = _i;
        if (!(i < n && is_space(Caml_string.get(line, i)))) {
          return i;
        }
        _i = i + 1 | 0;
        continue;
      };
    };
    const i = skip_ws(0);
    if (!(i < n && Caml_string.get(line, i) === /* '-' */45)) {
      return;
    }
    const after_dash = skip_ws(i + 1 | 0);
    if (!((after_dash + 2 | 0) < n && Caml_string.get(line, after_dash) === /* '[' */91 && (Caml_string.get(line, after_dash + 1 | 0) === /* ' ' */32 || Caml_string.get(line, after_dash + 1 | 0) === /* 'x' */120 || Caml_string.get(line, after_dash + 1 | 0) === /* 'X' */88) && Caml_string.get(line, after_dash + 2 | 0) === /* ']' */93)) {
      return;
    }
    const after_bracket = skip_ws(after_dash + 3 | 0);
    if (!((line.length - after_bracket | 0) >= task_id.length && Stdlib__String.sub(line, after_bracket, task_id.length) === task_id)) {
      return;
    }
    const after_id = after_bracket + task_id.length | 0;
    const boundary_ok = after_id >= n || !Melange__Domain.is_word_char(Caml_string.get(line, after_id));
    if (boundary_ok) {
      return after_dash + 1 | 0;
    }
    
  };
  const find = function (_param) {
    while (true) {
      const param = _param;
      if (!param) {
        return;
      }
      const idx = try_line(param.hd);
      if (idx !== undefined) {
        return idx;
      }
      _param = param.tl;
      continue;
    };
  };
  const mark_index = find(ls);
  if (mark_index === undefined) {
    return {
      TAG: /* Error */ 1,
      _0: "task " + (task_id + " not found")
    };
  }
  const replaced = {
    contents: false
  };
  const rewritten = Stdlib__List.map((function (line) {
    if (replaced.contents) {
      return line;
    }
    const idx = try_line(line);
    if (idx === undefined) {
      return line;
    }
    const mark = done_ ? /* 'x' */120 : /* ' ' */32;
    replaced.contents = true;
    return Stdlib__String.sub(line, 0, idx) + (Stdlib__String.make(1, mark) + Stdlib__String.sub(line, idx + 1 | 0, (line.length - idx | 0) - 1 | 0));
  }), ls);
  return {
    TAG: /* Ok */ 0,
    _0: Stdlib__String.concat("\n", rewritten)
  };
}

export {
  normalize_crlf,
  lines_of,
  starts_with,
  ends_with,
  contains,
  find_from,
  trim,
  is_space,
  strip_bom,
  unquote,
  parse_simple_yaml,
  attr,
  parse_frontmatter,
  first_heading,
  is_heading_1_3,
  contains_word_ci,
  parse_constitution,
  has_fail_word,
  constitution_gate_failing,
  parse_task_id,
  parse_task_line,
  is_t_tag,
  split_tag_value,
  find_keyword_ci,
  take_keyword_tag,
  drop_range,
  parse_task_rest,
  dedup_add,
  with_inferred_deps,
  parse_tasks_markdown,
  extract_wiki_links,
  derive_feature_status,
  infer_horizon,
  assemble_feature,
  set_task_checkbox,
}
/* No side effect */
