// Generated by Melange

import * as Caml_string from "melange.js/caml_string.js";
import * as Melange__Context_gen from "./context_gen.js";
import * as Melange__Domain from "./domain.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Option from "melange/option.js";
import * as Stdlib__String from "melange/string.js";

function str(s) {
  return s;
}

function $$int(i) {
  return i;
}

function $$float(f) {
  return f;
}

function bool(b) {
  return b;
}

const $$null = null;

const arr = Stdlib__Array.of_list;

function obj(kvs) {
  const d = {};
  Stdlib__List.iter((function (param) {
    d[param[0]] = param[1];
  }), kvs);
  return d;
}

function opt_str(s) {
  if (s !== undefined) {
    return s;
  } else {
    return $$null;
  }
}

function opt_int(i) {
  if (i !== undefined) {
    return i;
  } else {
    return $$null;
  }
}

const Json = {
  str,
  $$int,
  $$float,
  bool,
  $$null,
  arr,
  obj,
  opt_str,
  opt_int
};

const horizon_json = Melange__Domain.horizon_to_string;

function priority_json(p) {
  if (p !== undefined) {
    return Melange__Domain.priority_to_string(p);
  } else {
    return $$null;
  }
}

function spec_card_json(c) {
  return obj({
    hd: [
      "slug",
      c.slug
    ],
    tl: {
      hd: [
        "title",
        c.title
      ],
      tl: {
        hd: [
          "horizon",
          Melange__Domain.horizon_to_string(c.horizon)
        ],
        tl: {
          hd: [
            "priority",
            priority_json(c.priority)
          ],
          tl: {
            hd: [
              "status",
              Melange__Domain.status_to_string(c.status)
            ],
            tl: {
              hd: [
                "open_tasks",
                c.open_tasks
              ],
              tl: {
                hd: [
                  "total_tasks",
                  c.total_tasks
                ],
                tl: /* [] */ 0
              }
            }
          }
        }
      }
    }
  });
}

function task_card_json(c) {
  return obj({
    hd: [
      "ref",
      c.card_ref
    ],
    tl: {
      hd: [
        "title",
        c.card_title
      ],
      tl: {
        hd: [
          "done",
          c.card_done
        ],
        tl: {
          hd: [
            "spec_slug",
            c.card_spec_slug
          ],
          tl: {
            hd: [
              "priority",
              priority_json(c.card_priority)
            ],
            tl: /* [] */ 0
          }
        }
      }
    }
  });
}

function task_json(t) {
  const s = t.story;
  const s$1 = t.status_tag;
  const s$2 = t.phase;
  return obj({
    hd: [
      "id",
      t.id
    ],
    tl: {
      hd: [
        "title",
        t.title
      ],
      tl: {
        hd: [
          "done",
          t.is_done
        ],
        tl: {
          hd: [
            "parallel",
            t.parallel
          ],
          tl: {
            hd: [
              "story",
              s !== undefined ? s : $$null
            ],
            tl: {
              hd: [
                "points",
                opt_int(t.points)
              ],
              tl: {
                hd: [
                  "rank",
                  opt_int(t.rank)
                ],
                tl: {
                  hd: [
                    "priority",
                    priority_json(t.priority)
                  ],
                  tl: {
                    hd: [
                      "status_tag",
                      s$1 !== undefined ? s$1 : $$null
                    ],
                    tl: {
                      hd: [
                        "phase",
                        s$2 !== undefined ? s$2 : $$null
                      ],
                      tl: {
                        hd: [
                          "spec_slug",
                          t.spec_slug
                        ],
                        tl: {
                          hd: [
                            "depends_on",
                            Stdlib__Array.of_list(Stdlib__List.map(str, t.depends_on))
                          ],
                          tl: {
                            hd: [
                              "body",
                              t.body
                            ],
                            tl: {
                              hd: [
                                "line",
                                t.line
                              ],
                              tl: /* [] */ 0
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  });
}

function blocked_item_json(item) {
  const c = item.card;
  let card;
  card = c.TAG === /* Spec_card */ 0 ? spec_card_json(c._0) : task_card_json(c._0);
  return obj({
    hd: [
      "card",
      card
    ],
    tl: {
      hd: [
        "why",
        item.why
      ],
      tl: {
        hd: [
          "kind",
          item.kind
        ],
        tl: /* [] */ 0
      }
    }
  });
}

function blocked_items_json(items) {
  return Stdlib__Array.of_list(Stdlib__List.map(blocked_item_json, items));
}

function roadmap_json(features) {
  const bucket = function (h) {
    return Stdlib__List.map((function (f) {
      return spec_card_json(Melange__Domain.spec_card(f));
    }), Stdlib__List.filter((function (f) {
      return f.inferred_horizon === h;
    }), features));
  };
  return obj({
    hd: [
      "horizons",
      Stdlib__Array.of_list({
        hd: obj({
          hd: [
            "name",
            "now"
          ],
          tl: {
            hd: [
              "specs",
              Stdlib__Array.of_list(bucket(/* Now */ 0))
            ],
            tl: /* [] */ 0
          }
        }),
        tl: {
          hd: obj({
            hd: [
              "name",
              "next"
            ],
            tl: {
              hd: [
                "specs",
                Stdlib__Array.of_list(bucket(/* Next */ 1))
              ],
              tl: /* [] */ 0
            }
          }),
          tl: {
            hd: obj({
              hd: [
                "name",
                "later"
              ],
              tl: {
                hd: [
                  "specs",
                  Stdlib__Array.of_list(bucket(/* Later */ 2))
                ],
                tl: /* [] */ 0
              }
            }),
            tl: /* [] */ 0
          }
        }
      })
    ],
    tl: /* [] */ 0
  });
}

function backlog_items(features) {
  return Stdlib__List.map(Melange__Domain.task_card, Stdlib__List.concat_map((function (f) {
    return Stdlib__List.filter((function (t) {
      return !t.is_done;
    }), f.tasks);
  }), features));
}

function backlog_json(features) {
  return obj({
    hd: [
      "items",
      Stdlib__Array.of_list(Stdlib__List.map(task_card_json, backlog_items(features)))
    ],
    tl: /* [] */ 0
  });
}

function spec_detail_json(d) {
  const tasks = d.sd_feature.tasks;
  const s = d.sd_plan_md;
  const s$1 = d.sd_tasks_md;
  return obj({
    hd: [
      "card",
      spec_card_json(d.sd_card)
    ],
    tl: {
      hd: [
        "spec_md",
        d.sd_spec_md
      ],
      tl: {
        hd: [
          "plan_md",
          s !== undefined ? s : $$null
        ],
        tl: {
          hd: [
            "tasks_md",
            s$1 !== undefined ? s$1 : $$null
          ],
          tl: {
            hd: [
              "plan_present",
              d.sd_plan_present
            ],
            tl: {
              hd: [
                "task_counts",
                obj({
                  hd: [
                    "open",
                    d.sd_open
                  ],
                  tl: {
                    hd: [
                      "total",
                      d.sd_total
                    ],
                    tl: /* [] */ 0
                  }
                })
              ],
              tl: {
                hd: [
                  "tasks",
                  Stdlib__Array.of_list(Stdlib__List.map(task_json, tasks))
                ],
                tl: {
                  hd: [
                    "siblings",
                    Stdlib__Array.of_list(Stdlib__List.map(str, d.sd_feature.siblings))
                  ],
                  tl: /* [] */ 0
                }
              }
            }
          }
        }
      }
    }
  });
}

function spec_detail_of_feature(f) {
  const open_ = Stdlib__List.length(Stdlib__List.filter((function (t) {
    return !t.is_done;
  }), f.tasks));
  return {
    sd_card: Melange__Domain.spec_card(f),
    sd_spec_md: f.spec_md,
    sd_plan_md: f.plan_md,
    sd_tasks_md: f.tasks_md,
    sd_plan_present: f.plan_md !== undefined,
    sd_open: open_,
    sd_total: Stdlib__List.length(f.tasks),
    sd_feature: f
  };
}

function task_detail_json(d) {
  return obj({
    hd: [
      "card",
      task_card_json(d.td_card)
    ],
    tl: {
      hd: [
        "body",
        d.td_body
      ],
      tl: {
        hd: [
          "spec_slug",
          d.td_slug
        ],
        tl: {
          hd: [
            "blockers",
            Stdlib__Array.of_list(Stdlib__List.map(task_card_json, d.td_blockers))
          ],
          tl: {
            hd: [
              "task",
              task_json(d.td_task)
            ],
            tl: /* [] */ 0
          }
        }
      }
    }
  });
}

function task_detail_of(f, t) {
  const blockers = Stdlib__List.filter_map((function (id) {
    const dep = Stdlib__List.find_opt((function (x) {
      return x.id === id;
    }), f.tasks);
    if (dep !== undefined && !dep.is_done) {
      return Melange__Domain.task_card(dep);
    }
    
  }), t.depends_on);
  return {
    td_card: Melange__Domain.task_card(t),
    td_body: t.body,
    td_slug: f.slug,
    td_blockers: blockers,
    td_task: t
  };
}

function graph_typed(features) {
  const match = Stdlib__List.fold_left((function (param, f) {
    const nodes = Stdlib.$at(param[0], {
      hd: {
        node_id: f.slug,
        node_kind: "spec",
        node_title: f.title,
        node_status: Melange__Domain.status_to_string(f.status)
      },
      tl: /* [] */ 0
    });
    const match = Stdlib__List.fold_left((function (param, t) {
      const nodes = Stdlib.$at(param[0], {
        hd: {
          node_id: Melange__Domain.make_ref(f.slug, t.id),
          node_kind: "task",
          node_title: t.title,
          node_status: t.is_done ? "done" : "open"
        },
        tl: /* [] */ 0
      });
      const edges = Stdlib.$at(param[1], {
        hd: {
          g_edge_from: f.slug,
          g_edge_to: Melange__Domain.make_ref(f.slug, t.id),
          g_edge_kind: "contains"
        },
        tl: /* [] */ 0
      });
      const edges$1 = Stdlib.$at(edges, Stdlib__List.map((function (dep) {
        return {
          g_edge_from: Melange__Domain.make_ref(f.slug, dep),
          g_edge_to: Melange__Domain.make_ref(f.slug, t.id),
          g_edge_kind: "depends"
        };
      }), t.depends_on));
      return [
        nodes,
        edges$1
      ];
    }), [
      nodes,
      param[1]
    ], f.tasks);
    const edges = Stdlib.$at(match[1], Stdlib__List.filter_map((function (link) {
      const slug = link.slug;
      if (slug === undefined) {
        return;
      }
      if (slug === f.slug) {
        return;
      }
      const tid = link.task_id;
      return {
        g_edge_from: f.slug,
        g_edge_to: tid !== undefined ? Melange__Domain.make_ref(slug, tid) : slug,
        g_edge_kind: "wiki"
      };
    }), f.wiki_links));
    return [
      match[0],
      edges
    ];
  }), [
    /* [] */ 0,
    /* [] */ 0
  ], features);
  return {
    nodes: match[0],
    edges: match[1]
  };
}

function graph_json(features) {
  const match = graph_typed(features);
  const node_json = function (n) {
    return obj({
      hd: [
        "id",
        n.node_id
      ],
      tl: {
        hd: [
          "kind",
          n.node_kind
        ],
        tl: {
          hd: [
            "title",
            n.node_title
          ],
          tl: {
            hd: [
              "status",
              n.node_status
            ],
            tl: /* [] */ 0
          }
        }
      }
    });
  };
  const edge_json = function (e) {
    return obj({
      hd: [
        "from",
        e.g_edge_from
      ],
      tl: {
        hd: [
          "to",
          e.g_edge_to
        ],
        tl: {
          hd: [
            "kind",
            e.g_edge_kind
          ],
          tl: /* [] */ 0
        }
      }
    });
  };
  return obj({
    hd: [
      "nodes",
      Stdlib__Array.of_list(Stdlib__List.map(node_json, match.nodes))
    ],
    tl: {
      hd: [
        "edges",
        Stdlib__Array.of_list(Stdlib__List.map(edge_json, match.edges))
      ],
      tl: /* [] */ 0
    }
  });
}

function metrics_json(features) {
  const m = Melange__Context_gen.metrics_of(features);
  const match = m.m_by_horizon;
  return obj({
    hd: [
      "features",
      m.m_features
    ],
    tl: {
      hd: [
        "by_status",
        obj(Stdlib__List.map((function (param) {
          return [
            param[0],
            param[1]
          ];
        }), m.m_by_status))
      ],
      tl: {
        hd: [
          "by_horizon",
          obj({
            hd: [
              "now",
              match[0]
            ],
            tl: {
              hd: [
                "next",
                match[1]
              ],
              tl: {
                hd: [
                  "later",
                  match[2]
                ],
                tl: /* [] */ 0
              }
            }
          })
        ],
        tl: {
          hd: [
            "open_tasks",
            m.m_open_tasks
          ],
          tl: {
            hd: [
              "total_tasks",
              m.m_total_tasks
            ],
            tl: /* [] */ 0
          }
        }
      }
    }
  });
}

function summary_visual_json(features, blocked) {
  return obj({
    hd: [
      "in_flight",
      Stdlib__Array.of_list(Stdlib__List.map((function (f) {
        return spec_card_json(Melange__Domain.spec_card(f));
      }), Melange__Context_gen.in_flight(features)))
    ],
    tl: {
      hd: [
        "blocked",
        Stdlib__Array.of_list(Stdlib__List.map(blocked_item_json, blocked))
      ],
      tl: {
        hd: [
          "priority_queue",
          Stdlib__Array.of_list(Stdlib__List.map((function (t) {
            return task_card_json(Melange__Domain.task_card(t));
          }), Melange__Context_gen.ready_tasks(features)))
        ],
        tl: {
          hd: [
            "metrics",
            metrics_json(features)
          ],
          tl: /* [] */ 0
        }
      }
    }
  });
}

function catalog_of(features, constitution, memory_hits) {
  const specs = Stdlib__List.map((function (f) {
    return [
      f.slug,
      spec_detail_of_feature(f)
    ];
  }), features);
  const tasks = Stdlib__List.fold_left((function (acc, f) {
    return Stdlib__List.fold_left((function (acc, t) {
      const detail = task_detail_of(f, t);
      const acc_0 = [
        Melange__Domain.make_ref(f.slug, t.id),
        [
          detail,
          false
        ]
      ];
      const acc$1 = {
        hd: acc_0,
        tl: acc
      };
      const bare = Stdlib__String.uppercase_ascii(t.id);
      const match = Stdlib__List.assoc_opt(bare, acc$1);
      if (match !== undefined) {
        return Stdlib__List.map((function (param) {
          const v = param[1];
          const k = param[0];
          if (k === bare) {
            return [
              k,
              [
                v[0],
                true
              ]
            ];
          } else {
            return [
              k,
              v
            ];
          }
        }), acc$1);
      } else {
        return {
          hd: [
            bare,
            [
              detail,
              false
            ]
          ],
          tl: acc$1
        };
      }
    }), acc, f.tasks);
  }), /* [] */ 0, features);
  const blocked = Melange__Context_gen.blocked_tasks(features);
  return {
    cat_slugs: Stdlib__List.map((function (f) {
      return f.slug;
    }), features),
    cat_summary_json: summary_visual_json(features, blocked),
    cat_in_flight: Stdlib__List.map(Melange__Domain.spec_card, Melange__Context_gen.in_flight(features)),
    cat_ready: Stdlib__List.map(Melange__Domain.task_card, Melange__Context_gen.ready_tasks(features)),
    cat_blocked: blocked,
    cat_roadmap_json: roadmap_json(features),
    cat_roadmap_specs: Stdlib__List.map((function (f) {
      return f.slug;
    }), features),
    cat_backlog_json: backlog_json(features),
    cat_blocked_json: obj({
      hd: [
        "items",
        Stdlib__Array.of_list(Stdlib__List.map(blocked_item_json, blocked))
      ],
      tl: /* [] */ 0
    }),
    cat_graph_json: graph_json(features),
    cat_specs: specs,
    cat_tasks: tasks,
    cat_constitution: constitution,
    cat_memory_hits: memory_hits
  };
}

function find_feature(features, slug) {
  return Stdlib__List.find_opt((function (f) {
    return f.slug === slug;
  }), features);
}

function find_task(features, ref_) {
  const i = Stdlib__String.index_opt(ref_, /* '#' */35);
  let match;
  if (i !== undefined) {
    match = [
      Stdlib__String.sub(ref_, 0, i),
      Stdlib__String.uppercase_ascii(Stdlib__String.sub(ref_, i + 1 | 0, (ref_.length - i | 0) - 1 | 0))
    ];
  } else {
    const n = ref_.length;
    let looks_like_task = false;
    if (n >= 2) {
      let tmp = false;
      if (Caml_string.get(ref_, 0) === /* 'T' */84 || Caml_string.get(ref_, 0) === /* 't' */116) {
        const digits = function (_i) {
          while (true) {
            const i = _i;
            if (i >= n) {
              return true;
            }
            if (!Melange__Domain.is_digit(Caml_string.get(ref_, i))) {
              return false;
            }
            _i = i + 1 | 0;
            continue;
          };
        };
        tmp = digits(1);
      }
      looks_like_task = tmp;
    }
    match = looks_like_task ? [
        undefined,
        Stdlib__String.uppercase_ascii(ref_)
      ] : [
        ref_,
        undefined
      ];
  }
  const task_id = match[1];
  const slug = match[0];
  if (slug !== undefined) {
    if (task_id === undefined) {
      return;
    }
    const hit_of = function (f) {
      return Stdlib__Option.map((function (t) {
        return [
          f,
          t
        ];
      }), Stdlib__List.find_opt((function (t) {
        return Stdlib__String.uppercase_ascii(t.id) === task_id;
      }), f.tasks));
    };
    return Stdlib__Option.bind(find_feature(features, slug), hit_of);
  }
  if (task_id === undefined) {
    return;
  }
  const hit_of$1 = function (f) {
    return Stdlib__Option.map((function (t) {
      return [
        f,
        t
      ];
    }), Stdlib__List.find_opt((function (t) {
      return Stdlib__String.uppercase_ascii(t.id) === task_id;
    }), f.tasks));
  };
  const hits = Stdlib__List.filter_map(hit_of$1, features);
  if (hits && !hits.tl) {
    return hits.hd;
  }
  
}

export {
  Json,
  horizon_json,
  priority_json,
  spec_card_json,
  task_card_json,
  task_json,
  blocked_item_json,
  blocked_items_json,
  roadmap_json,
  backlog_items,
  backlog_json,
  spec_detail_json,
  spec_detail_of_feature,
  task_detail_json,
  task_detail_of,
  graph_typed,
  graph_json,
  metrics_json,
  summary_visual_json,
  catalog_of,
  find_feature,
  find_task,
}
/* null Not a pure module */
