(lang dune 3.8)
(name status_dash)

(using melange 0.1)

(generate_opam_files true)

(package
 (name status_dash)
 (synopsis "Spec-kit reading surface domain")
 (depends
  (ocaml (and (>= 5.5.0) (< 5.6)))
  (dune (= 3.24.2))
  (melange (= 7.0.1-55))
  (ocamlformat (and (= 0.29.0) :with-dev-setup)))
 (allow_empty))
